// ==============================================================
// Generated by Vitis HLS v2024.2.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module system_top_module2_coarse_cfo_Pipeline_PHASE_D (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m1_to_m2_data_dout,
        m1_to_m2_data_empty_n,
        m1_to_m2_data_read,
        m1_to_m2_data_num_data_valid,
        m1_to_m2_data_fifo_cap,
        m2_to_m4_data_din,
        m2_to_m4_data_full_n,
        m2_to_m4_data_write,
        m2_to_m4_data_num_data_valid,
        m2_to_m4_data_fifo_cap,
        m2_search_buffer_din,
        m2_search_buffer_full_n,
        m2_search_buffer_write,
        m2_search_buffer_num_data_valid,
        m2_search_buffer_fifo_cap,
        num_samples,
        empty,
        sext_ln138,
        early_buf_re_address0,
        early_buf_re_ce0,
        early_buf_re_q0,
        early_buf_im_address0,
        early_buf_im_ce0,
        early_buf_im_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] m1_to_m2_data_dout;
input   m1_to_m2_data_empty_n;
output   m1_to_m2_data_read;
input  [6:0] m1_to_m2_data_num_data_valid;
input  [6:0] m1_to_m2_data_fifo_cap;
output  [31:0] m2_to_m4_data_din;
input   m2_to_m4_data_full_n;
output   m2_to_m4_data_write;
input  [11:0] m2_to_m4_data_num_data_valid;
input  [11:0] m2_to_m4_data_fifo_cap;
output  [31:0] m2_search_buffer_din;
input   m2_search_buffer_full_n;
output   m2_search_buffer_write;
input  [10:0] m2_search_buffer_num_data_valid;
input  [10:0] m2_search_buffer_fifo_cap;
input  [31:0] num_samples;
input  [10:0] empty;
input  [28:0] sext_ln138;
output  [10:0] early_buf_re_address0;
output   early_buf_re_ce0;
input  [15:0] early_buf_re_q0;
output  [10:0] early_buf_im_address0;
output   early_buf_im_ce0;
input  [15:0] early_buf_im_q0;

reg ap_idle;
reg m1_to_m2_data_read;
reg m2_to_m4_data_write;
reg m2_search_buffer_write;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
reg    ap_block_state3_pp0_stage0_iter2_grp1;
reg    ap_block_pp0_stage0_subdone_grp1_done_reg;
reg    ap_block_pp0_stage0_subdone_grp1;
reg    ap_block_pp0_stage0_subdone;
reg   [0:0] icmp_ln155_reg_494;
reg   [0:0] icmp_ln155_reg_494_pp0_iter3_reg;
reg    ap_block_state5_pp0_stage0_iter4_grp2;
reg    ap_block_pp0_stage0_subdone_grp2_done_reg;
reg    ap_block_pp0_stage0_subdone_grp2;
wire   [0:0] icmp_ln150_fu_222_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [9:0] m2_cos_lut_address0;
wire   [15:0] m2_cos_lut_q0;
wire   [9:0] m2_sin_lut_address0;
wire   [15:0] m2_sin_lut_q0;
reg    m1_to_m2_data_blk_n;
wire    ap_block_pp0_stage0_grp1;
reg    m2_to_m4_data_blk_n;
reg    m2_search_buffer_blk_n;
wire    ap_block_pp0_stage0_grp2;
reg    ap_block_pp0_stage0_11001;
wire  signed [31:0] sext_ln138_cast_fu_193_p1;
reg  signed [31:0] sext_ln138_cast_reg_485;
wire   [0:0] icmp_ln155_fu_231_p2;
reg   [0:0] icmp_ln155_reg_494_pp0_iter2_reg;
reg   [15:0] raw_re_reg_518;
reg   [15:0] raw_im_reg_523;
reg   [15:0] cos_val_reg_528;
reg   [15:0] sin_val_reg_533;
reg   [15:0] trunc_ln164_2_reg_538;
reg    ap_block_pp0_stage0_11001_grp2;
reg   [15:0] trunc_ln165_2_reg_543;
wire   [63:0] zext_ln157_fu_245_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln160_fu_301_p1;
reg   [30:0] n_fu_90;
wire   [30:0] n_11_fu_328_p2;
wire    ap_loop_init;
reg   [31:0] phase_acc_fu_94;
wire   [31:0] phase_acc_3_fu_307_p2;
reg   [31:0] search_cnt_fu_98;
wire   [31:0] search_cnt_3_fu_312_p2;
reg    ap_block_pp0_stage0_11001_grp1;
reg    ap_block_pp0_stage0_01001_grp1;
reg    ap_block_pp0_stage0_01001_grp2;
reg    early_buf_re_ce0_local;
reg    early_buf_im_ce0_local;
reg    m2_cos_lut_ce0_local;
reg    m2_sin_lut_ce0_local;
wire   [31:0] zext_ln150_fu_218_p1;
wire   [10:0] trunc_ln150_fu_227_p1;
wire   [10:0] buf_idx_fu_240_p2;
wire   [15:0] trunc_ln159_fu_269_p1;
wire   [9:0] trunc_ln_fu_251_p4;
wire   [0:0] icmp_ln159_fu_273_p2;
wire   [9:0] add_ln159_fu_279_p2;
wire   [0:0] tmp_10_fu_261_p3;
wire   [9:0] select_ln159_fu_285_p3;
wire   [9:0] ref_tmp_i_i_0_i_fu_293_p3;
wire  signed [15:0] mul_ln164_fu_345_p0;
wire  signed [29:0] sext_ln164_fu_339_p1;
wire  signed [15:0] mul_ln164_fu_345_p1;
wire  signed [29:0] sext_ln164_1_fu_342_p1;
wire  signed [15:0] mul_ln164_1_fu_357_p0;
wire  signed [29:0] sext_ln164_2_fu_351_p1;
wire  signed [15:0] mul_ln164_1_fu_357_p1;
wire  signed [29:0] sext_ln164_3_fu_354_p1;
wire   [29:0] mul_ln164_fu_345_p2;
wire   [29:0] mul_ln164_1_fu_357_p2;
wire   [25:0] trunc_ln5_fu_363_p4;
wire   [25:0] trunc_ln164_1_fu_373_p4;
wire   [25:0] sub_ln164_fu_383_p2;
wire  signed [15:0] mul_ln165_fu_399_p0;
wire  signed [15:0] mul_ln165_fu_399_p1;
wire  signed [15:0] mul_ln165_1_fu_405_p0;
wire  signed [15:0] mul_ln165_1_fu_405_p1;
wire   [29:0] mul_ln165_fu_399_p2;
wire   [29:0] mul_ln165_1_fu_405_p2;
wire   [25:0] trunc_ln6_fu_411_p4;
wire   [25:0] trunc_ln165_1_fu_421_p4;
wire   [25:0] add_ln165_fu_431_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_448;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp1_done_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp2_done_reg = 1'b0;
#0 n_fu_90 = 31'd0;
#0 phase_acc_fu_94 = 32'd0;
#0 search_cnt_fu_98 = 32'd0;
#0 ap_done_reg = 1'b0;
end

system_top_module2_coarse_cfo_Pipeline_PHASE_D_m2_cos_lut_ROM_AUTO_1R #(
    .DataWidth( 16 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
m2_cos_lut_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(m2_cos_lut_address0),
    .ce0(m2_cos_lut_ce0_local),
    .q0(m2_cos_lut_q0)
);

system_top_module2_coarse_cfo_Pipeline_PHASE_D_m2_sin_lut_ROM_AUTO_1R #(
    .DataWidth( 16 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
m2_sin_lut_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(m2_sin_lut_address0),
    .ce0(m2_sin_lut_ce0_local),
    .q0(m2_sin_lut_q0)
);

system_top_mul_16s_16s_30_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 30 ))
mul_16s_16s_30_1_1_U124(
    .din0(mul_ln164_fu_345_p0),
    .din1(mul_ln164_fu_345_p1),
    .dout(mul_ln164_fu_345_p2)
);

system_top_mul_16s_16s_30_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 30 ))
mul_16s_16s_30_1_1_U125(
    .din0(mul_ln164_1_fu_357_p0),
    .din1(mul_ln164_1_fu_357_p1),
    .dout(mul_ln164_1_fu_357_p2)
);

system_top_mul_16s_16s_30_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 30 ))
mul_16s_16s_30_1_1_U126(
    .din0(mul_ln165_fu_399_p0),
    .din1(mul_ln165_fu_399_p1),
    .dout(mul_ln165_fu_399_p2)
);

system_top_mul_16s_16s_30_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 30 ))
mul_16s_16s_30_1_1_U127(
    .din0(mul_ln165_1_fu_405_p0),
    .din1(mul_ln165_1_fu_405_p1),
    .dout(mul_ln165_1_fu_405_p2)
);

system_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp1_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp1_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp1)) begin
            ap_block_pp0_stage0_subdone_grp1_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp2_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp2_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp2)) begin
            ap_block_pp0_stage0_subdone_grp2_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            n_fu_90 <= 31'd2048;
        end else if (((icmp_ln150_fu_222_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            n_fu_90 <= n_11_fu_328_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            phase_acc_fu_94 <= 32'd0;
        end else if ((1'b1 == ap_condition_448)) begin
            phase_acc_fu_94 <= phase_acc_3_fu_307_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            search_cnt_fu_98 <= 32'd0;
        end else if ((1'b1 == ap_condition_448)) begin
            search_cnt_fu_98 <= search_cnt_3_fu_312_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        icmp_ln155_reg_494 <= icmp_ln155_fu_231_p2;
        sext_ln138_cast_reg_485 <= sext_ln138_cast_fu_193_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        cos_val_reg_528 <= m2_cos_lut_q0;
        icmp_ln155_reg_494_pp0_iter2_reg <= icmp_ln155_reg_494;
        icmp_ln155_reg_494_pp0_iter3_reg <= icmp_ln155_reg_494_pp0_iter2_reg;
        raw_im_reg_523 <= early_buf_im_q0;
        raw_re_reg_518 <= early_buf_re_q0;
        sin_val_reg_533 <= m2_sin_lut_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp2))) begin
        trunc_ln164_2_reg_538 <= {{sub_ln164_fu_383_p2[25:10]}};
        trunc_ln165_2_reg_543 <= {{add_ln165_fu_431_p2[25:10]}};
    end
end

always @ (*) begin
    if (((icmp_ln150_fu_222_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        early_buf_im_ce0_local = 1'b1;
    end else begin
        early_buf_im_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        early_buf_re_ce0_local = 1'b1;
    end else begin
        early_buf_re_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        m1_to_m2_data_blk_n = m1_to_m2_data_empty_n;
    end else begin
        m1_to_m2_data_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        m1_to_m2_data_read = 1'b1;
    end else begin
        m1_to_m2_data_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m2_cos_lut_ce0_local = 1'b1;
    end else begin
        m2_cos_lut_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln155_reg_494_pp0_iter3_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (1'b0 == ap_block_pp0_stage0_grp2) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        m2_search_buffer_blk_n = m2_search_buffer_full_n;
    end else begin
        m2_search_buffer_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln155_reg_494_pp0_iter3_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp2) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        m2_search_buffer_write = 1'b1;
    end else begin
        m2_search_buffer_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m2_sin_lut_ce0_local = 1'b1;
    end else begin
        m2_sin_lut_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        m2_to_m4_data_blk_n = m2_to_m4_data_full_n;
    end else begin
        m2_to_m4_data_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        m2_to_m4_data_write = 1'b1;
    end else begin
        m2_to_m4_data_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln159_fu_279_p2 = (trunc_ln_fu_251_p4 + 10'd1);

assign add_ln165_fu_431_p2 = (trunc_ln6_fu_411_p4 + trunc_ln165_1_fu_421_p4);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = ((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2_grp1));
end

always @ (*) begin
    ap_block_pp0_stage0_01001_grp2 = ((1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage0_iter4_grp2));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage0_iter4_grp2)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2_grp1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2_grp1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp2 = ((1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage0_iter4_grp2));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage0_iter4_grp2)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2_grp1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp1 = ((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2_grp1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp2 = ((1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage0_iter4_grp2));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2_grp1 = ((m2_to_m4_data_full_n == 1'b0) | (m1_to_m2_data_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state5_pp0_stage0_iter4_grp2 = ((icmp_ln155_reg_494_pp0_iter3_reg == 1'd1) & (m2_search_buffer_full_n == 1'b0));
end

always @ (*) begin
    ap_condition_448 = ((icmp_ln150_fu_222_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln155_fu_231_p2 == 1'd1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_ready = ap_ready_sig;

assign buf_idx_fu_240_p2 = (trunc_ln150_fu_227_p1 + empty);

assign early_buf_im_address0 = zext_ln157_fu_245_p1;

assign early_buf_im_ce0 = early_buf_im_ce0_local;

assign early_buf_re_address0 = zext_ln157_fu_245_p1;

assign early_buf_re_ce0 = early_buf_re_ce0_local;

assign icmp_ln150_fu_222_p2 = (($signed(zext_ln150_fu_218_p1) < $signed(num_samples)) ? 1'b1 : 1'b0);

assign icmp_ln155_fu_231_p2 = (($signed(search_cnt_fu_98) < $signed(32'd640)) ? 1'b1 : 1'b0);

assign icmp_ln159_fu_273_p2 = ((trunc_ln159_fu_269_p1 != 16'd0) ? 1'b1 : 1'b0);

assign m2_cos_lut_address0 = zext_ln160_fu_301_p1;

assign m2_search_buffer_din = {{trunc_ln165_2_reg_543}, {trunc_ln164_2_reg_538}};

assign m2_sin_lut_address0 = zext_ln160_fu_301_p1;

assign m2_to_m4_data_din = m1_to_m2_data_dout;

assign mul_ln164_1_fu_357_p0 = sext_ln164_2_fu_351_p1;

assign mul_ln164_1_fu_357_p1 = sext_ln164_3_fu_354_p1;

assign mul_ln164_fu_345_p0 = sext_ln164_fu_339_p1;

assign mul_ln164_fu_345_p1 = sext_ln164_1_fu_342_p1;

assign mul_ln165_1_fu_405_p0 = sext_ln164_fu_339_p1;

assign mul_ln165_1_fu_405_p1 = sext_ln164_3_fu_354_p1;

assign mul_ln165_fu_399_p0 = sext_ln164_2_fu_351_p1;

assign mul_ln165_fu_399_p1 = sext_ln164_1_fu_342_p1;

assign n_11_fu_328_p2 = (n_fu_90 + 31'd1);

assign phase_acc_3_fu_307_p2 = ($signed(phase_acc_fu_94) + $signed(sext_ln138_cast_reg_485));

assign ref_tmp_i_i_0_i_fu_293_p3 = ((tmp_10_fu_261_p3[0:0] == 1'b1) ? select_ln159_fu_285_p3 : trunc_ln_fu_251_p4);

assign search_cnt_3_fu_312_p2 = (search_cnt_fu_98 + 32'd1);

assign select_ln159_fu_285_p3 = ((icmp_ln159_fu_273_p2[0:0] == 1'b1) ? add_ln159_fu_279_p2 : trunc_ln_fu_251_p4);

assign sext_ln138_cast_fu_193_p1 = $signed(sext_ln138);

assign sext_ln164_1_fu_342_p1 = $signed(raw_re_reg_518);

assign sext_ln164_2_fu_351_p1 = $signed(sin_val_reg_533);

assign sext_ln164_3_fu_354_p1 = $signed(raw_im_reg_523);

assign sext_ln164_fu_339_p1 = $signed(cos_val_reg_528);

assign sub_ln164_fu_383_p2 = (trunc_ln5_fu_363_p4 - trunc_ln164_1_fu_373_p4);

assign tmp_10_fu_261_p3 = phase_acc_fu_94[32'd31];

assign trunc_ln150_fu_227_p1 = search_cnt_fu_98[10:0];

assign trunc_ln159_fu_269_p1 = phase_acc_fu_94[15:0];

assign trunc_ln164_1_fu_373_p4 = {{mul_ln164_1_fu_357_p2[29:4]}};

assign trunc_ln165_1_fu_421_p4 = {{mul_ln165_1_fu_405_p2[29:4]}};

assign trunc_ln5_fu_363_p4 = {{mul_ln164_fu_345_p2[29:4]}};

assign trunc_ln6_fu_411_p4 = {{mul_ln165_fu_399_p2[29:4]}};

assign trunc_ln_fu_251_p4 = {{phase_acc_fu_94[25:16]}};

assign zext_ln150_fu_218_p1 = n_fu_90;

assign zext_ln157_fu_245_p1 = buf_idx_fu_240_p2;

assign zext_ln160_fu_301_p1 = ref_tmp_i_i_0_i_fu_293_p3;

endmodule //system_top_module2_coarse_cfo_Pipeline_PHASE_D
