// ==============================================================
// Generated by Vitis HLS v2024.2.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module system_top_module2_coarse_cfo_Pipeline_PHASE_A (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m1_to_m2_data_dout,
        m1_to_m2_data_empty_n,
        m1_to_m2_data_read,
        m1_to_m2_data_num_data_valid,
        m1_to_m2_data_fifo_cap,
        m2_to_m4_data_din,
        m2_to_m4_data_full_n,
        m2_to_m4_data_write,
        m2_to_m4_data_num_data_valid,
        m2_to_m4_data_fifo_cap,
        m1_startOffset_dout,
        m1_startOffset_empty_n,
        m1_startOffset_read,
        m1_startOffset_num_data_valid,
        m1_startOffset_fifo_cap,
        m2_to_m4_startOffset_din,
        m2_to_m4_startOffset_full_n,
        m2_to_m4_startOffset_write,
        m2_to_m4_startOffset_num_data_valid,
        m2_to_m4_startOffset_fifo_cap,
        sO_rx_out,
        sO_rx_out_ap_vld,
        startOffset_out,
        startOffset_out_ap_vld,
        early_buf_re_address1,
        early_buf_re_ce1,
        early_buf_re_we1,
        early_buf_re_d1,
        early_buf_im_address1,
        early_buf_im_ce1,
        early_buf_im_we1,
        early_buf_im_d1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] m1_to_m2_data_dout;
input   m1_to_m2_data_empty_n;
output   m1_to_m2_data_read;
input  [6:0] m1_to_m2_data_num_data_valid;
input  [6:0] m1_to_m2_data_fifo_cap;
output  [31:0] m2_to_m4_data_din;
input   m2_to_m4_data_full_n;
output   m2_to_m4_data_write;
input  [11:0] m2_to_m4_data_num_data_valid;
input  [11:0] m2_to_m4_data_fifo_cap;
input  [15:0] m1_startOffset_dout;
input   m1_startOffset_empty_n;
output   m1_startOffset_read;
input  [2:0] m1_startOffset_num_data_valid;
input  [2:0] m1_startOffset_fifo_cap;
output  [15:0] m2_to_m4_startOffset_din;
input   m2_to_m4_startOffset_full_n;
output   m2_to_m4_startOffset_write;
input  [2:0] m2_to_m4_startOffset_num_data_valid;
input  [2:0] m2_to_m4_startOffset_fifo_cap;
output  [0:0] sO_rx_out;
output   sO_rx_out_ap_vld;
output  [15:0] startOffset_out;
output   startOffset_out_ap_vld;
output  [10:0] early_buf_re_address1;
output   early_buf_re_ce1;
output   early_buf_re_we1;
output  [15:0] early_buf_re_d1;
output  [10:0] early_buf_im_address1;
output   early_buf_im_ce1;
output   early_buf_im_we1;
output  [15:0] early_buf_im_d1;

reg ap_idle;
reg m1_to_m2_data_read;
reg m2_to_m4_data_write;
reg m1_startOffset_read;
reg m2_to_m4_startOffset_write;
reg sO_rx_out_ap_vld;
reg startOffset_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
reg   [0:0] icmp_ln88_reg_279;
reg    ap_block_state2_pp0_stage0_iter1_grp1;
reg    ap_block_pp0_stage0_subdone_grp1_done_reg;
reg    ap_block_pp0_stage0_subdone_grp1;
reg    ap_block_pp0_stage0_subdone;
reg   [0:0] ap_phi_mux_sO_rx_phi_fu_175_p4;
wire   [0:0] tmp_13_i_nbreadreq_fu_102_p3;
reg    ap_predicate_op38_read_state2;
reg    ap_block_state2_pp0_stage0_iter1_grp2;
reg    ap_block_pp0_stage0_subdone_grp2_done_reg;
reg    ap_block_pp0_stage0_subdone_grp2;
reg   [0:0] icmp_ln88_reg_279_pp0_iter1_reg;
reg   [0:0] sO_rx_reg_171;
reg   [0:0] tmp_13_i_reg_283;
reg    ap_predicate_op43_write_state3;
reg    ap_block_state3_pp0_stage0_iter2_grp2;
wire   [0:0] icmp_ln88_fu_213_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    m1_to_m2_data_blk_n;
wire    ap_block_pp0_stage0_grp1;
reg    m2_to_m4_data_blk_n;
reg    m1_startOffset_blk_n;
wire    ap_block_pp0_stage0_grp2;
reg    m2_to_m4_startOffset_blk_n;
reg   [0:0] sO_rx_1_reg_184;
reg   [11:0] n_12_reg_274;
reg    ap_block_pp0_stage0_11001;
reg    ap_block_pp0_stage0_11001_grp2;
reg   [15:0] startOffset_4_reg_287;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_init;
wire    ap_block_pp0_stage0;
wire   [0:0] ap_phi_reg_pp0_iter1_sO_rx_1_reg_184;
wire   [63:0] zext_ln88_fu_230_p1;
reg   [11:0] n_fu_80;
wire   [11:0] add_ln88_fu_219_p2;
reg   [11:0] ap_sig_allocacmp_n_12;
reg   [15:0] startOffset_fu_84;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_block_pp0_stage0_11001_grp1;
reg    ap_block_pp0_stage0_01001_grp1;
reg    ap_block_pp0_stage0_01001_grp2;
reg    early_buf_re_we1_local;
wire   [15:0] sample_re_fu_235_p1;
reg    early_buf_re_ce1_local;
reg    early_buf_im_we1_local;
reg    early_buf_im_ce1_local;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_353;
reg    ap_condition_181;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp1_done_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp2_done_reg = 1'b0;
#0 n_fu_80 = 12'd0;
#0 startOffset_fu_84 = 16'd0;
#0 ap_done_reg = 1'b0;
end

system_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp1_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp1_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp1)) begin
            ap_block_pp0_stage0_subdone_grp1_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp2_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp2_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp2)) begin
            ap_block_pp0_stage0_subdone_grp2_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln88_fu_213_p2 == 1'd0))) begin
            n_fu_80 <= add_ln88_fu_219_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            n_fu_80 <= 12'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_13_i_nbreadreq_fu_102_p3 == 1'd0) & (ap_phi_mux_sO_rx_phi_fu_175_p4 == 1'd0) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp2) & (icmp_ln88_reg_279 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sO_rx_1_reg_184 <= 1'd0;
    end else if ((((tmp_13_i_nbreadreq_fu_102_p3 == 1'd1) & (ap_phi_mux_sO_rx_phi_fu_175_p4 == 1'd0) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp2) & (icmp_ln88_reg_279 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_phi_mux_sO_rx_phi_fu_175_p4 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp2) & (icmp_ln88_reg_279 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        sO_rx_1_reg_184 <= 1'd1;
    end else if ((~(icmp_ln88_reg_279 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sO_rx_1_reg_184 <= ap_phi_reg_pp0_iter1_sO_rx_1_reg_184;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln88_reg_279_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp2) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        sO_rx_reg_171 <= sO_rx_1_reg_184;
    end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        sO_rx_reg_171 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_181)) begin
        if ((ap_loop_init == 1'b1)) begin
            startOffset_fu_84 <= 16'd0;
        end else if ((1'b1 == ap_condition_353)) begin
            startOffset_fu_84 <= m1_startOffset_dout;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln88_reg_279 <= icmp_ln88_fu_213_p2;
        icmp_ln88_reg_279_pp0_iter1_reg <= icmp_ln88_reg_279;
        n_12_reg_274 <= ap_sig_allocacmp_n_12;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp2) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        startOffset_4_reg_287 <= m1_startOffset_dout;
        tmp_13_i_reg_283 <= tmp_13_i_nbreadreq_fu_102_p3;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln88_fu_213_p2 == 1'd1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln88_reg_279 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln88_reg_279_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_phi_mux_sO_rx_phi_fu_175_p4 = sO_rx_1_reg_184;
    end else begin
        ap_phi_mux_sO_rx_phi_fu_175_p4 = sO_rx_reg_171;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_n_12 = 12'd0;
    end else begin
        ap_sig_allocacmp_n_12 = n_fu_80;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        early_buf_im_ce1_local = 1'b1;
    end else begin
        early_buf_im_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (icmp_ln88_reg_279 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        early_buf_im_we1_local = 1'b1;
    end else begin
        early_buf_im_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        early_buf_re_ce1_local = 1'b1;
    end else begin
        early_buf_re_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (icmp_ln88_reg_279 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        early_buf_re_we1_local = 1'b1;
    end else begin
        early_buf_re_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op38_read_state2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (1'b0 == ap_block_pp0_stage0_grp2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m1_startOffset_blk_n = m1_startOffset_empty_n;
    end else begin
        m1_startOffset_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_predicate_op38_read_state2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m1_startOffset_read = 1'b1;
    end else begin
        m1_startOffset_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage0_grp1) & (icmp_ln88_reg_279 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m1_to_m2_data_blk_n = m1_to_m2_data_empty_n;
    end else begin
        m1_to_m2_data_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (icmp_ln88_reg_279 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m1_to_m2_data_read = 1'b1;
    end else begin
        m1_to_m2_data_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage0_grp1) & (icmp_ln88_reg_279 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m2_to_m4_data_blk_n = m2_to_m4_data_full_n;
    end else begin
        m2_to_m4_data_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (icmp_ln88_reg_279 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m2_to_m4_data_write = 1'b1;
    end else begin
        m2_to_m4_data_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (1'b0 == ap_block_pp0_stage0_grp2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op43_write_state3 == 1'b1))) begin
        m2_to_m4_startOffset_blk_n = m2_to_m4_startOffset_full_n;
    end else begin
        m2_to_m4_startOffset_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op43_write_state3 == 1'b1))) begin
        m2_to_m4_startOffset_write = 1'b1;
    end else begin
        m2_to_m4_startOffset_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp2) & (icmp_ln88_reg_279 == 1'd1) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sO_rx_out_ap_vld = 1'b1;
    end else begin
        sO_rx_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp2) & (icmp_ln88_reg_279 == 1'd1) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        startOffset_out_ap_vld = 1'b1;
    end else begin
        startOffset_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln88_fu_219_p2 = (ap_sig_allocacmp_n_12 + 12'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = ((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp1));
end

always @ (*) begin
    ap_block_pp0_stage0_01001_grp2 = (((1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp2)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2_grp2)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (((1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp2)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp1)))) | ((1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2_grp2)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp2 = (((1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp2)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2_grp2)));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter1 == 1'b1) & (((1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp2)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp1)))) | ((1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2_grp2)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp1 = ((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp2 = (((1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp2)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2_grp2)));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1_grp1 = (((icmp_ln88_reg_279 == 1'd0) & (m2_to_m4_data_full_n == 1'b0)) | ((icmp_ln88_reg_279 == 1'd0) & (m1_to_m2_data_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1_grp2 = ((ap_predicate_op38_read_state2 == 1'b1) & (m1_startOffset_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2_grp2 = ((m2_to_m4_startOffset_full_n == 1'b0) & (ap_predicate_op43_write_state3 == 1'b1));
end

always @ (*) begin
    ap_condition_181 = ((1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp2) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_353 = ((tmp_13_i_nbreadreq_fu_102_p3 == 1'd1) & (ap_phi_mux_sO_rx_phi_fu_175_p4 == 1'd0) & (icmp_ln88_reg_279 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter1_sO_rx_1_reg_184 = 'bx;

always @ (*) begin
    ap_predicate_op38_read_state2 = ((tmp_13_i_nbreadreq_fu_102_p3 == 1'd1) & (ap_phi_mux_sO_rx_phi_fu_175_p4 == 1'd0) & (icmp_ln88_reg_279 == 1'd0));
end

always @ (*) begin
    ap_predicate_op43_write_state3 = ((icmp_ln88_reg_279_pp0_iter1_reg == 1'd0) & (tmp_13_i_reg_283 == 1'd1) & (sO_rx_reg_171 == 1'd0));
end

assign ap_ready = ap_ready_sig;

assign early_buf_im_address1 = zext_ln88_fu_230_p1;

assign early_buf_im_ce1 = early_buf_im_ce1_local;

assign early_buf_im_d1 = {{m1_to_m2_data_dout[31:16]}};

assign early_buf_im_we1 = early_buf_im_we1_local;

assign early_buf_re_address1 = zext_ln88_fu_230_p1;

assign early_buf_re_ce1 = early_buf_re_ce1_local;

assign early_buf_re_d1 = sample_re_fu_235_p1;

assign early_buf_re_we1 = early_buf_re_we1_local;

assign icmp_ln88_fu_213_p2 = ((ap_sig_allocacmp_n_12 == 12'd2048) ? 1'b1 : 1'b0);

assign m2_to_m4_data_din = m1_to_m2_data_dout;

assign m2_to_m4_startOffset_din = startOffset_4_reg_287;

assign sO_rx_out = sO_rx_reg_171;

assign sample_re_fu_235_p1 = m1_to_m2_data_dout[15:0];

assign startOffset_out = startOffset_fu_84;

assign tmp_13_i_nbreadreq_fu_102_p3 = m1_startOffset_empty_n;

assign zext_ln88_fu_230_p1 = n_12_reg_274;

endmodule //system_top_module2_coarse_cfo_Pipeline_PHASE_A
