// -------------------------------------------------------------
// 
// File Name: hdl_prj/hdlsrc/wlanhdlTimeAndFrequencySynchronization/CordicKernelMag_block55.v
// Created: 2026-02-04 22:38:44
// 
// Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: CordicKernelMag_block55
// Source Path: wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Fine CFO Estimation and 
// Correction/Fine CFO Estimation/Complex to Magnitude-Angle
// Hierarchy Level: 3
// Model version: 9.2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module CordicKernelMag_block55
          (clk,
           reset,
           enb,
           xin,
           yin,
           zin,
           lut_value,
           idx,
           yout,
           zout);


  input   clk;
  input   reset;
  input   enb;
  input   signed [31:0] xin;  // sfix32_En19
  input   signed [31:0] yin;  // sfix32_En19
  input   signed [33:0] zin;  // sfix34_En33
  input   [30:0] lut_value;  // ufix31_En33
  input   [5:0] idx;  // ufix6
  output  signed [31:0] yout;  // sfix32_En19
  output  signed [33:0] zout;  // sfix34_En33


  reg signed [31:0] yin_1;  // sfix32_En19
  wire yLessThanZero;
  reg  yLessThanZero_1;
  reg signed [31:0] xin_1;  // sfix32_En19
  wire [7:0] dynamic_shift_cast;  // uint8
  wire signed [31:0] xShifted;  // sfix32_En19
  wire signed [31:0] yout2;  // sfix32_En19
  reg signed [31:0] yout2_1;  // sfix32_En19
  wire signed [31:0] yout1;  // sfix32_En19
  reg signed [31:0] yout1_1;  // sfix32_En19
  reg signed [33:0] zin_1;  // sfix34_En33
  wire signed [33:0] ZAdder_add_cast;  // sfix34_En33
  wire signed [33:0] zout2;  // sfix34_En33
  reg signed [33:0] zout2_1;  // sfix34_En33
  wire signed [33:0] ZSub_sub_cast;  // sfix34_En33
  wire signed [33:0] zout1;  // sfix34_En33
  reg signed [33:0] zout1_1;  // sfix34_En33


  always @(posedge clk or posedge reset)
    begin : rd_1_process
      if (reset == 1'b1) begin
        yin_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          yin_1 <= yin;
        end
      end
    end

  assign yLessThanZero = yin_1 < 32'sb00000000000000000000000000000000;

  always @(posedge clk or posedge reset)
    begin : rd_3_process
      if (reset == 1'b1) begin
        yLessThanZero_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          yLessThanZero_1 <= yLessThanZero;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : rd_0_process
      if (reset == 1'b1) begin
        xin_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          xin_1 <= xin;
        end
      end
    end

  assign dynamic_shift_cast = {2'b0, idx};
  assign xShifted = xin_1 >>> dynamic_shift_cast;

  assign yout2 = yin_1 - xShifted;

  always @(posedge clk or posedge reset)
    begin : rd_6_process
      if (reset == 1'b1) begin
        yout2_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          yout2_1 <= yout2;
        end
      end
    end

  assign yout1 = yin_1 + xShifted;

  always @(posedge clk or posedge reset)
    begin : rd_5_process
      if (reset == 1'b1) begin
        yout1_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          yout1_1 <= yout1;
        end
      end
    end

  assign yout = (yLessThanZero_1 == 1'b0 ? yout2_1 :
              yout1_1);

  always @(posedge clk or posedge reset)
    begin : rd_7_process
      if (reset == 1'b1) begin
        zin_1 <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          zin_1 <= zin;
        end
      end
    end

  assign ZAdder_add_cast = {3'b0, lut_value};
  assign zout2 = zin_1 + ZAdder_add_cast;

  always @(posedge clk or posedge reset)
    begin : rd_9_process
      if (reset == 1'b1) begin
        zout2_1 <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          zout2_1 <= zout2;
        end
      end
    end

  assign ZSub_sub_cast = {3'b0, lut_value};
  assign zout1 = zin_1 - ZSub_sub_cast;

  always @(posedge clk or posedge reset)
    begin : rd_8_process
      if (reset == 1'b1) begin
        zout1_1 <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          zout1_1 <= zout1;
        end
      end
    end

  assign zout = (yLessThanZero_1 == 1'b0 ? zout2_1 :
              zout1_1);

endmodule  // CordicKernelMag_block55

