// -------------------------------------------------------------
// 
// File Name: hdl_prj/hdlsrc/wlanhdlTimeAndFrequencySynchronization/DTadjust.v
// Created: 2026-02-04 22:38:43
// 
// Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: DTadjust
// Source Path: wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Coarse Time Sync/Correlator/delayedCorrelation/DTadjust
// Hierarchy Level: 4
// Model version: 9.2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module DTadjust
          (in_re,
           in_im,
           out_re,
           out_im);


  input   signed [31:0] in_re;  // sfix32_En24
  input   signed [31:0] in_im;  // sfix32_En24
  output  signed [31:0] out_re;  // sfix32_En26
  output  signed [31:0] out_im;  // sfix32_En26




  assign out_re = ((in_re[31] == 1'b0) && (in_re[30:29] != 2'b00) ? 32'sb01111111111111111111111111111111 :
              ((in_re[31] == 1'b1) && (in_re[30:29] != 2'b11) ? 32'sb10000000000000000000000000000000 :
              {in_re[29:0], 2'b00}));
  assign out_im = ((in_im[31] == 1'b0) && (in_im[30:29] != 2'b00) ? 32'sb01111111111111111111111111111111 :
              ((in_im[31] == 1'b1) && (in_im[30:29] != 2'b11) ? 32'sb10000000000000000000000000000000 :
              {in_im[29:0], 2'b00}));

endmodule  // DTadjust

