open_system('wlanhdlTimeAndFrequencySynchronization');
open_system('gm_wlanhdlTimeAndFrequencySynchronization');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Coarse Time Sync/Peak Detector/considerFirstPeak/Logical Operator6', 'user5');
hilite_system('wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Coarse Time Sync/Peak Detector/considerFirstPeak/Logical Operator6', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Coarse Time Sync/Peak Detector/considerFirstPeak/rd_14', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Coarse Time Sync/Peak Detector/considerFirstPeak/HDL Counter1', 'user5');
hilite_system('wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Coarse Time Sync/Peak Detector/considerFirstPeak/HDL Counter1', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Coarse Time Sync/Peak Detector/considerFirstPeak/Delay9', 'user5');
hilite_system('wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Coarse Time Sync/Peak Detector/considerFirstPeak/Delay9', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Coarse Time Sync/Peak Detector/considerFirstPeak/HDL Counter1_absorbed', 'user5');
hilite_system('wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Coarse Time Sync/Peak Detector/considerFirstPeak/HDL Counter1', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Fine Time Sync/Peak Searcher/peakDetector/switchReset', 'user5');
hilite_system('wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Fine Time Sync/Peak Searcher/peakDetector/HDL Counter2', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Fine Time Sync/Peak Searcher/peakDetector/switchEnable', 'user5');
hilite_system('wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Fine Time Sync/Peak Searcher/peakDetector/HDL Counter2', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Fine Time Sync/Peak Searcher/peakDetector/rd_10', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Fine Time Sync/Peak Searcher/peakDetector/rd_3', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Fine Time Sync/Peak Searcher/peakDetector/rd_6', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Fine Time Sync/Peak Searcher/peakDetector/crp_out_delay1', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Fine Time Sync/Peak Searcher/peakDetector/HDL Counter2', 'user5');
hilite_system('wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Fine Time Sync/Peak Searcher/peakDetector/HDL Counter2', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Fine Time Sync/Peak Searcher/peakDetector/HDL Counter2_absorbed', 'user5');
hilite_system('wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Fine Time Sync/Peak Searcher/peakDetector/HDL Counter2', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Fine Time Sync/Peak Searcher/peakDetector/Logical Operator6', 'user5');
hilite_system('wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Fine Time Sync/Peak Searcher/peakDetector/Logical Operator6', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Fine Time Sync/Peak Searcher/peakDetector/rd_51', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Fine Time Sync/Peak Searcher/peakDetector/Delay12', 'user5');
hilite_system('wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Fine Time Sync/Peak Searcher/peakDetector/Delay12', 'user5');
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Fine Time Sync/Peak Searcher/peakDetector/Delay12_absorbed', 'user4');
hilite_system('wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Fine Time Sync/Peak Searcher/peakDetector/Delay12', 'user4');
