open_system('wlanhdlTimeAndFrequencySynchronization');
open_system('gm_wlanhdlTimeAndFrequencySynchronization');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Coarse CFO Estimation and Correction/Coarse CFO Correction/DTConverter', 'user2');
annotate_port('gm_wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Coarse CFO Estimation and Correction/Coarse CFO Correction/DTConverter', 1, 1, 'This MATLAB Function block participating in code reuse inhibits clock-rate pipelining. Consider setting either the ''Architecture'' to ''MATLAB Datapath'' or the model property ''SubsystemReuse'' to ''off''.');
hilite_system('wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Coarse CFO Estimation and Correction/Coarse CFO Correction/DTConverter', 'user2');
annotate_port('wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Coarse CFO Estimation and Correction/Coarse CFO Correction/DTConverter', 1, 1, 'This MATLAB Function block participating in code reuse inhibits clock-rate pipelining. Consider setting either the ''Architecture'' to ''MATLAB Datapath'' or the model property ''SubsystemReuse'' to ''off''.');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Coarse CFO Estimation and Correction/Coarse CFO Correction/NCO', 'user2');
annotate_port('gm_wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Coarse CFO Estimation and Correction/Coarse CFO Correction/NCO', 1, 1, 'Unsupported block for clock-rate pipelining');
hilite_system('wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Coarse CFO Estimation and Correction/Coarse CFO Correction/NCO', 'user2');
annotate_port('wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Coarse CFO Estimation and Correction/Coarse CFO Correction/NCO', 1, 1, 'Unsupported block for clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Coarse CFO Estimation and Correction/Coarse CFO Correction/NCO', 'user2');
annotate_port('gm_wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Coarse CFO Estimation and Correction/Coarse CFO Correction/NCO', 1, 1, 'Unsupported block for clock-rate pipelining');
hilite_system('wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Coarse CFO Estimation and Correction/Coarse CFO Correction/NCO', 'user2');
annotate_port('wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Coarse CFO Estimation and Correction/Coarse CFO Correction/NCO', 1, 1, 'Unsupported block for clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Coarse CFO Estimation and Correction/Coarse CFO Estimation/Sample FreqOff', 'user2');
annotate_port('gm_wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Coarse CFO Estimation and Correction/Coarse CFO Estimation/Sample FreqOff', 1, 1, 'Stateful MATLAB Function blocks can be clock-rate pipelined internally, but the block boundary is not clock-rate pipelined unless they use the ''MATLAB Datapath'' architecture. Set the architecture to ''MATLAB Datapath'' or remove the use of persistent variables.');
hilite_system('wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Coarse CFO Estimation and Correction/Coarse CFO Estimation/Sample FreqOff', 'user2');
annotate_port('wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Coarse CFO Estimation and Correction/Coarse CFO Estimation/Sample FreqOff', 1, 1, 'Stateful MATLAB Function blocks can be clock-rate pipelined internally, but the block boundary is not clock-rate pipelined unless they use the ''MATLAB Datapath'' architecture. Set the architecture to ''MATLAB Datapath'' or remove the use of persistent variables.');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Coarse Time Sync/Energy Calculator/streamSynchronizer/StreamSyncronizer', 'user2');
annotate_port('gm_wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Coarse Time Sync/Energy Calculator/streamSynchronizer/StreamSyncronizer', 1, 1, 'Stateful MATLAB Function blocks can be clock-rate pipelined internally, but the block boundary is not clock-rate pipelined unless they use the ''MATLAB Datapath'' architecture. Set the architecture to ''MATLAB Datapath'' or remove the use of persistent variables.');
hilite_system('wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Coarse Time Sync/Energy Calculator/streamSynchronizer/StreamSyncronizer', 'user2');
annotate_port('wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Coarse Time Sync/Energy Calculator/streamSynchronizer/StreamSyncronizer', 1, 1, 'Stateful MATLAB Function blocks can be clock-rate pipelined internally, but the block boundary is not clock-rate pipelined unless they use the ''MATLAB Datapath'' architecture. Set the architecture to ''MATLAB Datapath'' or remove the use of persistent variables.');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Coarse Time Sync/Peak Detector/MATLAB Function1', 'user2');
annotate_port('gm_wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Coarse Time Sync/Peak Detector/MATLAB Function1', 1, 1, 'This MATLAB Function block participating in code reuse inhibits clock-rate pipelining. Consider setting either the ''Architecture'' to ''MATLAB Datapath'' or the model property ''SubsystemReuse'' to ''off''.');
hilite_system('wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Coarse Time Sync/Peak Detector/MATLAB Function1', 'user2');
annotate_port('wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Coarse Time Sync/Peak Detector/MATLAB Function1', 1, 1, 'This MATLAB Function block participating in code reuse inhibits clock-rate pipelining. Consider setting either the ''Architecture'' to ''MATLAB Datapath'' or the model property ''SubsystemReuse'' to ''off''.');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Coarse Time Sync/Peak Detector/searchStartOfFrame', 'user2');
annotate_port('gm_wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Coarse Time Sync/Peak Detector/searchStartOfFrame', 1, 1, 'Stateful MATLAB Function blocks can be clock-rate pipelined internally, but the block boundary is not clock-rate pipelined unless they use the ''MATLAB Datapath'' architecture. Set the architecture to ''MATLAB Datapath'' or remove the use of persistent variables.');
hilite_system('wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Coarse Time Sync/Peak Detector/searchStartOfFrame', 'user2');
annotate_port('wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Coarse Time Sync/Peak Detector/searchStartOfFrame', 1, 1, 'Stateful MATLAB Function blocks can be clock-rate pipelined internally, but the block boundary is not clock-rate pipelined unless they use the ''MATLAB Datapath'' architecture. Set the architecture to ''MATLAB Datapath'' or remove the use of persistent variables.');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Coarse Time Sync/Stream Synchronizer/StreamSyncronizer', 'user2');
annotate_port('gm_wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Coarse Time Sync/Stream Synchronizer/StreamSyncronizer', 1, 1, 'Stateful MATLAB Function blocks can be clock-rate pipelined internally, but the block boundary is not clock-rate pipelined unless they use the ''MATLAB Datapath'' architecture. Set the architecture to ''MATLAB Datapath'' or remove the use of persistent variables.');
hilite_system('wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Coarse Time Sync/Stream Synchronizer/StreamSyncronizer', 'user2');
annotate_port('wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Coarse Time Sync/Stream Synchronizer/StreamSyncronizer', 1, 1, 'Stateful MATLAB Function blocks can be clock-rate pipelined internally, but the block boundary is not clock-rate pipelined unless they use the ''MATLAB Datapath'' architecture. Set the architecture to ''MATLAB Datapath'' or remove the use of persistent variables.');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Fine CFO Estimation and Correction/Fine CFO Correction/DTConverter', 'user2');
annotate_port('gm_wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Fine CFO Estimation and Correction/Fine CFO Correction/DTConverter', 1, 1, 'This MATLAB Function block participating in code reuse inhibits clock-rate pipelining. Consider setting either the ''Architecture'' to ''MATLAB Datapath'' or the model property ''SubsystemReuse'' to ''off''.');
hilite_system('wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Fine CFO Estimation and Correction/Fine CFO Correction/DTConverter', 'user2');
annotate_port('wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Fine CFO Estimation and Correction/Fine CFO Correction/DTConverter', 1, 1, 'This MATLAB Function block participating in code reuse inhibits clock-rate pipelining. Consider setting either the ''Architecture'' to ''MATLAB Datapath'' or the model property ''SubsystemReuse'' to ''off''.');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Fine CFO Estimation and Correction/Fine CFO Correction/NCO', 'user2');
annotate_port('gm_wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Fine CFO Estimation and Correction/Fine CFO Correction/NCO', 1, 1, 'Unsupported block for clock-rate pipelining');
hilite_system('wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Fine CFO Estimation and Correction/Fine CFO Correction/NCO', 'user2');
annotate_port('wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Fine CFO Estimation and Correction/Fine CFO Correction/NCO', 1, 1, 'Unsupported block for clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Fine CFO Estimation and Correction/Fine CFO Correction/NCO', 'user2');
annotate_port('gm_wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Fine CFO Estimation and Correction/Fine CFO Correction/NCO', 1, 1, 'Unsupported block for clock-rate pipelining');
hilite_system('wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Fine CFO Estimation and Correction/Fine CFO Correction/NCO', 'user2');
annotate_port('wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Fine CFO Estimation and Correction/Fine CFO Correction/NCO', 1, 1, 'Unsupported block for clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Fine CFO Estimation and Correction/Fine CFO Estimation/sample FreqOff', 'user2');
annotate_port('gm_wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Fine CFO Estimation and Correction/Fine CFO Estimation/sample FreqOff', 1, 1, 'Stateful MATLAB Function blocks can be clock-rate pipelined internally, but the block boundary is not clock-rate pipelined unless they use the ''MATLAB Datapath'' architecture. Set the architecture to ''MATLAB Datapath'' or remove the use of persistent variables.');
hilite_system('wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Fine CFO Estimation and Correction/Fine CFO Estimation/sample FreqOff', 'user2');
annotate_port('wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Fine CFO Estimation and Correction/Fine CFO Estimation/sample FreqOff', 1, 1, 'Stateful MATLAB Function blocks can be clock-rate pipelined internally, but the block boundary is not clock-rate pipelined unless they use the ''MATLAB Datapath'' architecture. Set the architecture to ''MATLAB Datapath'' or remove the use of persistent variables.');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Fine Time Sync/Peak Searcher/maxPeakSearcher/maxPeakSearcher', 'user2');
annotate_port('gm_wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Fine Time Sync/Peak Searcher/maxPeakSearcher/maxPeakSearcher', 1, 1, 'Stateful MATLAB Function blocks can be clock-rate pipelined internally, but the block boundary is not clock-rate pipelined unless they use the ''MATLAB Datapath'' architecture. Set the architecture to ''MATLAB Datapath'' or remove the use of persistent variables.');
hilite_system('wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Fine Time Sync/Peak Searcher/maxPeakSearcher/maxPeakSearcher', 'user2');
annotate_port('wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Fine Time Sync/Peak Searcher/maxPeakSearcher/maxPeakSearcher', 1, 1, 'Stateful MATLAB Function blocks can be clock-rate pipelined internally, but the block boundary is not clock-rate pipelined unless they use the ''MATLAB Datapath'' architecture. Set the architecture to ''MATLAB Datapath'' or remove the use of persistent variables.');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Fine Time Sync/Peak Searcher/peakDetector/dataSelector ', 'user2');
annotate_port('gm_wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Fine Time Sync/Peak Searcher/peakDetector/dataSelector ', 1, 1, 'This MATLAB Function block participating in code reuse inhibits clock-rate pipelining. Consider setting either the ''Architecture'' to ''MATLAB Datapath'' or the model property ''SubsystemReuse'' to ''off''.');
hilite_system('wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Fine Time Sync/Peak Searcher/peakDetector/dataSelector ', 'user2');
annotate_port('wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Fine Time Sync/Peak Searcher/peakDetector/dataSelector ', 1, 1, 'This MATLAB Function block participating in code reuse inhibits clock-rate pipelining. Consider setting either the ''Architecture'' to ''MATLAB Datapath'' or the model property ''SubsystemReuse'' to ''off''.');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Rx Filter/Discrete FIR Filter', 'user2');
annotate_port('gm_wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Rx Filter/Discrete FIR Filter', 1, 1, 'Unsupported block for clock-rate pipelining');
hilite_system('wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Rx Filter/Discrete FIR Filter', 'user2');
annotate_port('wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Rx Filter/Discrete FIR Filter', 1, 1, 'Unsupported block for clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Rx Filter/Discrete FIR Filter', 'user2');
annotate_port('gm_wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Rx Filter/Discrete FIR Filter', 1, 1, 'Unsupported block for clock-rate pipelining');
hilite_system('wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Rx Filter/Discrete FIR Filter', 'user2');
annotate_port('wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Rx Filter/Discrete FIR Filter', 1, 1, 'Unsupported block for clock-rate pipelining');
