// -------------------------------------------------------------
// 
// File Name: hdl_prj/hdlsrc/wlanhdlTimeAndFrequencySynchronization/maxPeakSearcher.v
// Created: 2026-02-04 22:38:44
// 
// Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: maxPeakSearcher
// Source Path: wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Fine Time Sync/Peak Searcher/maxPeakSearcher/maxPeakSearcher
// Hierarchy Level: 4
// Model version: 9.2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module maxPeakSearcher
          (clk,
           reset,
           enb_1_8_0,
           dataIn,
           validIn,
           countValue,
           reset_1,
           maxPeak);


  input   clk;
  input   reset;
  input   enb_1_8_0;
  input   signed [31:0] dataIn;  // sfix32_En15
  input   validIn;
  input   [15:0] countValue;  // uint16
  input   reset_1;
  output  [15:0] maxPeak;  // uint16


  reg [15:0] maxPeak_1;  // uint16
  reg [15:0] maxPeakReg;  // uint16
  reg  maxPeakReg_not_empty;
  reg [15:0] maxPeakPrev;  // uint16
  reg signed [31:0] maxValueReg;  // sfix32
  reg [15:0] maxPeakReg_next;  // uint16
  reg  maxPeakReg_not_empty_next;
  reg [15:0] maxPeakPrev_next;  // uint16
  reg signed [31:0] maxValueReg_next;  // sfix32_En15
  reg [15:0] maxPeakReg_temp;  // uint16
  reg [15:0] maxPeakPrev_temp;  // uint16
  reg signed [31:0] maxValueReg_temp;  // sfix32_En15
  reg signed [16:0] sub_temp;  // sfix17
  reg signed [16:0] t_0;  // sfix17


  always @(posedge clk or posedge reset)
    begin : maxPeakSearcher_1_process
      if (reset == 1'b1) begin
        maxPeakReg_not_empty <= 1'b0;
      end
      else begin
        if (enb_1_8_0) begin
          maxPeakReg <= maxPeakReg_next;
          maxPeakReg_not_empty <= maxPeakReg_not_empty_next;
          maxPeakPrev <= maxPeakPrev_next;
          maxValueReg <= maxValueReg_next;
        end
      end
    end

  always @(countValue, dataIn, maxPeakPrev, maxPeakReg, maxPeakReg_not_empty, maxValueReg,
       reset_1, validIn) begin
    sub_temp = 17'sb00000000000000000;
    t_0 = 17'sb00000000000000000;
    maxPeakReg_temp = maxPeakReg;
    maxPeakPrev_temp = maxPeakPrev;
    maxValueReg_temp = maxValueReg;
    maxPeakReg_not_empty_next = maxPeakReg_not_empty;
    if (( ! maxPeakReg_not_empty) || reset_1) begin
      maxValueReg_temp = 32'sb00000000000000000000000000000000;
      maxPeakReg_temp = 16'd0;
      maxPeakReg_not_empty_next = 1'b1;
      maxPeakPrev_temp = 16'd0;
    end
    if (validIn && (dataIn > maxValueReg_temp)) begin
      maxPeakReg_temp = countValue;
      maxValueReg_temp = dataIn;
    end
    if (countValue == 16'd127) begin
      t_0 = {1'b0, maxPeakReg_temp};
      sub_temp = t_0 - 17'sb00000000001000000;
      if (sub_temp[16] == 1'b1) begin
        maxPeakPrev_temp = 16'b0000000000000000;
      end
      else begin
        maxPeakPrev_temp = sub_temp[15:0];
      end
    end
    maxPeak_1 = maxPeakPrev_temp;
    maxPeakReg_next = maxPeakReg_temp;
    maxPeakPrev_next = maxPeakPrev_temp;
    maxValueReg_next = maxValueReg_temp;
  end

  assign maxPeak = maxPeak_1;

endmodule  // maxPeakSearcher

