// -------------------------------------------------------------
// 
// File Name: hdl_prj/hdlsrc/wlanhdlTimeAndFrequencySynchronization/MovingSum.v
// Created: 2026-02-04 22:38:43
// 
// Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: MovingSum
// Source Path: wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Coarse Time Sync/Correlator/MovingSum
// Hierarchy Level: 3
// Model version: 9.2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module MovingSum
          (clk,
           reset,
           enb_1_8_1,
           enb_1_8_0,
           enb,
           dataIn_re,
           dataIn_im,
           validIn,
           reset_1,
           dataOut_re,
           dataOut_im,
           validOut);


  input   clk;
  input   reset;
  input   enb_1_8_1;
  input   enb_1_8_0;
  input   enb;
  input   signed [31:0] dataIn_re;  // sfix32_En26
  input   signed [31:0] dataIn_im;  // sfix32_En26
  input   validIn;
  input   reset_1;
  output  signed [32:0] dataOut_re;  // sfix33_En26
  output  signed [32:0] dataOut_im;  // sfix33_En26
  output  validOut;


  wire validIn_1;
  reg  validIn_2;
  reg  Delay3_out1;
  wire Delay3_out1_1;
  reg  [1:0] rd_4_reg;  // ufix1 [2]
  wire Delay3_out1_2;
  wire signed [31:0] dataIn_re_1;  // sfix32_En26
  wire signed [31:0] dataIn_im_1;  // sfix32_En26
  reg signed [31:0] dataIn_re_2;  // sfix32_En26
  reg signed [31:0] dataIn_im_2;  // sfix32_En26
  wire signed [31:0] Synchronous_Enabled_128_Sample_Delay_dataOut_re;  // sfix32_En26
  wire signed [31:0] Synchronous_Enabled_128_Sample_Delay_dataOut_im;  // sfix32_En26
  wire signed [31:0] Synchronous_Enabled_128_Sample_Delay_dataOut_re_1;  // sfix32_En26
  wire signed [31:0] Synchronous_Enabled_128_Sample_Delay_dataOut_im_1;  // sfix32_En26
  reg signed [31:0] Synchronous_Enabled_128_Sample_Delay_dataOut_re_2;  // sfix32_En26
  reg signed [31:0] Synchronous_Enabled_128_Sample_Delay_dataOut_im_2;  // sfix32_En26
  wire signed [32:0] Add_sub_cast;  // sfix33_En26
  wire signed [32:0] Add_sub_cast_1;  // sfix33_En26
  wire signed [32:0] Add_sub_cast_2;  // sfix33_En26
  wire signed [32:0] Add_sub_cast_3;  // sfix33_En26
  wire signed [32:0] Add_out1_re;  // sfix33_En26
  wire signed [32:0] Add_out1_im;  // sfix33_En26
  reg signed [32:0] Add_out1_re_1;  // sfix33_En26
  reg signed [32:0] Add_out1_im_1;  // sfix33_En26
  wire signed [32:0] Shift_Arithmetic_out1_re;  // sfix33_En26
  wire signed [32:0] Shift_Arithmetic_out1_im;  // sfix33_En26
  reg signed [32:0] Shift_Arithmetic_out1_re_1;  // sfix33_En26
  reg signed [32:0] Shift_Arithmetic_out1_im_1;  // sfix33_En26
  reg signed [32:0] Delay12_bypass_reg_re;  // sfix33_En26
  reg signed [32:0] Delay12_bypass_reg_im;  // sfix33_En26
  wire signed [32:0] Delay12_out1_re;  // sfix33_En26
  wire signed [32:0] Delay12_out1_im;  // sfix33_En26
  wire signed [32:0] Delay12_out1_re_1;  // sfix33_En26
  wire signed [32:0] Delay12_out1_im_1;  // sfix33_En26
  reg signed [32:0] Delay12_out1_re_2;  // sfix33_En26
  reg signed [32:0] Delay12_out1_im_2;  // sfix33_En26
  reg signed [32:0] Synchronous_Enabled_Unit_Delay_out1_re;  // sfix33_En26
  reg signed [32:0] Synchronous_Enabled_Unit_Delay_out1_im;  // sfix33_En26
  wire signed [32:0] Add1_out1_re;  // sfix33_En26
  wire signed [32:0] Add1_out1_im;  // sfix33_En26
  reg signed [32:0] Add1_out1_re_1;  // sfix33_En26
  reg signed [32:0] Add1_out1_im_1;  // sfix33_En26
  wire signed [32:0] Synchronous_Enabled_Unit_Delay_out1_im_1;  // sfix33_En26
  wire signed [32:0] Synchronous_Enabled_Unit_Delay_out1_im_2;  // sfix33_En26
  wire signed [32:0] Synchronous_Enabled_Unit_Delay_out1_re_1;  // sfix33_En26
  wire signed [32:0] Synchronous_Enabled_Unit_Delay_out1_re_2;  // sfix33_En26
  reg signed [32:0] Synchronous_Enabled_Unit_Delay_out1_re_3;  // sfix33_En26
  reg signed [32:0] Synchronous_Enabled_Unit_Delay_out1_im_3;  // sfix33_En26
  wire signed [32:0] Synchronous_Enabled_Unit_Delay_ectrl_re;  // sfix33_En26
  wire signed [32:0] Synchronous_Enabled_Unit_Delay_ectrl_im;  // sfix33_En26
  reg signed [32:0] Synchronous_Enabled_Unit_Delay_ectrl_re_1;  // sfix33_En26
  reg signed [32:0] Synchronous_Enabled_Unit_Delay_ectrl_im_1;  // sfix33_En26
  reg signed [32:0] Synchronous_Enabled_Unit_Delay_lowered_bypass_reg_re;  // sfix33_En26
  reg signed [32:0] Synchronous_Enabled_Unit_Delay_lowered_bypass_reg_im;  // sfix33_En26
  reg signed [32:0] Delay5_out1_re;  // sfix33_En26
  reg signed [32:0] Delay5_out1_im;  // sfix33_En26
  reg  Delay3_out1_3;
  reg  [1:0] Delay6_reg;  // ufix1 [2]
  wire Delay6_out1;


  assign validIn_1 = validIn;

  always @(posedge clk or posedge reset)
    begin : Delay31_output_process
      if (reset == 1'b1) begin
        validIn_2 <= 1'b0;
      end
      else begin
        if (enb_1_8_1) begin
          validIn_2 <= validIn_1;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay3_process
      if (reset == 1'b1) begin
        Delay3_out1 <= 1'b0;
      end
      else begin
        if (enb_1_8_0) begin
          Delay3_out1 <= validIn_2;
        end
      end
    end

  assign Delay3_out1_1 = Delay3_out1;

  always @(posedge clk or posedge reset)
    begin : rd_4_process
      if (reset == 1'b1) begin
        rd_4_reg <= {2{1'b0}};
      end
      else begin
        if (enb) begin
          rd_4_reg[0] <= Delay3_out1_1;
          rd_4_reg[1] <= rd_4_reg[0];
        end
      end
    end

  assign Delay3_out1_2 = rd_4_reg[1];

  assign dataIn_re_1 = dataIn_re;

  assign dataIn_im_1 = dataIn_im;

  always @(posedge clk or posedge reset)
    begin : rd_1_process
      if (reset == 1'b1) begin
        dataIn_re_2 <= 32'sb00000000000000000000000000000000;
        dataIn_im_2 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          dataIn_re_2 <= dataIn_re_1;
          dataIn_im_2 <= dataIn_im_1;
        end
      end
    end

  Synchronous_Enabled_128_Sample_Delay u_Synchronous_Enabled_128_Sample_Delay (.clk(clk),
                                                                               .reset(reset),
                                                                               .enb_1_8_1(enb_1_8_1),
                                                                               .enb(enb),
                                                                               .dataIn_re(dataIn_re),  // sfix32_En26
                                                                               .dataIn_im(dataIn_im),  // sfix32_En26
                                                                               .en(validIn),
                                                                               .reset_1(reset_1),
                                                                               .dataOut_re(Synchronous_Enabled_128_Sample_Delay_dataOut_re),  // sfix32_En26
                                                                               .dataOut_im(Synchronous_Enabled_128_Sample_Delay_dataOut_im)  // sfix32_En26
                                                                               );

  assign Synchronous_Enabled_128_Sample_Delay_dataOut_re_1 = Synchronous_Enabled_128_Sample_Delay_dataOut_re;

  assign Synchronous_Enabled_128_Sample_Delay_dataOut_im_1 = Synchronous_Enabled_128_Sample_Delay_dataOut_im;

  always @(posedge clk or posedge reset)
    begin : rd_2_process
      if (reset == 1'b1) begin
        Synchronous_Enabled_128_Sample_Delay_dataOut_re_2 <= 32'sb00000000000000000000000000000000;
        Synchronous_Enabled_128_Sample_Delay_dataOut_im_2 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          Synchronous_Enabled_128_Sample_Delay_dataOut_re_2 <= Synchronous_Enabled_128_Sample_Delay_dataOut_re_1;
          Synchronous_Enabled_128_Sample_Delay_dataOut_im_2 <= Synchronous_Enabled_128_Sample_Delay_dataOut_im_1;
        end
      end
    end

  assign Add_sub_cast = {dataIn_re_2[31], dataIn_re_2};
  assign Add_sub_cast_1 = {Synchronous_Enabled_128_Sample_Delay_dataOut_re_2[31], Synchronous_Enabled_128_Sample_Delay_dataOut_re_2};
  assign Add_out1_re = Add_sub_cast - Add_sub_cast_1;
  assign Add_sub_cast_2 = {dataIn_im_2[31], dataIn_im_2};
  assign Add_sub_cast_3 = {Synchronous_Enabled_128_Sample_Delay_dataOut_im_2[31], Synchronous_Enabled_128_Sample_Delay_dataOut_im_2};
  assign Add_out1_im = Add_sub_cast_2 - Add_sub_cast_3;

  always @(posedge clk or posedge reset)
    begin : rd_3_process
      if (reset == 1'b1) begin
        Add_out1_re_1 <= 33'sh000000000;
        Add_out1_im_1 <= 33'sh000000000;
      end
      else begin
        if (enb) begin
          Add_out1_re_1 <= Add_out1_re;
          Add_out1_im_1 <= Add_out1_im;
        end
      end
    end

  assign Shift_Arithmetic_out1_re = Add_out1_re_1 >>> 8'd1;
  assign Shift_Arithmetic_out1_im = Add_out1_im_1 >>> 8'd1;

  always @(posedge clk or posedge reset)
    begin : crp_out_delay_process
      if (reset == 1'b1) begin
        Shift_Arithmetic_out1_re_1 <= 33'sh000000000;
        Shift_Arithmetic_out1_im_1 <= 33'sh000000000;
      end
      else begin
        if (enb) begin
          Shift_Arithmetic_out1_re_1 <= Shift_Arithmetic_out1_re;
          Shift_Arithmetic_out1_im_1 <= Shift_Arithmetic_out1_im;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay12_bypass_process
      if (reset == 1'b1) begin
        Delay12_bypass_reg_re <= 33'sh000000000;
        Delay12_bypass_reg_im <= 33'sh000000000;
      end
      else begin
        if (enb_1_8_1) begin
          Delay12_bypass_reg_im <= Shift_Arithmetic_out1_im_1;
          Delay12_bypass_reg_re <= Shift_Arithmetic_out1_re_1;
        end
      end
    end

  assign Delay12_out1_re = (enb_1_8_1 == 1'b1 ? Shift_Arithmetic_out1_re_1 :
              Delay12_bypass_reg_re);
  assign Delay12_out1_im = (enb_1_8_1 == 1'b1 ? Shift_Arithmetic_out1_im_1 :
              Delay12_bypass_reg_im);

  assign Delay12_out1_re_1 = Delay12_out1_re;

  assign Delay12_out1_im_1 = Delay12_out1_im;

  always @(posedge clk or posedge reset)
    begin : rd_21_process
      if (reset == 1'b1) begin
        Delay12_out1_re_2 <= 33'sh000000000;
        Delay12_out1_im_2 <= 33'sh000000000;
      end
      else begin
        if (enb) begin
          Delay12_out1_re_2 <= Delay12_out1_re_1;
          Delay12_out1_im_2 <= Delay12_out1_im_1;
        end
      end
    end

  assign Add1_out1_re = Synchronous_Enabled_Unit_Delay_out1_re + Delay12_out1_re_2;
  assign Add1_out1_im = Synchronous_Enabled_Unit_Delay_out1_im + Delay12_out1_im_2;

  always @(posedge clk or posedge reset)
    begin : rd_31_process
      if (reset == 1'b1) begin
        Add1_out1_re_1 <= 33'sh000000000;
        Add1_out1_im_1 <= 33'sh000000000;
      end
      else begin
        if (enb) begin
          Add1_out1_re_1 <= Add1_out1_re;
          Add1_out1_im_1 <= Add1_out1_im;
        end
      end
    end

  assign Synchronous_Enabled_Unit_Delay_out1_im_2 = Synchronous_Enabled_Unit_Delay_out1_im_1;

  assign Synchronous_Enabled_Unit_Delay_out1_re_2 = Synchronous_Enabled_Unit_Delay_out1_re_1;

  always @(posedge clk or posedge reset)
    begin : rd_11_process
      if (reset == 1'b1) begin
        Synchronous_Enabled_Unit_Delay_out1_re <= 33'sh000000000;
        Synchronous_Enabled_Unit_Delay_out1_im <= 33'sh000000000;
      end
      else begin
        if (enb) begin
          Synchronous_Enabled_Unit_Delay_out1_re <= Synchronous_Enabled_Unit_Delay_out1_re_2;
          Synchronous_Enabled_Unit_Delay_out1_im <= Synchronous_Enabled_Unit_Delay_out1_im_2;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : rd_5_process
      if (reset == 1'b1) begin
        Synchronous_Enabled_Unit_Delay_out1_re_3 <= 33'sh000000000;
        Synchronous_Enabled_Unit_Delay_out1_im_3 <= 33'sh000000000;
      end
      else begin
        if (enb) begin
          Synchronous_Enabled_Unit_Delay_out1_re_3 <= Synchronous_Enabled_Unit_Delay_out1_re;
          Synchronous_Enabled_Unit_Delay_out1_im_3 <= Synchronous_Enabled_Unit_Delay_out1_im;
        end
      end
    end

  assign Synchronous_Enabled_Unit_Delay_ectrl_re = (Delay3_out1_2 == 1'b0 ? Synchronous_Enabled_Unit_Delay_out1_re_3 :
              Add1_out1_re_1);
  assign Synchronous_Enabled_Unit_Delay_ectrl_im = (Delay3_out1_2 == 1'b0 ? Synchronous_Enabled_Unit_Delay_out1_im_3 :
              Add1_out1_im_1);

  always @(posedge clk or posedge reset)
    begin : crp_out_delay1_process
      if (reset == 1'b1) begin
        Synchronous_Enabled_Unit_Delay_ectrl_re_1 <= 33'sh000000000;
        Synchronous_Enabled_Unit_Delay_ectrl_im_1 <= 33'sh000000000;
      end
      else begin
        if (enb) begin
          Synchronous_Enabled_Unit_Delay_ectrl_re_1 <= Synchronous_Enabled_Unit_Delay_ectrl_re;
          Synchronous_Enabled_Unit_Delay_ectrl_im_1 <= Synchronous_Enabled_Unit_Delay_ectrl_im;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Synchronous_Enabled_Unit_Delay_lowered_bypass_process
      if (reset == 1'b1) begin
        Synchronous_Enabled_Unit_Delay_lowered_bypass_reg_re <= 33'sh000000000;
        Synchronous_Enabled_Unit_Delay_lowered_bypass_reg_im <= 33'sh000000000;
      end
      else begin
        if (enb_1_8_1) begin
          Synchronous_Enabled_Unit_Delay_lowered_bypass_reg_im <= Synchronous_Enabled_Unit_Delay_ectrl_im_1;
          Synchronous_Enabled_Unit_Delay_lowered_bypass_reg_re <= Synchronous_Enabled_Unit_Delay_ectrl_re_1;
        end
      end
    end

  assign Synchronous_Enabled_Unit_Delay_out1_re_1 = (enb_1_8_1 == 1'b1 ? Synchronous_Enabled_Unit_Delay_ectrl_re_1 :
              Synchronous_Enabled_Unit_Delay_lowered_bypass_reg_re);
  assign Synchronous_Enabled_Unit_Delay_out1_im_1 = (enb_1_8_1 == 1'b1 ? Synchronous_Enabled_Unit_Delay_ectrl_im_1 :
              Synchronous_Enabled_Unit_Delay_lowered_bypass_reg_im);

  always @(posedge clk or posedge reset)
    begin : Delay5_process
      if (reset == 1'b1) begin
        Delay5_out1_re <= 33'sh000000000;
        Delay5_out1_im <= 33'sh000000000;
      end
      else begin
        if (enb_1_8_0) begin
          Delay5_out1_re <= Synchronous_Enabled_Unit_Delay_out1_re_1;
          Delay5_out1_im <= Synchronous_Enabled_Unit_Delay_out1_im_1;
        end
      end
    end

  assign dataOut_re = Delay5_out1_re;

  assign dataOut_im = Delay5_out1_im;

  always @(posedge clk or posedge reset)
    begin : Delay41_output_process
      if (reset == 1'b1) begin
        Delay3_out1_3 <= 1'b0;
      end
      else begin
        if (enb_1_8_1) begin
          Delay3_out1_3 <= Delay3_out1_1;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay6_process
      if (reset == 1'b1) begin
        Delay6_reg <= {2{1'b0}};
      end
      else begin
        if (enb_1_8_0) begin
          Delay6_reg[0] <= Delay3_out1_3;
          Delay6_reg[1] <= Delay6_reg[0];
        end
      end
    end

  assign Delay6_out1 = Delay6_reg[1];

  assign validOut = Delay6_out1;

endmodule  // MovingSum

