// -------------------------------------------------------------
// 
// File Name: hdl_prj/hdlsrc/wlanhdlTimeAndFrequencySynchronization/Synchronous_Enabled_16_Sample_Delay.v
// Created: 2026-02-04 22:38:43
// 
// Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Synchronous_Enabled_16_Sample_Delay
// Source Path: wlanhdlTimeAndFrequencySynchronization/WLANTimeAndFrequencySynchronization/Coarse Time Sync/Energy 
// Calculator/magnitudeSquared/MovingSum/Synchronous Enabled 16 Sample Delay
// Hierarchy Level: 5
// Model version: 9.2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Synchronous_Enabled_16_Sample_Delay
          (clk,
           reset,
           enb_1_8_1,
           enb,
           dataIn,
           en,
           dataOut);


  input   clk;
  input   reset;
  input   enb_1_8_1;
  input   enb;
  input   signed [33:0] dataIn;  // sfix34_En27
  input   en;
  output  signed [33:0] dataOut;  // sfix34_En27


  wire en_1;
  reg  en_2;
  wire en_3;
  reg  en_4;
  wire en_5;
  reg  en_6;
  wire en_7;
  reg  en_8;
  wire en_9;
  reg  en_10;
  wire en_11;
  reg  en_12;
  wire en_13;
  reg  en_14;
  wire en_15;
  reg  en_16;
  wire en_17;
  reg  en_18;
  wire en_19;
  reg  en_20;
  wire en_21;
  reg  en_22;
  wire en_23;
  reg  en_24;
  wire en_25;
  reg  en_26;
  wire en_27;
  reg  en_28;
  wire en_29;
  reg  en_30;
  wire en_31;
  reg  [1:0] rd_0_reg;  // ufix1 [2]
  wire en_32;
  wire signed [33:0] Delay1_delOut;  // sfix34_En27
  wire signed [33:0] Delay1_delOut_1;  // sfix34_En27
  reg signed [33:0] rd_1_reg [0:1];  // sfix34 [2]
  wire signed [33:0] rd_1_reg_next [0:1];  // sfix34_En27 [2]
  wire signed [33:0] Delay1_delOut_2;  // sfix34_En27
  wire signed [33:0] Delay1_ectrl;  // sfix34_En27
  reg signed [33:0] Delay1_ectrl_1;  // sfix34_En27
  reg signed [33:0] Delay1_lowered_bypass_reg;  // sfix34
  wire signed [33:0] Delay1_delOut_3;  // sfix34_En27
  reg signed [33:0] Delay1_delOut_4;  // sfix34_En27
  wire signed [33:0] Delay1_delOut_5;  // sfix34_En27
  wire signed [33:0] Delay1_delOut_6;  // sfix34_En27
  reg signed [33:0] Delay1_delOut_7;  // sfix34_En27
  wire signed [33:0] Delay1_ectrl_2;  // sfix34_En27
  reg signed [33:0] Delay1_ectrl_3;  // sfix34_En27
  reg signed [33:0] Delay1_lowered1_bypass_reg;  // sfix34
  wire signed [33:0] Delay1_delOut_8;  // sfix34_En27
  reg signed [33:0] Delay1_delOut_9;  // sfix34_En27
  wire signed [33:0] Delay1_delOut_10;  // sfix34_En27
  wire signed [33:0] Delay1_delOut_11;  // sfix34_En27
  reg signed [33:0] Delay1_delOut_12;  // sfix34_En27
  wire signed [33:0] Delay1_ectrl_4;  // sfix34_En27
  reg signed [33:0] Delay1_ectrl_5;  // sfix34_En27
  reg signed [33:0] Delay1_lowered2_bypass_reg;  // sfix34
  wire signed [33:0] Delay1_delOut_13;  // sfix34_En27
  reg signed [33:0] Delay1_delOut_14;  // sfix34_En27
  wire signed [33:0] Delay1_delOut_15;  // sfix34_En27
  wire signed [33:0] Delay1_delOut_16;  // sfix34_En27
  reg signed [33:0] Delay1_delOut_17;  // sfix34_En27
  wire signed [33:0] Delay1_ectrl_6;  // sfix34_En27
  reg signed [33:0] Delay1_ectrl_7;  // sfix34_En27
  reg signed [33:0] Delay1_lowered3_bypass_reg;  // sfix34
  wire signed [33:0] Delay1_delOut_18;  // sfix34_En27
  reg signed [33:0] Delay1_delOut_19;  // sfix34_En27
  wire signed [33:0] Delay1_delOut_20;  // sfix34_En27
  wire signed [33:0] Delay1_delOut_21;  // sfix34_En27
  reg signed [33:0] Delay1_delOut_22;  // sfix34_En27
  wire signed [33:0] Delay1_ectrl_8;  // sfix34_En27
  reg signed [33:0] Delay1_ectrl_9;  // sfix34_En27
  reg signed [33:0] Delay1_lowered4_bypass_reg;  // sfix34
  wire signed [33:0] Delay1_delOut_23;  // sfix34_En27
  reg signed [33:0] Delay1_delOut_24;  // sfix34_En27
  wire signed [33:0] Delay1_delOut_25;  // sfix34_En27
  wire signed [33:0] Delay1_delOut_26;  // sfix34_En27
  reg signed [33:0] Delay1_delOut_27;  // sfix34_En27
  wire signed [33:0] Delay1_ectrl_10;  // sfix34_En27
  reg signed [33:0] Delay1_ectrl_11;  // sfix34_En27
  reg signed [33:0] Delay1_lowered5_bypass_reg;  // sfix34
  wire signed [33:0] Delay1_delOut_28;  // sfix34_En27
  reg signed [33:0] Delay1_delOut_29;  // sfix34_En27
  wire signed [33:0] Delay1_delOut_30;  // sfix34_En27
  wire signed [33:0] Delay1_delOut_31;  // sfix34_En27
  reg signed [33:0] Delay1_delOut_32;  // sfix34_En27
  wire signed [33:0] Delay1_ectrl_12;  // sfix34_En27
  reg signed [33:0] Delay1_ectrl_13;  // sfix34_En27
  reg signed [33:0] Delay1_lowered6_bypass_reg;  // sfix34
  wire signed [33:0] Delay1_delOut_33;  // sfix34_En27
  reg signed [33:0] Delay1_delOut_34;  // sfix34_En27
  wire signed [33:0] Delay1_delOut_35;  // sfix34_En27
  wire signed [33:0] Delay1_delOut_36;  // sfix34_En27
  reg signed [33:0] Delay1_delOut_37;  // sfix34_En27
  wire signed [33:0] Delay1_ectrl_14;  // sfix34_En27
  reg signed [33:0] Delay1_ectrl_15;  // sfix34_En27
  reg signed [33:0] Delay1_lowered7_bypass_reg;  // sfix34
  wire signed [33:0] Delay1_delOut_38;  // sfix34_En27
  reg signed [33:0] Delay1_delOut_39;  // sfix34_En27
  wire signed [33:0] Delay1_delOut_40;  // sfix34_En27
  wire signed [33:0] Delay1_delOut_41;  // sfix34_En27
  reg signed [33:0] Delay1_delOut_42;  // sfix34_En27
  wire signed [33:0] Delay1_ectrl_16;  // sfix34_En27
  reg signed [33:0] Delay1_ectrl_17;  // sfix34_En27
  reg signed [33:0] Delay1_lowered8_bypass_reg;  // sfix34
  wire signed [33:0] Delay1_delOut_43;  // sfix34_En27
  reg signed [33:0] Delay1_delOut_44;  // sfix34_En27
  wire signed [33:0] Delay1_delOut_45;  // sfix34_En27
  wire signed [33:0] Delay1_delOut_46;  // sfix34_En27
  reg signed [33:0] Delay1_delOut_47;  // sfix34_En27
  wire signed [33:0] Delay1_ectrl_18;  // sfix34_En27
  reg signed [33:0] Delay1_ectrl_19;  // sfix34_En27
  reg signed [33:0] Delay1_lowered9_bypass_reg;  // sfix34
  wire signed [33:0] Delay1_delOut_48;  // sfix34_En27
  reg signed [33:0] Delay1_delOut_49;  // sfix34_En27
  wire signed [33:0] Delay1_delOut_50;  // sfix34_En27
  wire signed [33:0] Delay1_delOut_51;  // sfix34_En27
  reg signed [33:0] Delay1_delOut_52;  // sfix34_En27
  wire signed [33:0] Delay1_ectrl_20;  // sfix34_En27
  reg signed [33:0] Delay1_ectrl_21;  // sfix34_En27
  reg signed [33:0] Delay1_lowered10_bypass_reg;  // sfix34
  wire signed [33:0] Delay1_delOut_53;  // sfix34_En27
  reg signed [33:0] Delay1_delOut_54;  // sfix34_En27
  wire signed [33:0] Delay1_delOut_55;  // sfix34_En27
  wire signed [33:0] Delay1_delOut_56;  // sfix34_En27
  reg signed [33:0] Delay1_delOut_57;  // sfix34_En27
  wire signed [33:0] Delay1_ectrl_22;  // sfix34_En27
  reg signed [33:0] Delay1_ectrl_23;  // sfix34_En27
  reg signed [33:0] Delay1_lowered11_bypass_reg;  // sfix34
  wire signed [33:0] Delay1_delOut_58;  // sfix34_En27
  reg signed [33:0] Delay1_delOut_59;  // sfix34_En27
  wire signed [33:0] Delay1_delOut_60;  // sfix34_En27
  wire signed [33:0] Delay1_delOut_61;  // sfix34_En27
  reg signed [33:0] Delay1_delOut_62;  // sfix34_En27
  wire signed [33:0] Delay1_ectrl_24;  // sfix34_En27
  reg signed [33:0] Delay1_ectrl_25;  // sfix34_En27
  reg signed [33:0] Delay1_lowered12_bypass_reg;  // sfix34
  wire signed [33:0] Delay1_delOut_63;  // sfix34_En27
  reg signed [33:0] Delay1_delOut_64;  // sfix34_En27
  wire signed [33:0] Delay1_delOut_65;  // sfix34_En27
  wire signed [33:0] Delay1_delOut_66;  // sfix34_En27
  reg signed [33:0] Delay1_delOut_67;  // sfix34_En27
  wire signed [33:0] Delay1_ectrl_26;  // sfix34_En27
  reg signed [33:0] Delay1_ectrl_27;  // sfix34_En27
  reg signed [33:0] Delay1_lowered13_bypass_reg;  // sfix34
  wire signed [33:0] Delay1_delOut_68;  // sfix34_En27
  reg signed [33:0] Delay1_delOut_69;  // sfix34_En27
  wire signed [33:0] Delay1_delOut_70;  // sfix34_En27
  wire signed [33:0] Delay1_delOut_71;  // sfix34_En27
  reg signed [33:0] Delay1_delOut_72;  // sfix34_En27
  wire signed [33:0] Delay1_ectrl_28;  // sfix34_En27
  reg signed [33:0] Delay1_ectrl_29;  // sfix34_En27
  reg signed [33:0] Delay1_lowered14_bypass_reg;  // sfix34
  wire signed [33:0] Delay1_delOut_73;  // sfix34_En27
  reg signed [33:0] Delay1_delOut_74;  // sfix34_En27
  wire signed [33:0] Delay1_out1;  // sfix34_En27
  wire signed [33:0] Delay1_out1_1;  // sfix34_En27
  reg signed [33:0] Delay1_out1_2;  // sfix34_En27
  wire signed [33:0] Delay1_ectrl_30;  // sfix34_En27
  reg signed [33:0] Delay1_ectrl_31;  // sfix34_En27
  reg signed [33:0] Delay1_lowered15_bypass_reg;  // sfix34
  reg signed [31:0] rd_1_t_0_0;  // int32
  reg signed [31:0] rd_1_t_1;  // int32


  assign en_1 = en;

  always @(posedge clk or posedge reset)
    begin : rd_115_process
      if (reset == 1'b1) begin
        en_2 <= 1'b0;
      end
      else begin
        if (enb) begin
          en_2 <= en_1;
        end
      end
    end

  assign en_3 = en;

  always @(posedge clk or posedge reset)
    begin : rd_114_process
      if (reset == 1'b1) begin
        en_4 <= 1'b0;
      end
      else begin
        if (enb) begin
          en_4 <= en_3;
        end
      end
    end

  assign en_5 = en;

  always @(posedge clk or posedge reset)
    begin : rd_113_process
      if (reset == 1'b1) begin
        en_6 <= 1'b0;
      end
      else begin
        if (enb) begin
          en_6 <= en_5;
        end
      end
    end

  assign en_7 = en;

  always @(posedge clk or posedge reset)
    begin : rd_112_process
      if (reset == 1'b1) begin
        en_8 <= 1'b0;
      end
      else begin
        if (enb) begin
          en_8 <= en_7;
        end
      end
    end

  assign en_9 = en;

  always @(posedge clk or posedge reset)
    begin : rd_111_process
      if (reset == 1'b1) begin
        en_10 <= 1'b0;
      end
      else begin
        if (enb) begin
          en_10 <= en_9;
        end
      end
    end

  assign en_11 = en;

  always @(posedge clk or posedge reset)
    begin : rd_110_process
      if (reset == 1'b1) begin
        en_12 <= 1'b0;
      end
      else begin
        if (enb) begin
          en_12 <= en_11;
        end
      end
    end

  assign en_13 = en;

  always @(posedge clk or posedge reset)
    begin : rd_19_process
      if (reset == 1'b1) begin
        en_14 <= 1'b0;
      end
      else begin
        if (enb) begin
          en_14 <= en_13;
        end
      end
    end

  assign en_15 = en;

  always @(posedge clk or posedge reset)
    begin : rd_18_process
      if (reset == 1'b1) begin
        en_16 <= 1'b0;
      end
      else begin
        if (enb) begin
          en_16 <= en_15;
        end
      end
    end

  assign en_17 = en;

  always @(posedge clk or posedge reset)
    begin : rd_17_process
      if (reset == 1'b1) begin
        en_18 <= 1'b0;
      end
      else begin
        if (enb) begin
          en_18 <= en_17;
        end
      end
    end

  assign en_19 = en;

  always @(posedge clk or posedge reset)
    begin : rd_16_process
      if (reset == 1'b1) begin
        en_20 <= 1'b0;
      end
      else begin
        if (enb) begin
          en_20 <= en_19;
        end
      end
    end

  assign en_21 = en;

  always @(posedge clk or posedge reset)
    begin : rd_15_process
      if (reset == 1'b1) begin
        en_22 <= 1'b0;
      end
      else begin
        if (enb) begin
          en_22 <= en_21;
        end
      end
    end

  assign en_23 = en;

  always @(posedge clk or posedge reset)
    begin : rd_14_process
      if (reset == 1'b1) begin
        en_24 <= 1'b0;
      end
      else begin
        if (enb) begin
          en_24 <= en_23;
        end
      end
    end

  assign en_25 = en;

  always @(posedge clk or posedge reset)
    begin : rd_13_process
      if (reset == 1'b1) begin
        en_26 <= 1'b0;
      end
      else begin
        if (enb) begin
          en_26 <= en_25;
        end
      end
    end

  assign en_27 = en;

  always @(posedge clk or posedge reset)
    begin : rd_12_process
      if (reset == 1'b1) begin
        en_28 <= 1'b0;
      end
      else begin
        if (enb) begin
          en_28 <= en_27;
        end
      end
    end

  assign en_29 = en;

  always @(posedge clk or posedge reset)
    begin : rd_11_process
      if (reset == 1'b1) begin
        en_30 <= 1'b0;
      end
      else begin
        if (enb) begin
          en_30 <= en_29;
        end
      end
    end

  assign en_31 = en;

  always @(posedge clk or posedge reset)
    begin : rd_0_process
      if (reset == 1'b1) begin
        rd_0_reg <= {2{1'b0}};
      end
      else begin
        if (enb) begin
          rd_0_reg[0] <= en_31;
          rd_0_reg[1] <= rd_0_reg[0];
        end
      end
    end

  assign en_32 = rd_0_reg[1];

  assign Delay1_delOut_1 = Delay1_delOut;

  always @(posedge clk or posedge reset)
    begin : rd_1_process
      if (reset == 1'b1) begin
        for(rd_1_t_1 = 32'sd0; rd_1_t_1 <= 32'sd1; rd_1_t_1 = rd_1_t_1 + 32'sd1) begin
          rd_1_reg[rd_1_t_1] <= 34'sh000000000;
        end
      end
      else begin
        if (enb) begin
          for(rd_1_t_0_0 = 32'sd0; rd_1_t_0_0 <= 32'sd1; rd_1_t_0_0 = rd_1_t_0_0 + 32'sd1) begin
            rd_1_reg[rd_1_t_0_0] <= rd_1_reg_next[rd_1_t_0_0];
          end
        end
      end
    end

  assign Delay1_delOut_2 = rd_1_reg[1];
  assign rd_1_reg_next[0] = Delay1_delOut_1;
  assign rd_1_reg_next[1] = rd_1_reg[0];

  assign Delay1_ectrl = (en_32 == 1'b0 ? Delay1_delOut_2 :
              dataIn);

  always @(posedge clk or posedge reset)
    begin : crp_out_delay_process
      if (reset == 1'b1) begin
        Delay1_ectrl_1 <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          Delay1_ectrl_1 <= Delay1_ectrl;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay1_lowered_bypass_process
      if (reset == 1'b1) begin
        Delay1_lowered_bypass_reg <= 34'sh000000000;
      end
      else begin
        if (enb_1_8_1) begin
          Delay1_lowered_bypass_reg <= Delay1_ectrl_1;
        end
      end
    end

  assign Delay1_delOut = (enb_1_8_1 == 1'b1 ? Delay1_ectrl_1 :
              Delay1_lowered_bypass_reg);

  assign Delay1_delOut_3 = Delay1_delOut;

  always @(posedge clk or posedge reset)
    begin : rd_01_process
      if (reset == 1'b1) begin
        Delay1_delOut_4 <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          Delay1_delOut_4 <= Delay1_delOut_3;
        end
      end
    end

  assign Delay1_delOut_6 = Delay1_delOut_5;

  always @(posedge clk or posedge reset)
    begin : rd_2_process
      if (reset == 1'b1) begin
        Delay1_delOut_7 <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          Delay1_delOut_7 <= Delay1_delOut_6;
        end
      end
    end

  assign Delay1_ectrl_2 = (en_30 == 1'b0 ? Delay1_delOut_7 :
              Delay1_delOut_4);

  always @(posedge clk or posedge reset)
    begin : crp_out_delay1_process
      if (reset == 1'b1) begin
        Delay1_ectrl_3 <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          Delay1_ectrl_3 <= Delay1_ectrl_2;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay1_lowered1_bypass_process
      if (reset == 1'b1) begin
        Delay1_lowered1_bypass_reg <= 34'sh000000000;
      end
      else begin
        if (enb_1_8_1) begin
          Delay1_lowered1_bypass_reg <= Delay1_ectrl_3;
        end
      end
    end

  assign Delay1_delOut_5 = (enb_1_8_1 == 1'b1 ? Delay1_ectrl_3 :
              Delay1_lowered1_bypass_reg);

  assign Delay1_delOut_8 = Delay1_delOut_5;

  always @(posedge clk or posedge reset)
    begin : rd_02_process
      if (reset == 1'b1) begin
        Delay1_delOut_9 <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          Delay1_delOut_9 <= Delay1_delOut_8;
        end
      end
    end

  assign Delay1_delOut_11 = Delay1_delOut_10;

  always @(posedge clk or posedge reset)
    begin : rd_21_process
      if (reset == 1'b1) begin
        Delay1_delOut_12 <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          Delay1_delOut_12 <= Delay1_delOut_11;
        end
      end
    end

  assign Delay1_ectrl_4 = (en_28 == 1'b0 ? Delay1_delOut_12 :
              Delay1_delOut_9);

  always @(posedge clk or posedge reset)
    begin : crp_out_delay2_process
      if (reset == 1'b1) begin
        Delay1_ectrl_5 <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          Delay1_ectrl_5 <= Delay1_ectrl_4;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay1_lowered2_bypass_process
      if (reset == 1'b1) begin
        Delay1_lowered2_bypass_reg <= 34'sh000000000;
      end
      else begin
        if (enb_1_8_1) begin
          Delay1_lowered2_bypass_reg <= Delay1_ectrl_5;
        end
      end
    end

  assign Delay1_delOut_10 = (enb_1_8_1 == 1'b1 ? Delay1_ectrl_5 :
              Delay1_lowered2_bypass_reg);

  assign Delay1_delOut_13 = Delay1_delOut_10;

  always @(posedge clk or posedge reset)
    begin : rd_03_process
      if (reset == 1'b1) begin
        Delay1_delOut_14 <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          Delay1_delOut_14 <= Delay1_delOut_13;
        end
      end
    end

  assign Delay1_delOut_16 = Delay1_delOut_15;

  always @(posedge clk or posedge reset)
    begin : rd_22_process
      if (reset == 1'b1) begin
        Delay1_delOut_17 <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          Delay1_delOut_17 <= Delay1_delOut_16;
        end
      end
    end

  assign Delay1_ectrl_6 = (en_26 == 1'b0 ? Delay1_delOut_17 :
              Delay1_delOut_14);

  always @(posedge clk or posedge reset)
    begin : crp_out_delay3_process
      if (reset == 1'b1) begin
        Delay1_ectrl_7 <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          Delay1_ectrl_7 <= Delay1_ectrl_6;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay1_lowered3_bypass_process
      if (reset == 1'b1) begin
        Delay1_lowered3_bypass_reg <= 34'sh000000000;
      end
      else begin
        if (enb_1_8_1) begin
          Delay1_lowered3_bypass_reg <= Delay1_ectrl_7;
        end
      end
    end

  assign Delay1_delOut_15 = (enb_1_8_1 == 1'b1 ? Delay1_ectrl_7 :
              Delay1_lowered3_bypass_reg);

  assign Delay1_delOut_18 = Delay1_delOut_15;

  always @(posedge clk or posedge reset)
    begin : rd_04_process
      if (reset == 1'b1) begin
        Delay1_delOut_19 <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          Delay1_delOut_19 <= Delay1_delOut_18;
        end
      end
    end

  assign Delay1_delOut_21 = Delay1_delOut_20;

  always @(posedge clk or posedge reset)
    begin : rd_23_process
      if (reset == 1'b1) begin
        Delay1_delOut_22 <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          Delay1_delOut_22 <= Delay1_delOut_21;
        end
      end
    end

  assign Delay1_ectrl_8 = (en_24 == 1'b0 ? Delay1_delOut_22 :
              Delay1_delOut_19);

  always @(posedge clk or posedge reset)
    begin : crp_out_delay4_process
      if (reset == 1'b1) begin
        Delay1_ectrl_9 <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          Delay1_ectrl_9 <= Delay1_ectrl_8;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay1_lowered4_bypass_process
      if (reset == 1'b1) begin
        Delay1_lowered4_bypass_reg <= 34'sh000000000;
      end
      else begin
        if (enb_1_8_1) begin
          Delay1_lowered4_bypass_reg <= Delay1_ectrl_9;
        end
      end
    end

  assign Delay1_delOut_20 = (enb_1_8_1 == 1'b1 ? Delay1_ectrl_9 :
              Delay1_lowered4_bypass_reg);

  assign Delay1_delOut_23 = Delay1_delOut_20;

  always @(posedge clk or posedge reset)
    begin : rd_05_process
      if (reset == 1'b1) begin
        Delay1_delOut_24 <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          Delay1_delOut_24 <= Delay1_delOut_23;
        end
      end
    end

  assign Delay1_delOut_26 = Delay1_delOut_25;

  always @(posedge clk or posedge reset)
    begin : rd_24_process
      if (reset == 1'b1) begin
        Delay1_delOut_27 <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          Delay1_delOut_27 <= Delay1_delOut_26;
        end
      end
    end

  assign Delay1_ectrl_10 = (en_22 == 1'b0 ? Delay1_delOut_27 :
              Delay1_delOut_24);

  always @(posedge clk or posedge reset)
    begin : crp_out_delay5_process
      if (reset == 1'b1) begin
        Delay1_ectrl_11 <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          Delay1_ectrl_11 <= Delay1_ectrl_10;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay1_lowered5_bypass_process
      if (reset == 1'b1) begin
        Delay1_lowered5_bypass_reg <= 34'sh000000000;
      end
      else begin
        if (enb_1_8_1) begin
          Delay1_lowered5_bypass_reg <= Delay1_ectrl_11;
        end
      end
    end

  assign Delay1_delOut_25 = (enb_1_8_1 == 1'b1 ? Delay1_ectrl_11 :
              Delay1_lowered5_bypass_reg);

  assign Delay1_delOut_28 = Delay1_delOut_25;

  always @(posedge clk or posedge reset)
    begin : rd_06_process
      if (reset == 1'b1) begin
        Delay1_delOut_29 <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          Delay1_delOut_29 <= Delay1_delOut_28;
        end
      end
    end

  assign Delay1_delOut_31 = Delay1_delOut_30;

  always @(posedge clk or posedge reset)
    begin : rd_25_process
      if (reset == 1'b1) begin
        Delay1_delOut_32 <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          Delay1_delOut_32 <= Delay1_delOut_31;
        end
      end
    end

  assign Delay1_ectrl_12 = (en_20 == 1'b0 ? Delay1_delOut_32 :
              Delay1_delOut_29);

  always @(posedge clk or posedge reset)
    begin : crp_out_delay6_process
      if (reset == 1'b1) begin
        Delay1_ectrl_13 <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          Delay1_ectrl_13 <= Delay1_ectrl_12;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay1_lowered6_bypass_process
      if (reset == 1'b1) begin
        Delay1_lowered6_bypass_reg <= 34'sh000000000;
      end
      else begin
        if (enb_1_8_1) begin
          Delay1_lowered6_bypass_reg <= Delay1_ectrl_13;
        end
      end
    end

  assign Delay1_delOut_30 = (enb_1_8_1 == 1'b1 ? Delay1_ectrl_13 :
              Delay1_lowered6_bypass_reg);

  assign Delay1_delOut_33 = Delay1_delOut_30;

  always @(posedge clk or posedge reset)
    begin : rd_07_process
      if (reset == 1'b1) begin
        Delay1_delOut_34 <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          Delay1_delOut_34 <= Delay1_delOut_33;
        end
      end
    end

  assign Delay1_delOut_36 = Delay1_delOut_35;

  always @(posedge clk or posedge reset)
    begin : rd_26_process
      if (reset == 1'b1) begin
        Delay1_delOut_37 <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          Delay1_delOut_37 <= Delay1_delOut_36;
        end
      end
    end

  assign Delay1_ectrl_14 = (en_18 == 1'b0 ? Delay1_delOut_37 :
              Delay1_delOut_34);

  always @(posedge clk or posedge reset)
    begin : crp_out_delay7_process
      if (reset == 1'b1) begin
        Delay1_ectrl_15 <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          Delay1_ectrl_15 <= Delay1_ectrl_14;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay1_lowered7_bypass_process
      if (reset == 1'b1) begin
        Delay1_lowered7_bypass_reg <= 34'sh000000000;
      end
      else begin
        if (enb_1_8_1) begin
          Delay1_lowered7_bypass_reg <= Delay1_ectrl_15;
        end
      end
    end

  assign Delay1_delOut_35 = (enb_1_8_1 == 1'b1 ? Delay1_ectrl_15 :
              Delay1_lowered7_bypass_reg);

  assign Delay1_delOut_38 = Delay1_delOut_35;

  always @(posedge clk or posedge reset)
    begin : rd_08_process
      if (reset == 1'b1) begin
        Delay1_delOut_39 <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          Delay1_delOut_39 <= Delay1_delOut_38;
        end
      end
    end

  assign Delay1_delOut_41 = Delay1_delOut_40;

  always @(posedge clk or posedge reset)
    begin : rd_27_process
      if (reset == 1'b1) begin
        Delay1_delOut_42 <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          Delay1_delOut_42 <= Delay1_delOut_41;
        end
      end
    end

  assign Delay1_ectrl_16 = (en_16 == 1'b0 ? Delay1_delOut_42 :
              Delay1_delOut_39);

  always @(posedge clk or posedge reset)
    begin : crp_out_delay8_process
      if (reset == 1'b1) begin
        Delay1_ectrl_17 <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          Delay1_ectrl_17 <= Delay1_ectrl_16;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay1_lowered8_bypass_process
      if (reset == 1'b1) begin
        Delay1_lowered8_bypass_reg <= 34'sh000000000;
      end
      else begin
        if (enb_1_8_1) begin
          Delay1_lowered8_bypass_reg <= Delay1_ectrl_17;
        end
      end
    end

  assign Delay1_delOut_40 = (enb_1_8_1 == 1'b1 ? Delay1_ectrl_17 :
              Delay1_lowered8_bypass_reg);

  assign Delay1_delOut_43 = Delay1_delOut_40;

  always @(posedge clk or posedge reset)
    begin : rd_09_process
      if (reset == 1'b1) begin
        Delay1_delOut_44 <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          Delay1_delOut_44 <= Delay1_delOut_43;
        end
      end
    end

  assign Delay1_delOut_46 = Delay1_delOut_45;

  always @(posedge clk or posedge reset)
    begin : rd_28_process
      if (reset == 1'b1) begin
        Delay1_delOut_47 <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          Delay1_delOut_47 <= Delay1_delOut_46;
        end
      end
    end

  assign Delay1_ectrl_18 = (en_14 == 1'b0 ? Delay1_delOut_47 :
              Delay1_delOut_44);

  always @(posedge clk or posedge reset)
    begin : crp_out_delay9_process
      if (reset == 1'b1) begin
        Delay1_ectrl_19 <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          Delay1_ectrl_19 <= Delay1_ectrl_18;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay1_lowered9_bypass_process
      if (reset == 1'b1) begin
        Delay1_lowered9_bypass_reg <= 34'sh000000000;
      end
      else begin
        if (enb_1_8_1) begin
          Delay1_lowered9_bypass_reg <= Delay1_ectrl_19;
        end
      end
    end

  assign Delay1_delOut_45 = (enb_1_8_1 == 1'b1 ? Delay1_ectrl_19 :
              Delay1_lowered9_bypass_reg);

  assign Delay1_delOut_48 = Delay1_delOut_45;

  always @(posedge clk or posedge reset)
    begin : rd_010_process
      if (reset == 1'b1) begin
        Delay1_delOut_49 <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          Delay1_delOut_49 <= Delay1_delOut_48;
        end
      end
    end

  assign Delay1_delOut_51 = Delay1_delOut_50;

  always @(posedge clk or posedge reset)
    begin : rd_29_process
      if (reset == 1'b1) begin
        Delay1_delOut_52 <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          Delay1_delOut_52 <= Delay1_delOut_51;
        end
      end
    end

  assign Delay1_ectrl_20 = (en_12 == 1'b0 ? Delay1_delOut_52 :
              Delay1_delOut_49);

  always @(posedge clk or posedge reset)
    begin : crp_out_delay10_process
      if (reset == 1'b1) begin
        Delay1_ectrl_21 <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          Delay1_ectrl_21 <= Delay1_ectrl_20;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay1_lowered10_bypass_process
      if (reset == 1'b1) begin
        Delay1_lowered10_bypass_reg <= 34'sh000000000;
      end
      else begin
        if (enb_1_8_1) begin
          Delay1_lowered10_bypass_reg <= Delay1_ectrl_21;
        end
      end
    end

  assign Delay1_delOut_50 = (enb_1_8_1 == 1'b1 ? Delay1_ectrl_21 :
              Delay1_lowered10_bypass_reg);

  assign Delay1_delOut_53 = Delay1_delOut_50;

  always @(posedge clk or posedge reset)
    begin : rd_011_process
      if (reset == 1'b1) begin
        Delay1_delOut_54 <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          Delay1_delOut_54 <= Delay1_delOut_53;
        end
      end
    end

  assign Delay1_delOut_56 = Delay1_delOut_55;

  always @(posedge clk or posedge reset)
    begin : rd_210_process
      if (reset == 1'b1) begin
        Delay1_delOut_57 <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          Delay1_delOut_57 <= Delay1_delOut_56;
        end
      end
    end

  assign Delay1_ectrl_22 = (en_10 == 1'b0 ? Delay1_delOut_57 :
              Delay1_delOut_54);

  always @(posedge clk or posedge reset)
    begin : crp_out_delay11_process
      if (reset == 1'b1) begin
        Delay1_ectrl_23 <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          Delay1_ectrl_23 <= Delay1_ectrl_22;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay1_lowered11_bypass_process
      if (reset == 1'b1) begin
        Delay1_lowered11_bypass_reg <= 34'sh000000000;
      end
      else begin
        if (enb_1_8_1) begin
          Delay1_lowered11_bypass_reg <= Delay1_ectrl_23;
        end
      end
    end

  assign Delay1_delOut_55 = (enb_1_8_1 == 1'b1 ? Delay1_ectrl_23 :
              Delay1_lowered11_bypass_reg);

  assign Delay1_delOut_58 = Delay1_delOut_55;

  always @(posedge clk or posedge reset)
    begin : rd_012_process
      if (reset == 1'b1) begin
        Delay1_delOut_59 <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          Delay1_delOut_59 <= Delay1_delOut_58;
        end
      end
    end

  assign Delay1_delOut_61 = Delay1_delOut_60;

  always @(posedge clk or posedge reset)
    begin : rd_211_process
      if (reset == 1'b1) begin
        Delay1_delOut_62 <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          Delay1_delOut_62 <= Delay1_delOut_61;
        end
      end
    end

  assign Delay1_ectrl_24 = (en_8 == 1'b0 ? Delay1_delOut_62 :
              Delay1_delOut_59);

  always @(posedge clk or posedge reset)
    begin : crp_out_delay12_process
      if (reset == 1'b1) begin
        Delay1_ectrl_25 <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          Delay1_ectrl_25 <= Delay1_ectrl_24;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay1_lowered12_bypass_process
      if (reset == 1'b1) begin
        Delay1_lowered12_bypass_reg <= 34'sh000000000;
      end
      else begin
        if (enb_1_8_1) begin
          Delay1_lowered12_bypass_reg <= Delay1_ectrl_25;
        end
      end
    end

  assign Delay1_delOut_60 = (enb_1_8_1 == 1'b1 ? Delay1_ectrl_25 :
              Delay1_lowered12_bypass_reg);

  assign Delay1_delOut_63 = Delay1_delOut_60;

  always @(posedge clk or posedge reset)
    begin : rd_013_process
      if (reset == 1'b1) begin
        Delay1_delOut_64 <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          Delay1_delOut_64 <= Delay1_delOut_63;
        end
      end
    end

  assign Delay1_delOut_66 = Delay1_delOut_65;

  always @(posedge clk or posedge reset)
    begin : rd_212_process
      if (reset == 1'b1) begin
        Delay1_delOut_67 <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          Delay1_delOut_67 <= Delay1_delOut_66;
        end
      end
    end

  assign Delay1_ectrl_26 = (en_6 == 1'b0 ? Delay1_delOut_67 :
              Delay1_delOut_64);

  always @(posedge clk or posedge reset)
    begin : crp_out_delay13_process
      if (reset == 1'b1) begin
        Delay1_ectrl_27 <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          Delay1_ectrl_27 <= Delay1_ectrl_26;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay1_lowered13_bypass_process
      if (reset == 1'b1) begin
        Delay1_lowered13_bypass_reg <= 34'sh000000000;
      end
      else begin
        if (enb_1_8_1) begin
          Delay1_lowered13_bypass_reg <= Delay1_ectrl_27;
        end
      end
    end

  assign Delay1_delOut_65 = (enb_1_8_1 == 1'b1 ? Delay1_ectrl_27 :
              Delay1_lowered13_bypass_reg);

  assign Delay1_delOut_68 = Delay1_delOut_65;

  always @(posedge clk or posedge reset)
    begin : rd_014_process
      if (reset == 1'b1) begin
        Delay1_delOut_69 <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          Delay1_delOut_69 <= Delay1_delOut_68;
        end
      end
    end

  assign Delay1_delOut_71 = Delay1_delOut_70;

  always @(posedge clk or posedge reset)
    begin : rd_213_process
      if (reset == 1'b1) begin
        Delay1_delOut_72 <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          Delay1_delOut_72 <= Delay1_delOut_71;
        end
      end
    end

  assign Delay1_ectrl_28 = (en_4 == 1'b0 ? Delay1_delOut_72 :
              Delay1_delOut_69);

  always @(posedge clk or posedge reset)
    begin : crp_out_delay14_process
      if (reset == 1'b1) begin
        Delay1_ectrl_29 <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          Delay1_ectrl_29 <= Delay1_ectrl_28;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay1_lowered14_bypass_process
      if (reset == 1'b1) begin
        Delay1_lowered14_bypass_reg <= 34'sh000000000;
      end
      else begin
        if (enb_1_8_1) begin
          Delay1_lowered14_bypass_reg <= Delay1_ectrl_29;
        end
      end
    end

  assign Delay1_delOut_70 = (enb_1_8_1 == 1'b1 ? Delay1_ectrl_29 :
              Delay1_lowered14_bypass_reg);

  assign Delay1_delOut_73 = Delay1_delOut_70;

  always @(posedge clk or posedge reset)
    begin : rd_015_process
      if (reset == 1'b1) begin
        Delay1_delOut_74 <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          Delay1_delOut_74 <= Delay1_delOut_73;
        end
      end
    end

  assign Delay1_out1_1 = Delay1_out1;

  always @(posedge clk or posedge reset)
    begin : rd_214_process
      if (reset == 1'b1) begin
        Delay1_out1_2 <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          Delay1_out1_2 <= Delay1_out1_1;
        end
      end
    end

  assign Delay1_ectrl_30 = (en_2 == 1'b0 ? Delay1_out1_2 :
              Delay1_delOut_74);

  always @(posedge clk or posedge reset)
    begin : crp_out_delay15_process
      if (reset == 1'b1) begin
        Delay1_ectrl_31 <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          Delay1_ectrl_31 <= Delay1_ectrl_30;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay1_lowered15_bypass_process
      if (reset == 1'b1) begin
        Delay1_lowered15_bypass_reg <= 34'sh000000000;
      end
      else begin
        if (enb_1_8_1) begin
          Delay1_lowered15_bypass_reg <= Delay1_ectrl_31;
        end
      end
    end

  assign Delay1_out1 = (enb_1_8_1 == 1'b1 ? Delay1_ectrl_31 :
              Delay1_lowered15_bypass_reg);

  assign dataOut = Delay1_out1;

endmodule  // Synchronous_Enabled_16_Sample_Delay

