set src_dir [pwd]
set prj_dir "vivado_prj"
file mkdir ../$prj_dir
cd ../$prj_dir
create_project WLANTimeAndFrequencySynchronization.xpr
set_property PART xc7z020-clg400-1 [current_project]
add_file $src_dir/WLANTimeAndFrequencySynchronization_tc.v
add_file $src_dir/DTConverter.v
add_file $src_dir/SinLookUpTableGen.v
add_file $src_dir/CosLookUpTableGen.v
add_file $src_dir/WaveformGen.v
add_file $src_dir/NCO.v
add_file $src_dir/Coarse_CFO_Correction.v
add_file $src_dir/Averager.v
add_file $src_dir/SimpleDualPortRAM_generic.v
add_file $src_dir/Correlator.v
add_file $src_dir/Sample_FreqOff.v
add_file $src_dir/CordicKernelMag.v
add_file $src_dir/CordicKernelMag_block.v
add_file $src_dir/CordicKernelMag_block1.v
add_file $src_dir/CordicKernelMag_block2.v
add_file $src_dir/Quadrant_Correction.v
add_file $src_dir/CordicKernelMag_block3.v
add_file $src_dir/CordicKernelMag_block4.v
add_file $src_dir/CordicKernelMag_block5.v
add_file $src_dir/CordicKernelMag_block6.v
add_file $src_dir/CordicKernelMag_block7.v
add_file $src_dir/CordicKernelMag_block8.v
add_file $src_dir/CordicKernelMag_block9.v
add_file $src_dir/CordicKernelMag_block10.v
add_file $src_dir/CordicKernelMag_block11.v
add_file $src_dir/CordicKernelMag_block12.v
add_file $src_dir/CordicKernelMag_block13.v
add_file $src_dir/CordicKernelMag_block14.v
add_file $src_dir/CordicKernelMag_block15.v
add_file $src_dir/CordicKernelMag_block16.v
add_file $src_dir/CordicKernelMag_block17.v
add_file $src_dir/CordicKernelMag_block18.v
add_file $src_dir/CordicKernelMag_block19.v
add_file $src_dir/CordicKernelMag_block20.v
add_file $src_dir/CordicKernelMag_block21.v
add_file $src_dir/CordicKernelMag_block22.v
add_file $src_dir/CordicKernelMag_block23.v
add_file $src_dir/CordicKernelMag_block24.v
add_file $src_dir/CordicKernelMag_block25.v
add_file $src_dir/CordicKernelMag_block26.v
add_file $src_dir/CordicKernelMag_block27.v
add_file $src_dir/CordicKernelMag_block28.v
add_file $src_dir/Quadrant_Mapper.v
add_file $src_dir/Coarse_CFO_Estimation.v
add_file $src_dir/Coarse_CFO_Estimation_and_Correction.v
add_file $src_dir/MagnitudeSquared.v
add_file $src_dir/Synchronous_Enabled_128_Sample_Delay.v
add_file $src_dir/MovingSum.v
add_file $src_dir/DTadjust.v
add_file $src_dir/delayedCorrelation.v
add_file $src_dir/Correlator_block.v
add_file $src_dir/DTadjust_block.v
add_file $src_dir/MagnitudeSquared_block.v
add_file $src_dir/MagnitudeSquared1.v
add_file $src_dir/Synchronous_Enabled_16_Sample_Delay.v
add_file $src_dir/MovingSum_block.v
add_file $src_dir/magnitudeSquared_block1.v
add_file $src_dir/StreamSyncronizer.v
add_file $src_dir/streamSynchronizer.v
add_file $src_dir/Energy_Calculator.v
add_file $src_dir/considerFirstPeak.v
add_file $src_dir/MATLAB_Function1.v
add_file $src_dir/searchStartOfFrame.v
add_file $src_dir/Peak_Detector.v
add_file $src_dir/StreamSyncronizer_block.v
add_file $src_dir/Stream_Synchronizer.v
add_file $src_dir/Coarse_Time_Sync.v
add_file $src_dir/SinLookUpTableGen_block.v
add_file $src_dir/CosLookUpTableGen_block.v
add_file $src_dir/WaveformGen_block.v
add_file $src_dir/NCO_block.v
add_file $src_dir/Fine_CFO_Correction.v
add_file $src_dir/Averager_block.v
add_file $src_dir/Correlator_block1.v
add_file $src_dir/Quadrant_Mapper_block.v
add_file $src_dir/CordicKernelMag_block29.v
add_file $src_dir/CordicKernelMag_block30.v
add_file $src_dir/CordicKernelMag_block31.v
add_file $src_dir/CordicKernelMag_block32.v
add_file $src_dir/CordicKernelMag_block33.v
add_file $src_dir/CordicKernelMag_block34.v
add_file $src_dir/CordicKernelMag_block35.v
add_file $src_dir/CordicKernelMag_block36.v
add_file $src_dir/CordicKernelMag_block37.v
add_file $src_dir/CordicKernelMag_block38.v
add_file $src_dir/CordicKernelMag_block39.v
add_file $src_dir/CordicKernelMag_block40.v
add_file $src_dir/CordicKernelMag_block41.v
add_file $src_dir/CordicKernelMag_block42.v
add_file $src_dir/CordicKernelMag_block43.v
add_file $src_dir/CordicKernelMag_block44.v
add_file $src_dir/CordicKernelMag_block45.v
add_file $src_dir/CordicKernelMag_block46.v
add_file $src_dir/CordicKernelMag_block47.v
add_file $src_dir/CordicKernelMag_block48.v
add_file $src_dir/CordicKernelMag_block49.v
add_file $src_dir/CordicKernelMag_block50.v
add_file $src_dir/CordicKernelMag_block51.v
add_file $src_dir/CordicKernelMag_block52.v
add_file $src_dir/CordicKernelMag_block53.v
add_file $src_dir/CordicKernelMag_block54.v
add_file $src_dir/CordicKernelMag_block55.v
add_file $src_dir/CordicKernelMag_block56.v
add_file $src_dir/Quadrant_Correction_block.v
add_file $src_dir/CordicKernelMag_block57.v
add_file $src_dir/CordicKernelMag_block58.v
add_file $src_dir/Fine_CFO_Estimation.v
add_file $src_dir/Fine_CFO_Estimation_and_Correction.v
add_file $src_dir/MagnitudeSquared_block2.v
add_file $src_dir/FirRdyLogic.v
add_file $src_dir/SimpleDualPortRAM_generic_block.v
add_file $src_dir/Addressable_Delay_Line.v
add_file $src_dir/FilterTapSystolic.v
add_file $src_dir/Addressable_Delay_Line_block.v
add_file $src_dir/FilterTapSystolic_block.v
add_file $src_dir/Addressable_Delay_Line_block1.v
add_file $src_dir/FilterTapSystolic_block1.v
add_file $src_dir/C1.v
add_file $src_dir/corrFilter.v
add_file $src_dir/Correlator_block2.v
add_file $src_dir/extractLTFs.v
add_file $src_dir/maxPeakSearcher.v
add_file $src_dir/maxPeakSearcher_block.v
add_file $src_dir/peakDetector.v
add_file $src_dir/Peak_Searcher.v
add_file $src_dir/Fine_Time_Sync.v
add_file $src_dir/FilterCoef.v
add_file $src_dir/FilterTapSystolicPreAddWvlIn.v
add_file $src_dir/subFilter.v
add_file $src_dir/Filter.v
add_file $src_dir/Discrete_FIR_Filter.v
add_file $src_dir/DTConverter_block.v
add_file $src_dir/Rx_Filter.v
add_file $src_dir/WLANTimeAndFrequencySynchronization.v
launch_runs synth_1 -force
wait_on_run synth_1
