// ==============================================================
// Generated by Vitis HLS v2024.2.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="module2_coarse_cfo_module2_coarse_cfo,hls_ip_2024_2_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.510000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=7,HLS_SYN_DSP=0,HLS_SYN_FF=2289,HLS_SYN_LUT=3776,HLS_VERSION=2024_2_2}" *)

module module2_coarse_cfo (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        data_in_dout,
        data_in_empty_n,
        data_in_read,
        startOffset_in_dout,
        startOffset_in_empty_n,
        startOffset_in_read,
        search_buffer_out_din,
        search_buffer_out_full_n,
        search_buffer_out_write,
        coarseFreqOff_out_din,
        coarseFreqOff_out_full_n,
        coarseFreqOff_out_write,
        searchBufferLen_out_din,
        searchBufferLen_out_full_n,
        searchBufferLen_out_write,
        passthrough_out_din,
        passthrough_out_full_n,
        passthrough_out_write,
        startOffset_fwd_out_din,
        startOffset_fwd_out_full_n,
        startOffset_fwd_out_write,
        num_samples
);

parameter    ap_ST_fsm_state1 = 74'd1;
parameter    ap_ST_fsm_state2 = 74'd2;
parameter    ap_ST_fsm_state3 = 74'd4;
parameter    ap_ST_fsm_state4 = 74'd8;
parameter    ap_ST_fsm_state5 = 74'd16;
parameter    ap_ST_fsm_state6 = 74'd32;
parameter    ap_ST_fsm_state7 = 74'd64;
parameter    ap_ST_fsm_state8 = 74'd128;
parameter    ap_ST_fsm_state9 = 74'd256;
parameter    ap_ST_fsm_state10 = 74'd512;
parameter    ap_ST_fsm_state11 = 74'd1024;
parameter    ap_ST_fsm_state12 = 74'd2048;
parameter    ap_ST_fsm_state13 = 74'd4096;
parameter    ap_ST_fsm_state14 = 74'd8192;
parameter    ap_ST_fsm_state15 = 74'd16384;
parameter    ap_ST_fsm_state16 = 74'd32768;
parameter    ap_ST_fsm_state17 = 74'd65536;
parameter    ap_ST_fsm_state18 = 74'd131072;
parameter    ap_ST_fsm_state19 = 74'd262144;
parameter    ap_ST_fsm_state20 = 74'd524288;
parameter    ap_ST_fsm_state21 = 74'd1048576;
parameter    ap_ST_fsm_state22 = 74'd2097152;
parameter    ap_ST_fsm_state23 = 74'd4194304;
parameter    ap_ST_fsm_state24 = 74'd8388608;
parameter    ap_ST_fsm_state25 = 74'd16777216;
parameter    ap_ST_fsm_state26 = 74'd33554432;
parameter    ap_ST_fsm_state27 = 74'd67108864;
parameter    ap_ST_fsm_state28 = 74'd134217728;
parameter    ap_ST_fsm_state29 = 74'd268435456;
parameter    ap_ST_fsm_state30 = 74'd536870912;
parameter    ap_ST_fsm_state31 = 74'd1073741824;
parameter    ap_ST_fsm_state32 = 74'd2147483648;
parameter    ap_ST_fsm_state33 = 74'd4294967296;
parameter    ap_ST_fsm_state34 = 74'd8589934592;
parameter    ap_ST_fsm_state35 = 74'd17179869184;
parameter    ap_ST_fsm_state36 = 74'd34359738368;
parameter    ap_ST_fsm_state37 = 74'd68719476736;
parameter    ap_ST_fsm_state38 = 74'd137438953472;
parameter    ap_ST_fsm_state39 = 74'd274877906944;
parameter    ap_ST_fsm_state40 = 74'd549755813888;
parameter    ap_ST_fsm_state41 = 74'd1099511627776;
parameter    ap_ST_fsm_state42 = 74'd2199023255552;
parameter    ap_ST_fsm_state43 = 74'd4398046511104;
parameter    ap_ST_fsm_state44 = 74'd8796093022208;
parameter    ap_ST_fsm_state45 = 74'd17592186044416;
parameter    ap_ST_fsm_state46 = 74'd35184372088832;
parameter    ap_ST_fsm_state47 = 74'd70368744177664;
parameter    ap_ST_fsm_state48 = 74'd140737488355328;
parameter    ap_ST_fsm_state49 = 74'd281474976710656;
parameter    ap_ST_fsm_state50 = 74'd562949953421312;
parameter    ap_ST_fsm_state51 = 74'd1125899906842624;
parameter    ap_ST_fsm_state52 = 74'd2251799813685248;
parameter    ap_ST_fsm_state53 = 74'd4503599627370496;
parameter    ap_ST_fsm_state54 = 74'd9007199254740992;
parameter    ap_ST_fsm_state55 = 74'd18014398509481984;
parameter    ap_ST_fsm_state56 = 74'd36028797018963968;
parameter    ap_ST_fsm_state57 = 74'd72057594037927936;
parameter    ap_ST_fsm_state58 = 74'd144115188075855872;
parameter    ap_ST_fsm_state59 = 74'd288230376151711744;
parameter    ap_ST_fsm_state60 = 74'd576460752303423488;
parameter    ap_ST_fsm_state61 = 74'd1152921504606846976;
parameter    ap_ST_fsm_state62 = 74'd2305843009213693952;
parameter    ap_ST_fsm_state63 = 74'd4611686018427387904;
parameter    ap_ST_fsm_state64 = 74'd9223372036854775808;
parameter    ap_ST_fsm_state65 = 74'd18446744073709551616;
parameter    ap_ST_fsm_state66 = 74'd36893488147419103232;
parameter    ap_ST_fsm_state67 = 74'd73786976294838206464;
parameter    ap_ST_fsm_state68 = 74'd147573952589676412928;
parameter    ap_ST_fsm_state69 = 74'd295147905179352825856;
parameter    ap_ST_fsm_state70 = 74'd590295810358705651712;
parameter    ap_ST_fsm_state71 = 74'd1180591620717411303424;
parameter    ap_ST_fsm_state72 = 74'd2361183241434822606848;
parameter    ap_ST_fsm_state73 = 74'd4722366482869645213696;
parameter    ap_ST_fsm_state74 = 74'd9444732965739290427392;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] data_in_dout;
input   data_in_empty_n;
output   data_in_read;
input  [15:0] startOffset_in_dout;
input   startOffset_in_empty_n;
output   startOffset_in_read;
output  [31:0] search_buffer_out_din;
input   search_buffer_out_full_n;
output   search_buffer_out_write;
output  [31:0] coarseFreqOff_out_din;
input   coarseFreqOff_out_full_n;
output   coarseFreqOff_out_write;
output  [15:0] searchBufferLen_out_din;
input   searchBufferLen_out_full_n;
output   searchBufferLen_out_write;
output  [31:0] passthrough_out_din;
input   passthrough_out_full_n;
output   passthrough_out_write;
output  [15:0] startOffset_fwd_out_din;
input   startOffset_fwd_out_full_n;
output   startOffset_fwd_out_write;
input  [31:0] num_samples;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg data_in_read;
reg startOffset_in_read;
reg coarseFreqOff_out_write;
reg searchBufferLen_out_write;
reg[31:0] passthrough_out_din;
reg passthrough_out_write;
reg[15:0] startOffset_fwd_out_din;
reg startOffset_fwd_out_write;

(* fsm_encoding = "none" *) reg   [73:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [10:0] early_buf_re_address0;
reg    early_buf_re_ce0;
wire   [15:0] early_buf_re_q0;
reg   [10:0] early_buf_re_address1;
reg    early_buf_re_ce1;
reg    early_buf_re_we1;
wire   [15:0] early_buf_re_q1;
reg   [10:0] early_buf_im_address0;
reg    early_buf_im_ce0;
wire   [15:0] early_buf_im_q0;
reg   [10:0] early_buf_im_address1;
reg    early_buf_im_ce1;
reg    early_buf_im_we1;
wire   [15:0] early_buf_im_q1;
wire   [7:0] atan_lut_address0;
wire   [15:0] atan_lut_q0;
wire   [7:0] atan_lut_address1;
wire   [15:0] atan_lut_q1;
reg    startOffset_in_blk_n;
wire    ap_CS_fsm_state3;
wire   [0:0] sO_rx_loc_load_load_fu_363_p1;
reg    coarseFreqOff_out_blk_n;
wire    ap_CS_fsm_state74;
reg    searchBufferLen_out_blk_n;
reg    startOffset_fwd_out_blk_n;
reg   [31:0] num_samples_read_reg_1029;
wire  signed [31:0] sext_ln111_fu_369_p1;
reg  signed [31:0] sext_ln111_reg_1047;
wire    ap_CS_fsm_state4;
wire   [10:0] trunc_ln111_fu_373_p1;
reg   [10:0] trunc_ln111_reg_1052;
wire   [31:0] add_ln113_fu_382_p2;
reg   [31:0] add_ln113_reg_1059;
wire   [31:0] useLen_fu_393_p3;
reg   [31:0] useLen_reg_1065;
wire    ap_CS_fsm_state5;
wire   [4:0] select_ln114_fu_432_p3;
reg   [4:0] select_ln114_reg_1070;
wire  signed [5:0] sext_ln115_1_fu_440_p1;
reg  signed [5:0] sext_ln115_1_reg_1075;
wire    ap_CS_fsm_state6;
wire   [10:0] add_fu_458_p2;
reg   [10:0] add_reg_1080;
wire   [10:0] add24_fu_463_p2;
reg   [10:0] add24_reg_1085;
wire   [0:0] icmp_ln119_fu_468_p2;
reg   [0:0] icmp_ln119_reg_1090;
wire   [31:0] add_ln119_fu_479_p2;
reg   [31:0] add_ln119_reg_1094;
wire   [31:0] add_ln119_1_fu_511_p2;
reg   [31:0] add_ln119_1_reg_1100;
wire    ap_CS_fsm_state7;
wire   [0:0] x_neg_fu_526_p3;
reg   [0:0] x_neg_reg_1105;
wire    ap_CS_fsm_state9;
wire   [0:0] y_neg_fu_534_p3;
reg   [0:0] y_neg_reg_1110;
wire   [31:0] ax_fu_548_p3;
reg   [31:0] ax_reg_1115;
wire   [31:0] ay_fu_562_p3;
reg   [31:0] ay_reg_1123;
wire   [0:0] swap_fu_580_p2;
reg   [0:0] swap_reg_1134;
wire    ap_CS_fsm_state10;
wire   [50:0] grp_fu_608_p2;
reg   [50:0] sdiv_ln47_reg_1149;
wire    ap_CS_fsm_state64;
reg   [31:0] scaled_reg_1155;
wire    ap_CS_fsm_state65;
wire   [12:0] lut_idx_fu_688_p3;
reg   [12:0] lut_idx_reg_1160;
wire   [31:0] frac_fu_720_p2;
reg  signed [31:0] frac_reg_1166;
wire    ap_CS_fsm_state66;
wire  signed [23:0] v0_fu_741_p3;
reg  signed [23:0] v0_reg_1181;
wire    ap_CS_fsm_state67;
wire   [24:0] sub_ln55_fu_765_p2;
reg   [24:0] sub_ln55_reg_1186;
reg   [31:0] trunc_ln5_reg_1191;
wire    ap_CS_fsm_state68;
wire   [31:0] angle_2_fu_811_p3;
reg   [31:0] angle_2_reg_1196;
wire    ap_CS_fsm_state69;
wire   [31:0] angle_6_fu_853_p3;
reg   [31:0] angle_6_reg_1202;
wire    ap_CS_fsm_state70;
reg   [5:0] tmp_7_reg_1208;
wire   [31:0] select_ln61_fu_901_p3;
wire    ap_CS_fsm_state71;
wire  signed [31:0] signed_angle_2_fu_921_p3;
reg  signed [31:0] signed_angle_2_reg_1218;
wire    ap_CS_fsm_state72;
reg   [0:0] tmp_9_reg_1224;
reg   [27:0] tmp_2_reg_1229;
reg   [31:0] coarseFreqOff_reg_1234;
wire    ap_CS_fsm_state73;
wire   [28:0] phase_inc_fu_997_p3;
reg   [28:0] phase_inc_reg_1239;
wire    grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_ap_start;
wire    grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_ap_done;
wire    grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_ap_idle;
wire    grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_ap_ready;
wire    grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_data_in_read;
wire   [31:0] grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_passthrough_out_din;
wire    grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_passthrough_out_write;
wire    grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_startOffset_in_read;
wire   [15:0] grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_startOffset_fwd_out_din;
wire    grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_startOffset_fwd_out_write;
wire   [0:0] grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_sO_rx_out;
wire    grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_sO_rx_out_ap_vld;
wire   [15:0] grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_startOffset_out;
wire    grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_startOffset_out_ap_vld;
wire   [10:0] grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_early_buf_re_address1;
wire    grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_early_buf_re_ce1;
wire    grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_early_buf_re_we1;
wire   [15:0] grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_early_buf_re_d1;
wire   [10:0] grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_early_buf_im_address1;
wire    grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_early_buf_im_ce1;
wire    grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_early_buf_im_we1;
wire   [15:0] grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_early_buf_im_d1;
wire    grp_module2_coarse_cfo_Pipeline_CFO_ESTIMATE_fu_320_ap_start;
wire    grp_module2_coarse_cfo_Pipeline_CFO_ESTIMATE_fu_320_ap_done;
wire    grp_module2_coarse_cfo_Pipeline_CFO_ESTIMATE_fu_320_ap_idle;
wire    grp_module2_coarse_cfo_Pipeline_CFO_ESTIMATE_fu_320_ap_ready;
wire   [31:0] grp_module2_coarse_cfo_Pipeline_CFO_ESTIMATE_fu_320_C_re_out;
wire    grp_module2_coarse_cfo_Pipeline_CFO_ESTIMATE_fu_320_C_re_out_ap_vld;
wire   [31:0] grp_module2_coarse_cfo_Pipeline_CFO_ESTIMATE_fu_320_C_im_out;
wire    grp_module2_coarse_cfo_Pipeline_CFO_ESTIMATE_fu_320_C_im_out_ap_vld;
wire   [10:0] grp_module2_coarse_cfo_Pipeline_CFO_ESTIMATE_fu_320_early_buf_re_address0;
wire    grp_module2_coarse_cfo_Pipeline_CFO_ESTIMATE_fu_320_early_buf_re_ce0;
wire   [10:0] grp_module2_coarse_cfo_Pipeline_CFO_ESTIMATE_fu_320_early_buf_re_address1;
wire    grp_module2_coarse_cfo_Pipeline_CFO_ESTIMATE_fu_320_early_buf_re_ce1;
wire   [10:0] grp_module2_coarse_cfo_Pipeline_CFO_ESTIMATE_fu_320_early_buf_im_address0;
wire    grp_module2_coarse_cfo_Pipeline_CFO_ESTIMATE_fu_320_early_buf_im_ce0;
wire   [10:0] grp_module2_coarse_cfo_Pipeline_CFO_ESTIMATE_fu_320_early_buf_im_address1;
wire    grp_module2_coarse_cfo_Pipeline_CFO_ESTIMATE_fu_320_early_buf_im_ce1;
wire    grp_module2_coarse_cfo_Pipeline_PHASE_D_fu_333_ap_start;
wire    grp_module2_coarse_cfo_Pipeline_PHASE_D_fu_333_ap_done;
wire    grp_module2_coarse_cfo_Pipeline_PHASE_D_fu_333_ap_idle;
wire    grp_module2_coarse_cfo_Pipeline_PHASE_D_fu_333_ap_ready;
wire    grp_module2_coarse_cfo_Pipeline_PHASE_D_fu_333_data_in_read;
wire   [31:0] grp_module2_coarse_cfo_Pipeline_PHASE_D_fu_333_passthrough_out_din;
wire    grp_module2_coarse_cfo_Pipeline_PHASE_D_fu_333_passthrough_out_write;
wire   [31:0] grp_module2_coarse_cfo_Pipeline_PHASE_D_fu_333_search_buffer_out_din;
wire    grp_module2_coarse_cfo_Pipeline_PHASE_D_fu_333_search_buffer_out_write;
wire   [10:0] grp_module2_coarse_cfo_Pipeline_PHASE_D_fu_333_early_buf_re_address0;
wire    grp_module2_coarse_cfo_Pipeline_PHASE_D_fu_333_early_buf_re_ce0;
wire   [10:0] grp_module2_coarse_cfo_Pipeline_PHASE_D_fu_333_early_buf_im_address0;
wire    grp_module2_coarse_cfo_Pipeline_PHASE_D_fu_333_early_buf_im_ce0;
reg  signed [15:0] startOffset_2_reg_260;
reg    ap_block_state3;
reg   [31:0] ap_phi_mux_y_phi_fu_273_p4;
reg   [31:0] y_reg_269;
reg   [31:0] ap_phi_mux_x_phi_fu_284_p4;
reg   [31:0] x_reg_280;
reg   [31:0] angle_10_reg_291;
wire   [0:0] icmp_ln39_fu_574_p2;
reg    grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_module2_coarse_cfo_Pipeline_CFO_ESTIMATE_fu_320_ap_start_reg;
wire    ap_CS_fsm_state8;
reg    grp_module2_coarse_cfo_Pipeline_PHASE_D_fu_333_ap_start_reg;
wire   [63:0] zext_ln53_fu_725_p1;
wire   [63:0] zext_ln54_fu_736_p1;
reg    ap_block_state74;
reg    atan_lut_ce1_local;
reg    atan_lut_ce0_local;
wire   [27:0] mul_ln137_fu_358_p1;
wire   [31:0] rxLen_local_fu_377_p2;
wire   [0:0] icmp_ln113_fu_388_p2;
wire   [3:0] trunc_ln114_fu_408_p1;
wire   [3:0] sub_ln114_fu_412_p2;
wire   [4:0] zext_ln114_fu_418_p1;
wire   [0:0] tmp_fu_400_p3;
wire   [4:0] sub_ln114_1_fu_422_p2;
wire   [4:0] zext_ln114_1_fu_428_p1;
wire   [5:0] sub_ln115_fu_443_p2;
wire  signed [31:0] sext_ln115_fu_449_p1;
wire   [31:0] corrLen_fu_453_p2;
wire   [31:0] sub_ln119_fu_474_p2;
wire   [5:0] sub_ln119_1_fu_484_p2;
wire   [0:0] empty_fu_493_p2;
wire   [31:0] p_op_fu_498_p2;
wire  signed [31:0] sext_ln119_fu_489_p1;
wire   [31:0] smax_neg_fu_503_p3;
wire   [31:0] sub_ln36_fu_542_p2;
wire   [31:0] sub_ln37_fu_556_p2;
wire   [31:0] or_ln39_fu_570_p2;
wire   [31:0] select_ln44_fu_590_p3;
wire  signed [31:0] den_fu_584_p3;
wire   [50:0] grp_fu_608_p0;
wire   [50:0] shl_ln48_fu_614_p2;
wire   [50:0] shl_ln48_1_fu_619_p2;
wire   [50:0] sub_ln48_fu_624_p2;
wire   [18:0] tmp_6_fu_658_p4;
wire   [12:0] tmp_4_fu_640_p4;
wire   [0:0] icmp_ln49_fu_668_p2;
wire   [12:0] add_ln49_fu_674_p2;
wire   [0:0] tmp_5_fu_650_p3;
wire   [12:0] select_ln49_fu_680_p3;
wire   [0:0] icmp_ln50_fu_696_p2;
wire   [12:0] lut_idx_1_fu_701_p3;
wire   [31:0] shl_ln1_fu_712_p3;
wire   [7:0] trunc_ln49_fu_708_p1;
wire   [7:0] add_ln54_fu_730_p2;
wire   [23:0] v1_fu_753_p3;
wire  signed [24:0] sext_ln54_fu_761_p1;
wire  signed [24:0] sext_ln53_1_fu_749_p1;
wire  signed [27:0] tmp_s_fu_771_p3;
wire   [53:0] mul_ln55_fu_354_p2;
wire  signed [31:0] sext_ln53_fu_797_p1;
wire   [31:0] angle_fu_800_p2;
wire   [31:0] angle_1_fu_805_p2;
wire   [47:0] shl_ln2_fu_818_p3;
wire   [47:0] sub_ln58_fu_825_p2;
wire   [31:0] angle_3_fu_831_p4;
wire   [31:0] angle_4_fu_841_p3;
wire   [31:0] angle_5_fu_847_p2;
wire   [0:0] icmp_ln60_fu_870_p2;
wire   [31:0] angle_7_fu_875_p2;
wire   [31:0] angle_8_fu_880_p3;
wire   [0:0] tmp_8_fu_887_p3;
wire   [31:0] add_ln61_fu_895_p2;
wire   [0:0] icmp_ln132_fu_909_p2;
wire   [31:0] signed_angle_1_fu_915_p2;
wire   [47:0] mul_ln137_fu_358_p2;
wire   [47:0] shl_ln3_fu_961_p3;
wire   [47:0] sub_ln138_fu_968_p2;
wire   [27:0] tmp_1_fu_974_p4;
wire   [28:0] zext_ln138_fu_984_p1;
wire   [28:0] sub_ln138_1_fu_991_p2;
wire   [28:0] zext_ln138_1_fu_988_p1;
reg    grp_fu_608_ap_start;
wire    grp_fu_608_ap_done;
reg   [73:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
wire    ap_ST_fsm_state34_blk;
wire    ap_ST_fsm_state35_blk;
wire    ap_ST_fsm_state36_blk;
wire    ap_ST_fsm_state37_blk;
wire    ap_ST_fsm_state38_blk;
wire    ap_ST_fsm_state39_blk;
wire    ap_ST_fsm_state40_blk;
wire    ap_ST_fsm_state41_blk;
wire    ap_ST_fsm_state42_blk;
wire    ap_ST_fsm_state43_blk;
wire    ap_ST_fsm_state44_blk;
wire    ap_ST_fsm_state45_blk;
wire    ap_ST_fsm_state46_blk;
wire    ap_ST_fsm_state47_blk;
wire    ap_ST_fsm_state48_blk;
wire    ap_ST_fsm_state49_blk;
wire    ap_ST_fsm_state50_blk;
wire    ap_ST_fsm_state51_blk;
wire    ap_ST_fsm_state52_blk;
wire    ap_ST_fsm_state53_blk;
wire    ap_ST_fsm_state54_blk;
wire    ap_ST_fsm_state55_blk;
wire    ap_ST_fsm_state56_blk;
wire    ap_ST_fsm_state57_blk;
wire    ap_ST_fsm_state58_blk;
wire    ap_ST_fsm_state59_blk;
wire    ap_ST_fsm_state60_blk;
wire    ap_ST_fsm_state61_blk;
wire    ap_ST_fsm_state62_blk;
wire    ap_ST_fsm_state63_blk;
wire    ap_ST_fsm_state64_blk;
wire    ap_ST_fsm_state65_blk;
wire    ap_ST_fsm_state66_blk;
wire    ap_ST_fsm_state67_blk;
wire    ap_ST_fsm_state68_blk;
wire    ap_ST_fsm_state69_blk;
wire    ap_ST_fsm_state70_blk;
wire    ap_ST_fsm_state71_blk;
wire    ap_ST_fsm_state72_blk;
wire    ap_ST_fsm_state73_blk;
reg    ap_ST_fsm_state74_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 74'd1;
#0 grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_ap_start_reg = 1'b0;
#0 grp_module2_coarse_cfo_Pipeline_CFO_ESTIMATE_fu_320_ap_start_reg = 1'b0;
#0 grp_module2_coarse_cfo_Pipeline_PHASE_D_fu_333_ap_start_reg = 1'b0;
end

module2_coarse_cfo_early_buf_re_RAM_2P_BRAM_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 2048 ),
    .AddressWidth( 11 ))
early_buf_re_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(early_buf_re_address0),
    .ce0(early_buf_re_ce0),
    .q0(early_buf_re_q0),
    .address1(early_buf_re_address1),
    .ce1(early_buf_re_ce1),
    .we1(early_buf_re_we1),
    .d1(grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_early_buf_re_d1),
    .q1(early_buf_re_q1)
);

module2_coarse_cfo_early_buf_re_RAM_2P_BRAM_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 2048 ),
    .AddressWidth( 11 ))
early_buf_im_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(early_buf_im_address0),
    .ce0(early_buf_im_ce0),
    .q0(early_buf_im_q0),
    .address1(early_buf_im_address1),
    .ce1(early_buf_im_ce1),
    .we1(early_buf_im_we1),
    .d1(grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_early_buf_im_d1),
    .q1(early_buf_im_q1)
);

module2_coarse_cfo_atan_lut_ROM_AUTO_1R #(
    .DataWidth( 16 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
atan_lut_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(atan_lut_address0),
    .ce0(atan_lut_ce0_local),
    .q0(atan_lut_q0),
    .address1(atan_lut_address1),
    .ce1(atan_lut_ce1_local),
    .q1(atan_lut_q1)
);

module2_coarse_cfo_module2_coarse_cfo_Pipeline_PHASE_A grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_ap_start),
    .ap_done(grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_ap_done),
    .ap_idle(grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_ap_idle),
    .ap_ready(grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_ap_ready),
    .data_in_dout(data_in_dout),
    .data_in_empty_n(data_in_empty_n),
    .data_in_read(grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_data_in_read),
    .passthrough_out_din(grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_passthrough_out_din),
    .passthrough_out_full_n(passthrough_out_full_n),
    .passthrough_out_write(grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_passthrough_out_write),
    .startOffset_in_dout(startOffset_in_dout),
    .startOffset_in_empty_n(startOffset_in_empty_n),
    .startOffset_in_read(grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_startOffset_in_read),
    .startOffset_fwd_out_din(grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_startOffset_fwd_out_din),
    .startOffset_fwd_out_full_n(startOffset_fwd_out_full_n),
    .startOffset_fwd_out_write(grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_startOffset_fwd_out_write),
    .sO_rx_out(grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_sO_rx_out),
    .sO_rx_out_ap_vld(grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_sO_rx_out_ap_vld),
    .startOffset_out(grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_startOffset_out),
    .startOffset_out_ap_vld(grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_startOffset_out_ap_vld),
    .early_buf_re_address1(grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_early_buf_re_address1),
    .early_buf_re_ce1(grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_early_buf_re_ce1),
    .early_buf_re_we1(grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_early_buf_re_we1),
    .early_buf_re_d1(grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_early_buf_re_d1),
    .early_buf_im_address1(grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_early_buf_im_address1),
    .early_buf_im_ce1(grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_early_buf_im_ce1),
    .early_buf_im_we1(grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_early_buf_im_we1),
    .early_buf_im_d1(grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_early_buf_im_d1)
);

module2_coarse_cfo_module2_coarse_cfo_Pipeline_CFO_ESTIMATE grp_module2_coarse_cfo_Pipeline_CFO_ESTIMATE_fu_320(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_module2_coarse_cfo_Pipeline_CFO_ESTIMATE_fu_320_ap_start),
    .ap_done(grp_module2_coarse_cfo_Pipeline_CFO_ESTIMATE_fu_320_ap_done),
    .ap_idle(grp_module2_coarse_cfo_Pipeline_CFO_ESTIMATE_fu_320_ap_idle),
    .ap_ready(grp_module2_coarse_cfo_Pipeline_CFO_ESTIMATE_fu_320_ap_ready),
    .add_ln119_1_cast(add_ln119_1_reg_1100),
    .add(add_reg_1080),
    .add24(add24_reg_1085),
    .C_re_out(grp_module2_coarse_cfo_Pipeline_CFO_ESTIMATE_fu_320_C_re_out),
    .C_re_out_ap_vld(grp_module2_coarse_cfo_Pipeline_CFO_ESTIMATE_fu_320_C_re_out_ap_vld),
    .C_im_out(grp_module2_coarse_cfo_Pipeline_CFO_ESTIMATE_fu_320_C_im_out),
    .C_im_out_ap_vld(grp_module2_coarse_cfo_Pipeline_CFO_ESTIMATE_fu_320_C_im_out_ap_vld),
    .early_buf_re_address0(grp_module2_coarse_cfo_Pipeline_CFO_ESTIMATE_fu_320_early_buf_re_address0),
    .early_buf_re_ce0(grp_module2_coarse_cfo_Pipeline_CFO_ESTIMATE_fu_320_early_buf_re_ce0),
    .early_buf_re_q0(early_buf_re_q0),
    .early_buf_re_address1(grp_module2_coarse_cfo_Pipeline_CFO_ESTIMATE_fu_320_early_buf_re_address1),
    .early_buf_re_ce1(grp_module2_coarse_cfo_Pipeline_CFO_ESTIMATE_fu_320_early_buf_re_ce1),
    .early_buf_re_q1(early_buf_re_q1),
    .early_buf_im_address0(grp_module2_coarse_cfo_Pipeline_CFO_ESTIMATE_fu_320_early_buf_im_address0),
    .early_buf_im_ce0(grp_module2_coarse_cfo_Pipeline_CFO_ESTIMATE_fu_320_early_buf_im_ce0),
    .early_buf_im_q0(early_buf_im_q0),
    .early_buf_im_address1(grp_module2_coarse_cfo_Pipeline_CFO_ESTIMATE_fu_320_early_buf_im_address1),
    .early_buf_im_ce1(grp_module2_coarse_cfo_Pipeline_CFO_ESTIMATE_fu_320_early_buf_im_ce1),
    .early_buf_im_q1(early_buf_im_q1)
);

module2_coarse_cfo_module2_coarse_cfo_Pipeline_PHASE_D grp_module2_coarse_cfo_Pipeline_PHASE_D_fu_333(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_module2_coarse_cfo_Pipeline_PHASE_D_fu_333_ap_start),
    .ap_done(grp_module2_coarse_cfo_Pipeline_PHASE_D_fu_333_ap_done),
    .ap_idle(grp_module2_coarse_cfo_Pipeline_PHASE_D_fu_333_ap_idle),
    .ap_ready(grp_module2_coarse_cfo_Pipeline_PHASE_D_fu_333_ap_ready),
    .data_in_dout(data_in_dout),
    .data_in_empty_n(data_in_empty_n),
    .data_in_read(grp_module2_coarse_cfo_Pipeline_PHASE_D_fu_333_data_in_read),
    .passthrough_out_din(grp_module2_coarse_cfo_Pipeline_PHASE_D_fu_333_passthrough_out_din),
    .passthrough_out_full_n(passthrough_out_full_n),
    .passthrough_out_write(grp_module2_coarse_cfo_Pipeline_PHASE_D_fu_333_passthrough_out_write),
    .search_buffer_out_din(grp_module2_coarse_cfo_Pipeline_PHASE_D_fu_333_search_buffer_out_din),
    .search_buffer_out_full_n(search_buffer_out_full_n),
    .search_buffer_out_write(grp_module2_coarse_cfo_Pipeline_PHASE_D_fu_333_search_buffer_out_write),
    .num_samples(num_samples_read_reg_1029),
    .empty(trunc_ln111_reg_1052),
    .sext_ln138(phase_inc_reg_1239),
    .early_buf_re_address0(grp_module2_coarse_cfo_Pipeline_PHASE_D_fu_333_early_buf_re_address0),
    .early_buf_re_ce0(grp_module2_coarse_cfo_Pipeline_PHASE_D_fu_333_early_buf_re_ce0),
    .early_buf_re_q0(early_buf_re_q0),
    .early_buf_im_address0(grp_module2_coarse_cfo_Pipeline_PHASE_D_fu_333_early_buf_im_address0),
    .early_buf_im_ce0(grp_module2_coarse_cfo_Pipeline_PHASE_D_fu_333_early_buf_im_ce0),
    .early_buf_im_q0(early_buf_im_q0)
);

module2_coarse_cfo_mul_28s_32s_54_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 28 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 54 ))
mul_28s_32s_54_1_1_U38(
    .din0(tmp_s_fu_771_p3),
    .din1(frac_reg_1166),
    .dout(mul_ln55_fu_354_p2)
);

module2_coarse_cfo_mul_32s_28ns_48_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 28 ),
    .dout_WIDTH( 48 ))
mul_32s_28ns_48_1_1_U39(
    .din0(signed_angle_2_reg_1218),
    .din1(mul_ln137_fu_358_p1),
    .dout(mul_ln137_fu_358_p2)
);

module2_coarse_cfo_sdiv_51ns_32s_51_55_seq_1 #(
    .ID( 1 ),
    .NUM_STAGE( 55 ),
    .din0_WIDTH( 51 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 51 ))
sdiv_51ns_32s_51_55_seq_1_U40(
    .clk(ap_clk),
    .reset(ap_rst),
    .start(grp_fu_608_ap_start),
    .done(grp_fu_608_ap_done),
    .din0(grp_fu_608_p0),
    .din1(den_fu_584_p3),
    .ce(1'b1),
    .dout(grp_fu_608_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_module2_coarse_cfo_Pipeline_CFO_ESTIMATE_fu_320_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state7)) begin
            grp_module2_coarse_cfo_Pipeline_CFO_ESTIMATE_fu_320_ap_start_reg <= 1'b1;
        end else if ((grp_module2_coarse_cfo_Pipeline_CFO_ESTIMATE_fu_320_ap_ready == 1'b1)) begin
            grp_module2_coarse_cfo_Pipeline_CFO_ESTIMATE_fu_320_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_ap_start_reg <= 1'b1;
        end else if ((grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_ap_ready == 1'b1)) begin
            grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_module2_coarse_cfo_Pipeline_PHASE_D_fu_333_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state73)) begin
            grp_module2_coarse_cfo_Pipeline_PHASE_D_fu_333_ap_start_reg <= 1'b1;
        end else if ((grp_module2_coarse_cfo_Pipeline_PHASE_D_fu_333_ap_ready == 1'b1)) begin
            grp_module2_coarse_cfo_Pipeline_PHASE_D_fu_333_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln39_fu_574_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state10))) begin
        angle_10_reg_291 <= 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state71)) begin
        angle_10_reg_291 <= select_ln61_fu_901_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state3) & (1'b1 == ap_CS_fsm_state3))) begin
        if ((sO_rx_loc_load_load_fu_363_p1 == 1'd1)) begin
            startOffset_2_reg_260 <= grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_startOffset_out;
        end else if ((grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_sO_rx_out == 1'd0)) begin
            startOffset_2_reg_260 <= startOffset_in_dout;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln119_reg_1090 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
        x_reg_280 <= grp_module2_coarse_cfo_Pipeline_CFO_ESTIMATE_fu_320_C_re_out;
    end else if (((icmp_ln119_fu_468_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        x_reg_280 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln119_reg_1090 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
        y_reg_269 <= grp_module2_coarse_cfo_Pipeline_CFO_ESTIMATE_fu_320_C_im_out;
    end else if (((icmp_ln119_fu_468_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        y_reg_269 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        add24_reg_1085 <= add24_fu_463_p2;
        add_ln119_reg_1094 <= add_ln119_fu_479_p2;
        add_reg_1080 <= add_fu_458_p2;
        icmp_ln119_reg_1090 <= icmp_ln119_fu_468_p2;
        sext_ln115_1_reg_1075 <= sext_ln115_1_fu_440_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        add_ln113_reg_1059 <= add_ln113_fu_382_p2;
        sext_ln111_reg_1047 <= sext_ln111_fu_369_p1;
        trunc_ln111_reg_1052 <= trunc_ln111_fu_373_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        add_ln119_1_reg_1100 <= add_ln119_1_fu_511_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state69)) begin
        angle_2_reg_1196 <= angle_2_fu_811_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state70)) begin
        angle_6_reg_1202 <= angle_6_fu_853_p3;
        tmp_7_reg_1208 <= {{angle_6_fu_853_p3[31:26]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        ax_reg_1115 <= ax_fu_548_p3;
        ay_reg_1123 <= ay_fu_562_p3;
        x_neg_reg_1105 <= ap_phi_mux_x_phi_fu_284_p4[32'd31];
        y_neg_reg_1110 <= ap_phi_mux_y_phi_fu_273_p4[32'd31];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state73)) begin
        coarseFreqOff_reg_1234 <= {{mul_ln137_fu_358_p2[47:16]}};
        phase_inc_reg_1239 <= phase_inc_fu_997_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state66)) begin
        frac_reg_1166 <= frac_fu_720_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state65)) begin
        lut_idx_reg_1160 <= lut_idx_fu_688_p3;
        scaled_reg_1155 <= {{sub_ln48_fu_624_p2[50:19]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        num_samples_read_reg_1029 <= num_samples;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state64)) begin
        sdiv_ln47_reg_1149 <= grp_fu_608_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        select_ln114_reg_1070 <= select_ln114_fu_432_p3;
        useLen_reg_1065 <= useLen_fu_393_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state72)) begin
        signed_angle_2_reg_1218 <= signed_angle_2_fu_921_p3;
        tmp_2_reg_1229 <= {{signed_angle_2_fu_921_p3[31:4]}};
        tmp_9_reg_1224 <= signed_angle_2_fu_921_p3[32'd31];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state67)) begin
        sub_ln55_reg_1186[24 : 8] <= sub_ln55_fu_765_p2[24 : 8];
        v0_reg_1181[23 : 8] <= v0_fu_741_p3[23 : 8];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        swap_reg_1134 <= swap_fu_580_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state68)) begin
        trunc_ln5_reg_1191 <= {{mul_ln55_fu_354_p2[53:22]}};
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

always @ (*) begin
    if ((grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

assign ap_ST_fsm_state34_blk = 1'b0;

assign ap_ST_fsm_state35_blk = 1'b0;

assign ap_ST_fsm_state36_blk = 1'b0;

assign ap_ST_fsm_state37_blk = 1'b0;

assign ap_ST_fsm_state38_blk = 1'b0;

assign ap_ST_fsm_state39_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state3)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state40_blk = 1'b0;

assign ap_ST_fsm_state41_blk = 1'b0;

assign ap_ST_fsm_state42_blk = 1'b0;

assign ap_ST_fsm_state43_blk = 1'b0;

assign ap_ST_fsm_state44_blk = 1'b0;

assign ap_ST_fsm_state45_blk = 1'b0;

assign ap_ST_fsm_state46_blk = 1'b0;

assign ap_ST_fsm_state47_blk = 1'b0;

assign ap_ST_fsm_state48_blk = 1'b0;

assign ap_ST_fsm_state49_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state50_blk = 1'b0;

assign ap_ST_fsm_state51_blk = 1'b0;

assign ap_ST_fsm_state52_blk = 1'b0;

assign ap_ST_fsm_state53_blk = 1'b0;

assign ap_ST_fsm_state54_blk = 1'b0;

assign ap_ST_fsm_state55_blk = 1'b0;

assign ap_ST_fsm_state56_blk = 1'b0;

assign ap_ST_fsm_state57_blk = 1'b0;

assign ap_ST_fsm_state58_blk = 1'b0;

assign ap_ST_fsm_state59_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state60_blk = 1'b0;

assign ap_ST_fsm_state61_blk = 1'b0;

assign ap_ST_fsm_state62_blk = 1'b0;

assign ap_ST_fsm_state63_blk = 1'b0;

assign ap_ST_fsm_state64_blk = 1'b0;

assign ap_ST_fsm_state65_blk = 1'b0;

assign ap_ST_fsm_state66_blk = 1'b0;

assign ap_ST_fsm_state67_blk = 1'b0;

assign ap_ST_fsm_state68_blk = 1'b0;

assign ap_ST_fsm_state69_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state70_blk = 1'b0;

assign ap_ST_fsm_state71_blk = 1'b0;

assign ap_ST_fsm_state72_blk = 1'b0;

assign ap_ST_fsm_state73_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_block_state74) | (grp_module2_coarse_cfo_Pipeline_PHASE_D_fu_333_ap_done == 1'b0))) begin
        ap_ST_fsm_state74_blk = 1'b1;
    end else begin
        ap_ST_fsm_state74_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((grp_module2_coarse_cfo_Pipeline_CFO_ESTIMATE_fu_320_ap_done == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((~((1'b1 == ap_block_state74) | (grp_module2_coarse_cfo_Pipeline_PHASE_D_fu_333_ap_done == 1'b0)) & (1'b1 == ap_CS_fsm_state74))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln119_reg_1090 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
        ap_phi_mux_x_phi_fu_284_p4 = grp_module2_coarse_cfo_Pipeline_CFO_ESTIMATE_fu_320_C_re_out;
    end else begin
        ap_phi_mux_x_phi_fu_284_p4 = x_reg_280;
    end
end

always @ (*) begin
    if (((icmp_ln119_reg_1090 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
        ap_phi_mux_y_phi_fu_273_p4 = grp_module2_coarse_cfo_Pipeline_CFO_ESTIMATE_fu_320_C_im_out;
    end else begin
        ap_phi_mux_y_phi_fu_273_p4 = y_reg_269;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state74) | (grp_module2_coarse_cfo_Pipeline_PHASE_D_fu_333_ap_done == 1'b0)) & (1'b1 == ap_CS_fsm_state74))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state66)) begin
        atan_lut_ce0_local = 1'b1;
    end else begin
        atan_lut_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state66)) begin
        atan_lut_ce1_local = 1'b1;
    end else begin
        atan_lut_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state74)) begin
        coarseFreqOff_out_blk_n = coarseFreqOff_out_full_n;
    end else begin
        coarseFreqOff_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state74) | (grp_module2_coarse_cfo_Pipeline_PHASE_D_fu_333_ap_done == 1'b0)) & (1'b1 == ap_CS_fsm_state74))) begin
        coarseFreqOff_out_write = 1'b1;
    end else begin
        coarseFreqOff_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state74)) begin
        data_in_read = grp_module2_coarse_cfo_Pipeline_PHASE_D_fu_333_data_in_read;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        data_in_read = grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_data_in_read;
    end else begin
        data_in_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state74)) begin
        early_buf_im_address0 = grp_module2_coarse_cfo_Pipeline_PHASE_D_fu_333_early_buf_im_address0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        early_buf_im_address0 = grp_module2_coarse_cfo_Pipeline_CFO_ESTIMATE_fu_320_early_buf_im_address0;
    end else begin
        early_buf_im_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        early_buf_im_address1 = grp_module2_coarse_cfo_Pipeline_CFO_ESTIMATE_fu_320_early_buf_im_address1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        early_buf_im_address1 = grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_early_buf_im_address1;
    end else begin
        early_buf_im_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state74)) begin
        early_buf_im_ce0 = grp_module2_coarse_cfo_Pipeline_PHASE_D_fu_333_early_buf_im_ce0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        early_buf_im_ce0 = grp_module2_coarse_cfo_Pipeline_CFO_ESTIMATE_fu_320_early_buf_im_ce0;
    end else begin
        early_buf_im_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        early_buf_im_ce1 = grp_module2_coarse_cfo_Pipeline_CFO_ESTIMATE_fu_320_early_buf_im_ce1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        early_buf_im_ce1 = grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_early_buf_im_ce1;
    end else begin
        early_buf_im_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        early_buf_im_we1 = grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_early_buf_im_we1;
    end else begin
        early_buf_im_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state74)) begin
        early_buf_re_address0 = grp_module2_coarse_cfo_Pipeline_PHASE_D_fu_333_early_buf_re_address0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        early_buf_re_address0 = grp_module2_coarse_cfo_Pipeline_CFO_ESTIMATE_fu_320_early_buf_re_address0;
    end else begin
        early_buf_re_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        early_buf_re_address1 = grp_module2_coarse_cfo_Pipeline_CFO_ESTIMATE_fu_320_early_buf_re_address1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        early_buf_re_address1 = grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_early_buf_re_address1;
    end else begin
        early_buf_re_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state74)) begin
        early_buf_re_ce0 = grp_module2_coarse_cfo_Pipeline_PHASE_D_fu_333_early_buf_re_ce0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        early_buf_re_ce0 = grp_module2_coarse_cfo_Pipeline_CFO_ESTIMATE_fu_320_early_buf_re_ce0;
    end else begin
        early_buf_re_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        early_buf_re_ce1 = grp_module2_coarse_cfo_Pipeline_CFO_ESTIMATE_fu_320_early_buf_re_ce1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        early_buf_re_ce1 = grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_early_buf_re_ce1;
    end else begin
        early_buf_re_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        early_buf_re_we1 = grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_early_buf_re_we1;
    end else begin
        early_buf_re_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln39_fu_574_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state10))) begin
        grp_fu_608_ap_start = 1'b1;
    end else begin
        grp_fu_608_ap_start = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state74)) begin
        passthrough_out_din = grp_module2_coarse_cfo_Pipeline_PHASE_D_fu_333_passthrough_out_din;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        passthrough_out_din = grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_passthrough_out_din;
    end else begin
        passthrough_out_din = grp_module2_coarse_cfo_Pipeline_PHASE_D_fu_333_passthrough_out_din;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state74)) begin
        passthrough_out_write = grp_module2_coarse_cfo_Pipeline_PHASE_D_fu_333_passthrough_out_write;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        passthrough_out_write = grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_passthrough_out_write;
    end else begin
        passthrough_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state74)) begin
        searchBufferLen_out_blk_n = searchBufferLen_out_full_n;
    end else begin
        searchBufferLen_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state74) | (grp_module2_coarse_cfo_Pipeline_PHASE_D_fu_333_ap_done == 1'b0)) & (1'b1 == ap_CS_fsm_state74))) begin
        searchBufferLen_out_write = 1'b1;
    end else begin
        searchBufferLen_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_sO_rx_out == 1'd0))) begin
        startOffset_fwd_out_blk_n = startOffset_fwd_out_full_n;
    end else begin
        startOffset_fwd_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state3) & (1'b1 == ap_CS_fsm_state3) & (grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_sO_rx_out == 1'd0))) begin
        startOffset_fwd_out_din = startOffset_in_dout;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        startOffset_fwd_out_din = grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_startOffset_fwd_out_din;
    end else begin
        startOffset_fwd_out_din = grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_startOffset_fwd_out_din;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state3) & (1'b1 == ap_CS_fsm_state3) & (grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_sO_rx_out == 1'd0))) begin
        startOffset_fwd_out_write = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        startOffset_fwd_out_write = grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_startOffset_fwd_out_write;
    end else begin
        startOffset_fwd_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_sO_rx_out == 1'd0))) begin
        startOffset_in_blk_n = startOffset_in_empty_n;
    end else begin
        startOffset_in_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state3) & (1'b1 == ap_CS_fsm_state3) & (grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_sO_rx_out == 1'd0))) begin
        startOffset_in_read = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        startOffset_in_read = grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_startOffset_in_read;
    end else begin
        startOffset_in_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b0 == ap_block_state3) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((icmp_ln119_fu_468_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((grp_module2_coarse_cfo_Pipeline_CFO_ESTIMATE_fu_320_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((icmp_ln39_fu_574_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state72;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            ap_NS_fsm = ap_ST_fsm_state50;
        end
        ap_ST_fsm_state50 : begin
            ap_NS_fsm = ap_ST_fsm_state51;
        end
        ap_ST_fsm_state51 : begin
            ap_NS_fsm = ap_ST_fsm_state52;
        end
        ap_ST_fsm_state52 : begin
            ap_NS_fsm = ap_ST_fsm_state53;
        end
        ap_ST_fsm_state53 : begin
            ap_NS_fsm = ap_ST_fsm_state54;
        end
        ap_ST_fsm_state54 : begin
            ap_NS_fsm = ap_ST_fsm_state55;
        end
        ap_ST_fsm_state55 : begin
            ap_NS_fsm = ap_ST_fsm_state56;
        end
        ap_ST_fsm_state56 : begin
            ap_NS_fsm = ap_ST_fsm_state57;
        end
        ap_ST_fsm_state57 : begin
            ap_NS_fsm = ap_ST_fsm_state58;
        end
        ap_ST_fsm_state58 : begin
            ap_NS_fsm = ap_ST_fsm_state59;
        end
        ap_ST_fsm_state59 : begin
            ap_NS_fsm = ap_ST_fsm_state60;
        end
        ap_ST_fsm_state60 : begin
            ap_NS_fsm = ap_ST_fsm_state61;
        end
        ap_ST_fsm_state61 : begin
            ap_NS_fsm = ap_ST_fsm_state62;
        end
        ap_ST_fsm_state62 : begin
            ap_NS_fsm = ap_ST_fsm_state63;
        end
        ap_ST_fsm_state63 : begin
            ap_NS_fsm = ap_ST_fsm_state64;
        end
        ap_ST_fsm_state64 : begin
            ap_NS_fsm = ap_ST_fsm_state65;
        end
        ap_ST_fsm_state65 : begin
            ap_NS_fsm = ap_ST_fsm_state66;
        end
        ap_ST_fsm_state66 : begin
            ap_NS_fsm = ap_ST_fsm_state67;
        end
        ap_ST_fsm_state67 : begin
            ap_NS_fsm = ap_ST_fsm_state68;
        end
        ap_ST_fsm_state68 : begin
            ap_NS_fsm = ap_ST_fsm_state69;
        end
        ap_ST_fsm_state69 : begin
            ap_NS_fsm = ap_ST_fsm_state70;
        end
        ap_ST_fsm_state70 : begin
            ap_NS_fsm = ap_ST_fsm_state71;
        end
        ap_ST_fsm_state71 : begin
            ap_NS_fsm = ap_ST_fsm_state72;
        end
        ap_ST_fsm_state72 : begin
            ap_NS_fsm = ap_ST_fsm_state73;
        end
        ap_ST_fsm_state73 : begin
            ap_NS_fsm = ap_ST_fsm_state74;
        end
        ap_ST_fsm_state74 : begin
            if ((~((1'b1 == ap_block_state74) | (grp_module2_coarse_cfo_Pipeline_PHASE_D_fu_333_ap_done == 1'b0)) & (1'b1 == ap_CS_fsm_state74))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state74;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add24_fu_463_p2 = (trunc_ln111_reg_1052 + 11'd28);

assign add_fu_458_p2 = (trunc_ln111_reg_1052 + 11'd12);

assign add_ln113_fu_382_p2 = ($signed(rxLen_local_fu_377_p2) + $signed(32'd4294967284));

assign add_ln119_1_fu_511_p2 = ($signed(sext_ln119_fu_489_p1) + $signed(smax_neg_fu_503_p3));

assign add_ln119_fu_479_p2 = ($signed(sub_ln119_fu_474_p2) + $signed(sext_ln111_reg_1047));

assign add_ln49_fu_674_p2 = (tmp_4_fu_640_p4 + 13'd1);

assign add_ln54_fu_730_p2 = (trunc_ln49_fu_708_p1 + 8'd1);

assign add_ln61_fu_895_p2 = (angle_8_fu_880_p3 + 32'd67108864);

assign angle_1_fu_805_p2 = (32'd16777216 - angle_fu_800_p2);

assign angle_2_fu_811_p3 = ((swap_reg_1134[0:0] == 1'b1) ? angle_1_fu_805_p2 : angle_fu_800_p2);

assign angle_3_fu_831_p4 = {{sub_ln58_fu_825_p2[47:16]}};

assign angle_4_fu_841_p3 = ((x_neg_reg_1105[0:0] == 1'b1) ? angle_3_fu_831_p4 : angle_2_reg_1196);

assign angle_5_fu_847_p2 = (32'd67108864 - angle_4_fu_841_p3);

assign angle_6_fu_853_p3 = ((y_neg_reg_1110[0:0] == 1'b1) ? angle_5_fu_847_p2 : angle_4_fu_841_p3);

assign angle_7_fu_875_p2 = ($signed(angle_6_reg_1202) + $signed(32'd4227858432));

assign angle_8_fu_880_p3 = ((icmp_ln60_fu_870_p2[0:0] == 1'b1) ? angle_7_fu_875_p2 : angle_6_reg_1202);

assign angle_fu_800_p2 = ($signed(trunc_ln5_reg_1191) + $signed(sext_ln53_fu_797_p1));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state64 = ap_CS_fsm[32'd63];

assign ap_CS_fsm_state65 = ap_CS_fsm[32'd64];

assign ap_CS_fsm_state66 = ap_CS_fsm[32'd65];

assign ap_CS_fsm_state67 = ap_CS_fsm[32'd66];

assign ap_CS_fsm_state68 = ap_CS_fsm[32'd67];

assign ap_CS_fsm_state69 = ap_CS_fsm[32'd68];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state70 = ap_CS_fsm[32'd69];

assign ap_CS_fsm_state71 = ap_CS_fsm[32'd70];

assign ap_CS_fsm_state72 = ap_CS_fsm[32'd71];

assign ap_CS_fsm_state73 = ap_CS_fsm[32'd72];

assign ap_CS_fsm_state74 = ap_CS_fsm[32'd73];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state3 = (((grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_sO_rx_out == 1'd0) & (startOffset_fwd_out_full_n == 1'b0)) | ((grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_sO_rx_out == 1'd0) & (startOffset_in_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_state74 = ((searchBufferLen_out_full_n == 1'b0) | (coarseFreqOff_out_full_n == 1'b0));
end

assign atan_lut_address0 = zext_ln54_fu_736_p1;

assign atan_lut_address1 = zext_ln53_fu_725_p1;

assign ax_fu_548_p3 = ((x_neg_fu_526_p3[0:0] == 1'b1) ? sub_ln36_fu_542_p2 : ap_phi_mux_x_phi_fu_284_p4);

assign ay_fu_562_p3 = ((y_neg_fu_534_p3[0:0] == 1'b1) ? sub_ln37_fu_556_p2 : ap_phi_mux_y_phi_fu_273_p4);

assign coarseFreqOff_out_din = coarseFreqOff_reg_1234;

assign corrLen_fu_453_p2 = ($signed(sext_ln115_fu_449_p1) + $signed(useLen_reg_1065));

assign den_fu_584_p3 = ((swap_fu_580_p2[0:0] == 1'b1) ? ay_reg_1123 : ax_reg_1115);

assign empty_fu_493_p2 = (($signed(add_ln119_reg_1094) > $signed(32'd4294967151)) ? 1'b1 : 1'b0);

assign frac_fu_720_p2 = (scaled_reg_1155 - shl_ln1_fu_712_p3);

assign grp_fu_608_p0 = {{select_ln44_fu_590_p3}, {19'd0}};

assign grp_module2_coarse_cfo_Pipeline_CFO_ESTIMATE_fu_320_ap_start = grp_module2_coarse_cfo_Pipeline_CFO_ESTIMATE_fu_320_ap_start_reg;

assign grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_ap_start = grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_ap_start_reg;

assign grp_module2_coarse_cfo_Pipeline_PHASE_D_fu_333_ap_start = grp_module2_coarse_cfo_Pipeline_PHASE_D_fu_333_ap_start_reg;

assign icmp_ln113_fu_388_p2 = (($signed(add_ln113_reg_1059) < $signed(32'd144)) ? 1'b1 : 1'b0);

assign icmp_ln119_fu_468_p2 = (($signed(corrLen_fu_453_p2) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln132_fu_909_p2 = (($signed(angle_10_reg_291) > $signed(32'd33554432)) ? 1'b1 : 1'b0);

assign icmp_ln39_fu_574_p2 = ((or_ln39_fu_570_p2 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln49_fu_668_p2 = ((tmp_6_fu_658_p4 != 19'd0) ? 1'b1 : 1'b0);

assign icmp_ln50_fu_696_p2 = (($signed(lut_idx_reg_1160) > $signed(13'd254)) ? 1'b1 : 1'b0);

assign icmp_ln60_fu_870_p2 = (($signed(tmp_7_reg_1208) > $signed(6'd0)) ? 1'b1 : 1'b0);

assign lut_idx_1_fu_701_p3 = ((icmp_ln50_fu_696_p2[0:0] == 1'b1) ? 13'd254 : lut_idx_reg_1160);

assign lut_idx_fu_688_p3 = ((tmp_5_fu_650_p3[0:0] == 1'b1) ? select_ln49_fu_680_p3 : tmp_4_fu_640_p4);

assign mul_ln137_fu_358_p1 = 48'd80000000;

assign or_ln39_fu_570_p2 = (ay_reg_1123 | ax_reg_1115);

assign p_op_fu_498_p2 = (32'd0 - add_ln119_reg_1094);

assign phase_inc_fu_997_p3 = ((tmp_9_reg_1224[0:0] == 1'b1) ? sub_ln138_1_fu_991_p2 : zext_ln138_1_fu_988_p1);

assign rxLen_local_fu_377_p2 = ($signed(num_samples_read_reg_1029) - $signed(sext_ln111_fu_369_p1));

assign sO_rx_loc_load_load_fu_363_p1 = grp_module2_coarse_cfo_Pipeline_PHASE_A_fu_302_sO_rx_out;

assign searchBufferLen_out_din = 16'd640;

assign search_buffer_out_din = grp_module2_coarse_cfo_Pipeline_PHASE_D_fu_333_search_buffer_out_din;

assign search_buffer_out_write = grp_module2_coarse_cfo_Pipeline_PHASE_D_fu_333_search_buffer_out_write;

assign select_ln114_fu_432_p3 = ((tmp_fu_400_p3[0:0] == 1'b1) ? sub_ln114_1_fu_422_p2 : zext_ln114_1_fu_428_p1);

assign select_ln44_fu_590_p3 = ((swap_fu_580_p2[0:0] == 1'b1) ? ax_reg_1115 : ay_reg_1123);

assign select_ln49_fu_680_p3 = ((icmp_ln49_fu_668_p2[0:0] == 1'b1) ? add_ln49_fu_674_p2 : tmp_4_fu_640_p4);

assign select_ln61_fu_901_p3 = ((tmp_8_fu_887_p3[0:0] == 1'b1) ? add_ln61_fu_895_p2 : angle_8_fu_880_p3);

assign sext_ln111_fu_369_p1 = startOffset_2_reg_260;

assign sext_ln115_1_fu_440_p1 = $signed(select_ln114_reg_1070);

assign sext_ln115_fu_449_p1 = $signed(sub_ln115_fu_443_p2);

assign sext_ln119_fu_489_p1 = $signed(sub_ln119_1_fu_484_p2);

assign sext_ln53_1_fu_749_p1 = v0_fu_741_p3;

assign sext_ln53_fu_797_p1 = v0_reg_1181;

assign sext_ln54_fu_761_p1 = $signed(v1_fu_753_p3);

assign shl_ln1_fu_712_p3 = {{lut_idx_1_fu_701_p3}, {19'd0}};

assign shl_ln2_fu_818_p3 = {{angle_2_reg_1196}, {16'd0}};

assign shl_ln3_fu_961_p3 = {{signed_angle_2_reg_1218}, {16'd0}};

assign shl_ln48_1_fu_619_p2 = sdiv_ln47_reg_1149 << 51'd19;

assign shl_ln48_fu_614_p2 = sdiv_ln47_reg_1149 << 51'd27;

assign signed_angle_1_fu_915_p2 = ($signed(angle_10_reg_291) + $signed(32'd4227858432));

assign signed_angle_2_fu_921_p3 = ((icmp_ln132_fu_909_p2[0:0] == 1'b1) ? signed_angle_1_fu_915_p2 : angle_10_reg_291);

assign smax_neg_fu_503_p3 = ((empty_fu_493_p2[0:0] == 1'b1) ? p_op_fu_498_p2 : 32'd145);

assign sub_ln114_1_fu_422_p2 = (5'd0 - zext_ln114_fu_418_p1);

assign sub_ln114_fu_412_p2 = (4'd0 - trunc_ln114_fu_408_p1);

assign sub_ln115_fu_443_p2 = ($signed(6'd48) - $signed(sext_ln115_1_fu_440_p1));

assign sub_ln119_1_fu_484_p2 = ($signed(6'd47) - $signed(sext_ln115_1_reg_1075));

assign sub_ln119_fu_474_p2 = (32'd11 - num_samples_read_reg_1029);

assign sub_ln138_1_fu_991_p2 = (29'd0 - zext_ln138_fu_984_p1);

assign sub_ln138_fu_968_p2 = (48'd0 - shl_ln3_fu_961_p3);

assign sub_ln36_fu_542_p2 = (32'd0 - ap_phi_mux_x_phi_fu_284_p4);

assign sub_ln37_fu_556_p2 = (32'd0 - ap_phi_mux_y_phi_fu_273_p4);

assign sub_ln48_fu_624_p2 = (shl_ln48_fu_614_p2 - shl_ln48_1_fu_619_p2);

assign sub_ln55_fu_765_p2 = ($signed(sext_ln54_fu_761_p1) - $signed(sext_ln53_1_fu_749_p1));

assign sub_ln58_fu_825_p2 = (48'd2199023255552 - shl_ln2_fu_818_p3);

assign swap_fu_580_p2 = (($signed(ay_reg_1123) > $signed(ax_reg_1115)) ? 1'b1 : 1'b0);

assign tmp_1_fu_974_p4 = {{sub_ln138_fu_968_p2[47:20]}};

assign tmp_4_fu_640_p4 = {{sub_ln48_fu_624_p2[50:38]}};

assign tmp_5_fu_650_p3 = sub_ln48_fu_624_p2[32'd50];

assign tmp_6_fu_658_p4 = {{sub_ln48_fu_624_p2[37:19]}};

assign tmp_8_fu_887_p3 = angle_8_fu_880_p3[32'd31];

assign tmp_fu_400_p3 = useLen_fu_393_p3[32'd31];

assign tmp_s_fu_771_p3 = {{sub_ln55_reg_1186}, {3'd0}};

assign trunc_ln111_fu_373_p1 = startOffset_2_reg_260[10:0];

assign trunc_ln114_fu_408_p1 = useLen_fu_393_p3[3:0];

assign trunc_ln49_fu_708_p1 = lut_idx_1_fu_701_p3[7:0];

assign useLen_fu_393_p3 = ((icmp_ln113_fu_388_p2[0:0] == 1'b1) ? add_ln113_reg_1059 : 32'd144);

assign v0_fu_741_p3 = {{atan_lut_q1}, {8'd0}};

assign v1_fu_753_p3 = {{atan_lut_q0}, {8'd0}};

assign x_neg_fu_526_p3 = ap_phi_mux_x_phi_fu_284_p4[32'd31];

assign y_neg_fu_534_p3 = ap_phi_mux_y_phi_fu_273_p4[32'd31];

assign zext_ln114_1_fu_428_p1 = trunc_ln114_fu_408_p1;

assign zext_ln114_fu_418_p1 = sub_ln114_fu_412_p2;

assign zext_ln138_1_fu_988_p1 = tmp_2_reg_1229;

assign zext_ln138_fu_984_p1 = tmp_1_fu_974_p4;

assign zext_ln53_fu_725_p1 = lut_idx_1_fu_701_p3;

assign zext_ln54_fu_736_p1 = add_ln54_fu_730_p2;

always @ (posedge ap_clk) begin
    v0_reg_1181[7:0] <= 8'b00000000;
    sub_ln55_reg_1186[7:0] <= 8'b00000000;
end

endmodule //module2_coarse_cfo
