-- ==============================================================
-- Generated by Vitis HLS v2024.2.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity system_top_combine_and_peak_Pipeline_COMBINE is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    re_out_dout : IN STD_LOGIC_VECTOR (39 downto 0);
    re_out_empty_n : IN STD_LOGIC;
    re_out_read : OUT STD_LOGIC;
    re_out_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    re_out_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    im_out_dout : IN STD_LOGIC_VECTOR (39 downto 0);
    im_out_empty_n : IN STD_LOGIC;
    im_out_read : OUT STD_LOGIC;
    im_out_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    im_out_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    sum_out_dout : IN STD_LOGIC_VECTOR (39 downto 0);
    sum_out_empty_n : IN STD_LOGIC;
    sum_out_read : OUT STD_LOGIC;
    sum_out_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    sum_out_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    max_pos_2_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    max_pos_2_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of system_top_combine_and_peak_Pipeline_COMBINE is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv48_0 : STD_LOGIC_VECTOR (47 downto 0) := "000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_24 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100100";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv10_27F : STD_LOGIC_VECTOR (9 downto 0) := "1001111111";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_47 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000111";
    constant ap_const_lv10_9E : STD_LOGIC_VECTOR (9 downto 0) := "0010011110";
    constant ap_const_lv10_361 : STD_LOGIC_VECTOR (9 downto 0) := "1101100001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln57_fu_179_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal re_out_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal im_out_blk_n : STD_LOGIC;
    signal sum_out_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp0_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp0 : BOOLEAN;
    signal i_031_load_reg_318 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal i_031_load_reg_318_pp0_iter1_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal i_031_load_reg_318_pp0_iter2_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal corr_re_fu_145_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal corr_re_reg_324 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal corr_im_fu_167_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal corr_im_reg_329 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln57_reg_334 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln57_reg_334_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln57_reg_334_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal mul_ln65_fu_99_p2 : STD_LOGIC_VECTOR (71 downto 0);
    signal mul_ln65_reg_338 : STD_LOGIC_VECTOR (71 downto 0);
    signal mul_ln65_1_fu_103_p2 : STD_LOGIC_VECTOR (71 downto 0);
    signal mul_ln65_1_reg_343 : STD_LOGIC_VECTOR (71 downto 0);
    signal metric_reg_348 : STD_LOGIC_VECTOR (47 downto 0);
    signal i_031_fu_62 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    signal i_fu_173_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_031_load : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal max_pos3_fu_66 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal max_pos_fu_278_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_grp0 : BOOLEAN;
    signal max_metric4_fu_70 : STD_LOGIC_VECTOR (47 downto 0) := "000000000000000000000000000000000000000000000000";
    signal max_metric_fu_270_p3 : STD_LOGIC_VECTOR (47 downto 0);
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_block_pp0_stage0_01001_grp0 : BOOLEAN;
    signal mul_ln65_fu_99_p0 : STD_LOGIC_VECTOR (35 downto 0);
    signal sext_ln65_fu_197_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal mul_ln65_fu_99_p1 : STD_LOGIC_VECTOR (35 downto 0);
    signal mul_ln65_1_fu_103_p0 : STD_LOGIC_VECTOR (35 downto 0);
    signal sext_ln66_fu_210_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal mul_ln65_1_fu_103_p1 : STD_LOGIC_VECTOR (35 downto 0);
    signal trunc_ln_fu_125_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln63_1_fu_135_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln9_fu_151_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln64_fu_161_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln_fu_190_p3 : STD_LOGIC_VECTOR (35 downto 0);
    signal shl_ln3_fu_203_p3 : STD_LOGIC_VECTOR (35 downto 0);
    signal add_ln65_fu_216_p2 : STD_LOGIC_VECTOR (71 downto 0);
    signal add_ln72_fu_246_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln70_fu_241_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln70_fu_251_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln69_fu_236_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal max_metric_1_fu_255_p3 : STD_LOGIC_VECTOR (47 downto 0);
    signal max_pos_1_fu_262_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component system_top_mul_36s_36s_72_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (35 downto 0);
        din1 : IN STD_LOGIC_VECTOR (35 downto 0);
        dout : OUT STD_LOGIC_VECTOR (71 downto 0) );
    end component;


    component system_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_36s_36s_72_1_1_U164 : component system_top_mul_36s_36s_72_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 36,
        din1_WIDTH => 36,
        dout_WIDTH => 72)
    port map (
        din0 => mul_ln65_fu_99_p0,
        din1 => mul_ln65_fu_99_p1,
        dout => mul_ln65_fu_99_p2);

    mul_36s_36s_72_1_1_U165 : component system_top_mul_36s_36s_72_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 36,
        din1_WIDTH => 36,
        dout_WIDTH => 72)
    port map (
        din0 => mul_ln65_1_fu_103_p0,
        din1 => mul_ln65_1_fu_103_p1,
        dout => mul_ln65_1_fu_103_p2);

    flow_control_loop_pipe_sequential_init_U : component system_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp0_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0)) then 
                    ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_1;
                end if; 
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_loop_exit_ready_pp0_iter3_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_0))) then 
                ap_loop_exit_ready_pp0_iter3_reg <= ap_const_logic_0;
            elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then 
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
            end if; 
        end if;
    end process;

    i_031_fu_62_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_start_int = ap_const_logic_1)) then 
                    i_031_fu_62 <= i_fu_173_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_031_fu_62 <= ap_const_lv10_0;
                end if;
            end if; 
        end if;
    end process;

    max_metric4_fu_70_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    max_metric4_fu_70 <= ap_const_lv48_0;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    max_metric4_fu_70 <= max_metric_fu_270_p3;
                end if;
            end if; 
        end if;
    end process;

    max_pos3_fu_66_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    max_pos3_fu_66 <= ap_const_lv32_0;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    max_pos3_fu_66 <= max_pos_fu_278_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                i_031_load_reg_318 <= ap_sig_allocacmp_i_031_load;
                i_031_load_reg_318_pp0_iter1_reg <= i_031_load_reg_318;
                icmp_ln57_reg_334 <= icmp_ln57_fu_179_p2;
                icmp_ln57_reg_334_pp0_iter1_reg <= icmp_ln57_reg_334;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                corr_im_reg_329 <= corr_im_fu_167_p2;
                corr_re_reg_324 <= corr_re_fu_145_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                i_031_load_reg_318_pp0_iter2_reg <= i_031_load_reg_318_pp0_iter1_reg;
                icmp_ln57_reg_334_pp0_iter2_reg <= icmp_ln57_reg_334_pp0_iter1_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then
                metric_reg_348 <= add_ln65_fu_216_p2(71 downto 24);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                mul_ln65_1_reg_343 <= mul_ln65_1_fu_103_p2;
                mul_ln65_reg_338 <= mul_ln65_fu_99_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln64_fu_161_p2 <= std_logic_vector(unsigned(trunc_ln63_1_fu_135_p4) + unsigned(trunc_ln_fu_125_p4));
    add_ln65_fu_216_p2 <= std_logic_vector(unsigned(mul_ln65_1_reg_343) + unsigned(mul_ln65_reg_338));
    add_ln72_fu_246_p2 <= std_logic_vector(unsigned(i_031_load_reg_318_pp0_iter2_reg) + unsigned(ap_const_lv10_361));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_block_state1_pp0_stage0_iter0_grp1, ap_start_int)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0_grp1));
    end process;

        ap_block_pp0_stage0_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_block_state1_pp0_stage0_iter0_grp1, ap_start_int)
    begin
                ap_block_pp0_stage0_11001_grp1 <= ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0_grp1));
    end process;

        ap_block_pp0_stage0_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_block_state1_pp0_stage0_iter0_grp1, ap_start_int)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0_grp1));
    end process;

        ap_block_pp0_stage0_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state1_pp0_stage0_iter0_grp1_assign_proc : process(re_out_empty_n, im_out_empty_n, sum_out_empty_n)
    begin
                ap_block_state1_pp0_stage0_iter0_grp1 <= ((sum_out_empty_n = ap_const_logic_0) or (im_out_empty_n = ap_const_logic_0) or (re_out_empty_n = ap_const_logic_0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, icmp_ln57_fu_179_p2, ap_start_int)
    begin
        if (((icmp_ln57_fu_179_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter3_reg, ap_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_031_load_assign_proc : process(ap_CS_fsm_pp0_stage0, i_031_fu_62, ap_loop_init, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i_031_load <= ap_const_lv10_0;
        else 
            ap_sig_allocacmp_i_031_load <= i_031_fu_62;
        end if; 
    end process;

    corr_im_fu_167_p2 <= std_logic_vector(unsigned(trunc_ln9_fu_151_p4) - unsigned(add_ln64_fu_161_p2));
    corr_re_fu_145_p2 <= std_logic_vector(unsigned(trunc_ln_fu_125_p4) - unsigned(trunc_ln63_1_fu_135_p4));
    i_fu_173_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_031_load) + unsigned(ap_const_lv10_1));
    icmp_ln57_fu_179_p2 <= "1" when (ap_sig_allocacmp_i_031_load = ap_const_lv10_27F) else "0";
    icmp_ln69_fu_236_p2 <= "1" when (unsigned(i_031_load_reg_318_pp0_iter2_reg) > unsigned(ap_const_lv10_9E)) else "0";
    icmp_ln70_fu_241_p2 <= "1" when (signed(metric_reg_348) > signed(max_metric4_fu_70)) else "0";

    im_out_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, im_out_empty_n, ap_block_pp0_stage0_grp1, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            im_out_blk_n <= im_out_empty_n;
        else 
            im_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    im_out_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001_grp1, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            im_out_read <= ap_const_logic_1;
        else 
            im_out_read <= ap_const_logic_0;
        end if; 
    end process;

    max_metric_1_fu_255_p3 <= 
        metric_reg_348 when (icmp_ln70_fu_241_p2(0) = '1') else 
        max_metric4_fu_70;
    max_metric_fu_270_p3 <= 
        max_metric_1_fu_255_p3 when (icmp_ln69_fu_236_p2(0) = '1') else 
        max_metric4_fu_70;
    max_pos_1_fu_262_p3 <= 
        zext_ln70_fu_251_p1 when (icmp_ln70_fu_241_p2(0) = '1') else 
        max_pos3_fu_66;
    max_pos_2_out <= 
        max_pos_1_fu_262_p3 when (icmp_ln69_fu_236_p2(0) = '1') else 
        max_pos3_fu_66;

    max_pos_2_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, icmp_ln57_reg_334_pp0_iter2_reg, ap_loop_exit_ready_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1) and (icmp_ln57_reg_334_pp0_iter2_reg = ap_const_lv1_1))) then 
            max_pos_2_out_ap_vld <= ap_const_logic_1;
        else 
            max_pos_2_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    max_pos_fu_278_p3 <= 
        max_pos_1_fu_262_p3 when (icmp_ln69_fu_236_p2(0) = '1') else 
        max_pos3_fu_66;
    mul_ln65_1_fu_103_p0 <= sext_ln66_fu_210_p1(36 - 1 downto 0);
    mul_ln65_1_fu_103_p1 <= sext_ln66_fu_210_p1(36 - 1 downto 0);
    mul_ln65_fu_99_p0 <= sext_ln65_fu_197_p1(36 - 1 downto 0);
    mul_ln65_fu_99_p1 <= sext_ln65_fu_197_p1(36 - 1 downto 0);

    re_out_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, re_out_empty_n, ap_block_pp0_stage0_grp1, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            re_out_blk_n <= re_out_empty_n;
        else 
            re_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    re_out_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001_grp1, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            re_out_read <= ap_const_logic_1;
        else 
            re_out_read <= ap_const_logic_0;
        end if; 
    end process;

        sext_ln65_fu_197_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln_fu_190_p3),72));

        sext_ln66_fu_210_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln3_fu_203_p3),72));

    shl_ln3_fu_203_p3 <= (corr_im_reg_329 & ap_const_lv4_0);
    shl_ln_fu_190_p3 <= (corr_re_reg_324 & ap_const_lv4_0);

    sum_out_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, sum_out_empty_n, ap_block_pp0_stage0_grp1, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            sum_out_blk_n <= sum_out_empty_n;
        else 
            sum_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    sum_out_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001_grp1, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            sum_out_read <= ap_const_logic_1;
        else 
            sum_out_read <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln63_1_fu_135_p4 <= im_out_dout(36 downto 5);
    trunc_ln9_fu_151_p4 <= sum_out_dout(36 downto 5);
    trunc_ln_fu_125_p4 <= re_out_dout(36 downto 5);
    zext_ln70_fu_251_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln72_fu_246_p2),32));
end behav;
