-- ==============================================================
-- Generated by Vitis HLS v2024.2.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity system_top_module4_fine_cfo_apply_Pipeline_CFO_ESTIMATE is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    empty : IN STD_LOGIC_VECTOR (12 downto 0);
    C_re_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    C_re_out_ap_vld : OUT STD_LOGIC;
    C_im_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    C_im_out_ap_vld : OUT STD_LOGIC;
    circ_buf_re_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    circ_buf_re_ce0 : OUT STD_LOGIC;
    circ_buf_re_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    circ_buf_re_address1 : OUT STD_LOGIC_VECTOR (12 downto 0);
    circ_buf_re_ce1 : OUT STD_LOGIC;
    circ_buf_re_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    circ_buf_im_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    circ_buf_im_ce0 : OUT STD_LOGIC;
    circ_buf_im_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    circ_buf_im_address1 : OUT STD_LOGIC_VECTOR (12 downto 0);
    circ_buf_im_ce1 : OUT STD_LOGIC;
    circ_buf_im_q1 : IN STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of system_top_module4_fine_cfo_apply_Pipeline_CFO_ESTIMATE is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv7_40 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv8_B8 : STD_LOGIC_VECTOR (7 downto 0) := "10111000";
    constant ap_const_lv9_F8 : STD_LOGIC_VECTOR (8 downto 0) := "011111000";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln156_fu_160_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln156_reg_360 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln156_reg_360_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln156_reg_360_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln161_fu_218_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln161_reg_374 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln162_fu_228_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln162_reg_389 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln162_reg_389_pp0_iter2_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln162_1_fu_232_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln162_2_fu_236_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln162_2_reg_401 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln162_2_reg_401_pp0_iter2_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal sx_im_reg_407 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln163_fu_252_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln160_fu_212_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal C_im_fu_60 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal C_im_1_fu_295_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal C_re_fu_64 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal C_re_1_fu_276_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_fu_68 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal i_6_fu_166_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_sig_allocacmp_i_5 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal circ_buf_re_ce1_local : STD_LOGIC;
    signal circ_buf_re_ce0_local : STD_LOGIC;
    signal circ_buf_im_ce1_local : STD_LOGIC;
    signal circ_buf_im_ce0_local : STD_LOGIC;
    signal zext_ln156_1_fu_176_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln158_fu_180_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln158_fu_186_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln156_fu_172_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln159_fu_196_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln159_fu_202_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal cx_idx_fu_190_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sx_idx_fu_206_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal mul_ln162_1_fu_243_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln162_3_fu_240_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln162_1_fu_243_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln162_1_fu_243_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln163_fu_252_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln163_fu_252_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_319_p3 : STD_LOGIC_VECTOR (32 downto 0);
    signal trunc_ln_fu_263_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal sext_ln162_6_fu_272_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_328_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln1_fu_282_p4 : STD_LOGIC_VECTOR (26 downto 0);
    signal sext_ln163_fu_291_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_319_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_328_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component system_top_mul_16s_16s_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component system_top_mac_muladd_16s_16s_32s_33_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (32 downto 0) );
    end component;


    component system_top_mac_mulsub_16s_16s_32s_32_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component system_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_16s_16s_32_1_1_U209 : component system_top_mul_16s_16s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        din0 => mul_ln162_1_fu_243_p0,
        din1 => mul_ln162_1_fu_243_p1,
        dout => mul_ln162_1_fu_243_p2);

    mul_16s_16s_32_1_1_U210 : component system_top_mul_16s_16s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        din0 => mul_ln163_fu_252_p0,
        din1 => mul_ln163_fu_252_p1,
        dout => mul_ln163_fu_252_p2);

    mac_muladd_16s_16s_32s_33_4_1_U211 : component system_top_mac_muladd_16s_16s_32s_33_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 32,
        dout_WIDTH => 33)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_319_p0,
        din1 => circ_buf_re_q1,
        din2 => mul_ln162_1_fu_243_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_319_p3);

    mac_mulsub_16s_16s_32s_32_4_1_U212 : component system_top_mac_mulsub_16s_16s_32s_32_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_328_p0,
        din1 => circ_buf_im_q1,
        din2 => mul_ln163_fu_252_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_328_p3);

    flow_control_loop_pipe_sequential_init_U : component system_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    C_im_fu_60_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    C_im_fu_60 <= ap_const_lv32_0;
                elsif ((ap_enable_reg_pp0_iter4 = ap_const_logic_1)) then 
                    C_im_fu_60 <= C_im_1_fu_295_p2;
                end if;
            end if; 
        end if;
    end process;

    C_re_fu_64_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    C_re_fu_64 <= ap_const_lv32_0;
                elsif ((ap_enable_reg_pp0_iter4 = ap_const_logic_1)) then 
                    C_re_fu_64 <= C_re_1_fu_276_p2;
                end if;
            end if; 
        end if;
    end process;

    i_fu_68_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln156_fu_160_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_fu_68 <= i_6_fu_166_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_68 <= ap_const_lv7_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                icmp_ln156_reg_360 <= icmp_ln156_fu_160_p2;
                icmp_ln156_reg_360_pp0_iter1_reg <= icmp_ln156_reg_360;
                sext_ln162_2_reg_401 <= sext_ln162_2_fu_236_p1;
                sext_ln162_reg_389 <= sext_ln162_fu_228_p1;
                    zext_ln161_reg_374(12 downto 0) <= zext_ln161_fu_218_p1(12 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                icmp_ln156_reg_360_pp0_iter2_reg <= icmp_ln156_reg_360_pp0_iter1_reg;
                sext_ln162_2_reg_401_pp0_iter2_reg <= sext_ln162_2_reg_401;
                sext_ln162_reg_389_pp0_iter2_reg <= sext_ln162_reg_389;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                sx_im_reg_407 <= circ_buf_im_q0;
            end if;
        end if;
    end process;
    zext_ln161_reg_374(63 downto 13) <= "000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    C_im_1_fu_295_p2 <= std_logic_vector(signed(sext_ln163_fu_291_p1) + signed(C_im_fu_60));
    C_im_out <= C_im_fu_60;

    C_im_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln156_reg_360_pp0_iter2_reg, ap_loop_exit_ready_pp0_iter3_reg)
    begin
        if (((icmp_ln156_reg_360_pp0_iter2_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1))) then 
            C_im_out_ap_vld <= ap_const_logic_1;
        else 
            C_im_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    C_re_1_fu_276_p2 <= std_logic_vector(signed(sext_ln162_6_fu_272_p1) + signed(C_re_fu_64));
    C_re_out <= C_re_fu_64;

    C_re_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln156_reg_360_pp0_iter2_reg, ap_loop_exit_ready_pp0_iter3_reg)
    begin
        if (((icmp_ln156_reg_360_pp0_iter2_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1))) then 
            C_re_out_ap_vld <= ap_const_logic_1;
        else 
            C_re_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    add_ln158_fu_180_p2 <= std_logic_vector(unsigned(zext_ln156_1_fu_176_p1) + unsigned(ap_const_lv8_B8));
    add_ln159_fu_196_p2 <= std_logic_vector(unsigned(zext_ln156_fu_172_p1) + unsigned(ap_const_lv9_F8));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln156_fu_160_p2)
    begin
        if (((icmp_ln156_fu_160_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter3_reg, ap_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_5_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, i_fu_68)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i_5 <= ap_const_lv7_0;
        else 
            ap_sig_allocacmp_i_5 <= i_fu_68;
        end if; 
    end process;

    circ_buf_im_address0 <= zext_ln161_reg_374(13 - 1 downto 0);
    circ_buf_im_address1 <= zext_ln160_fu_212_p1(13 - 1 downto 0);
    circ_buf_im_ce0 <= circ_buf_im_ce0_local;

    circ_buf_im_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            circ_buf_im_ce0_local <= ap_const_logic_1;
        else 
            circ_buf_im_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    circ_buf_im_ce1 <= circ_buf_im_ce1_local;

    circ_buf_im_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            circ_buf_im_ce1_local <= ap_const_logic_1;
        else 
            circ_buf_im_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    circ_buf_re_address0 <= zext_ln161_fu_218_p1(13 - 1 downto 0);
    circ_buf_re_address1 <= zext_ln160_fu_212_p1(13 - 1 downto 0);
    circ_buf_re_ce0 <= circ_buf_re_ce0_local;

    circ_buf_re_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            circ_buf_re_ce0_local <= ap_const_logic_1;
        else 
            circ_buf_re_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    circ_buf_re_ce1 <= circ_buf_re_ce1_local;

    circ_buf_re_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            circ_buf_re_ce1_local <= ap_const_logic_1;
        else 
            circ_buf_re_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    cx_idx_fu_190_p2 <= std_logic_vector(unsigned(zext_ln158_fu_186_p1) + unsigned(empty));
    grp_fu_319_p0 <= sext_ln162_1_fu_232_p1(16 - 1 downto 0);
    grp_fu_328_p0 <= sext_ln162_1_fu_232_p1(16 - 1 downto 0);
    i_6_fu_166_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_5) + unsigned(ap_const_lv7_1));
    icmp_ln156_fu_160_p2 <= "1" when (ap_sig_allocacmp_i_5 = ap_const_lv7_40) else "0";
    mul_ln162_1_fu_243_p0 <= sext_ln162_3_fu_240_p1(16 - 1 downto 0);
    mul_ln162_1_fu_243_p1 <= sext_ln162_2_reg_401_pp0_iter2_reg(16 - 1 downto 0);
    mul_ln163_fu_252_p0 <= sext_ln162_3_fu_240_p1(16 - 1 downto 0);
    mul_ln163_fu_252_p1 <= sext_ln162_reg_389_pp0_iter2_reg(16 - 1 downto 0);
        sext_ln162_1_fu_232_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(circ_buf_re_q0),32));

        sext_ln162_2_fu_236_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(circ_buf_im_q1),32));

        sext_ln162_3_fu_240_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sx_im_reg_407),32));

        sext_ln162_6_fu_272_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln_fu_263_p4),32));

        sext_ln162_fu_228_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(circ_buf_re_q1),32));

        sext_ln163_fu_291_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln1_fu_282_p4),32));

    sx_idx_fu_206_p2 <= std_logic_vector(unsigned(zext_ln159_fu_202_p1) + unsigned(empty));
    trunc_ln1_fu_282_p4 <= grp_fu_328_p3(31 downto 5);
    trunc_ln_fu_263_p4 <= grp_fu_319_p3(32 downto 5);
    zext_ln156_1_fu_176_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_i_5),8));
    zext_ln156_fu_172_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_i_5),9));
    zext_ln158_fu_186_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln158_fu_180_p2),13));
    zext_ln159_fu_202_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln159_fu_196_p2),13));
    zext_ln160_fu_212_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(cx_idx_fu_190_p2),64));
    zext_ln161_fu_218_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sx_idx_fu_206_p2),64));
end behav;
