// ==============================================================
// Generated by Vitis HLS v2024.2.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module system_top_module1_packet_detect_Pipeline_STREAM_LOOP (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m0_to_m1_data_dout,
        m0_to_m1_data_empty_n,
        m0_to_m1_data_read,
        m0_to_m1_data_num_data_valid,
        m0_to_m1_data_fifo_cap,
        m1_to_m2_data_din,
        m1_to_m2_data_full_n,
        m1_to_m2_data_write,
        m1_to_m2_data_num_data_valid,
        m1_to_m2_data_fifo_cap,
        m1_startOffset_din,
        m1_startOffset_full_n,
        m1_startOffset_write,
        m1_startOffset_num_data_valid,
        m1_startOffset_fifo_cap,
        p_read,
        detected_out,
        detected_out_ap_vld,
        startOffset_out,
        startOffset_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] m0_to_m1_data_dout;
input   m0_to_m1_data_empty_n;
output   m0_to_m1_data_read;
input  [6:0] m0_to_m1_data_num_data_valid;
input  [6:0] m0_to_m1_data_fifo_cap;
output  [31:0] m1_to_m2_data_din;
input   m1_to_m2_data_full_n;
output   m1_to_m2_data_write;
input  [31:0] m1_to_m2_data_num_data_valid;
input  [31:0] m1_to_m2_data_fifo_cap;
output  [15:0] m1_startOffset_din;
input   m1_startOffset_full_n;
output   m1_startOffset_write;
input  [31:0] m1_startOffset_num_data_valid;
input  [31:0] m1_startOffset_fifo_cap;
input  [31:0] p_read;
output  [0:0] detected_out;
output   detected_out_ap_vld;
output  [15:0] startOffset_out;
output   startOffset_out_ap_vld;

reg ap_idle;
reg m0_to_m1_data_read;
reg m1_to_m2_data_write;
reg m1_startOffset_write;
reg detected_out_ap_vld;
reg startOffset_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_idle_pp0;
reg   [0:0] icmp_ln51_reg_2992;
reg    ap_block_state2_pp0_stage0_iter1_grp1;
reg   [0:0] icmp_ln51_reg_2992_pp0_iter9_reg;
reg   [0:0] icmp_ln65_reg_3048;
reg   [0:0] icmp_ln65_reg_3048_pp0_iter9_reg;
reg   [0:0] icmp_ln87_reg_3058;
reg   [0:0] icmp_ln87_reg_3058_pp0_iter9_reg;
reg   [0:0] detected_load_1_reg_3223;
reg   [0:0] icmp_ln95_reg_3227;
reg   [0:0] icmp_ln97_reg_3231;
reg    ap_predicate_op512_write_state11;
reg    ap_block_state11_pp0_stage0_iter10_grp1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln51_fu_1004_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    m0_to_m1_data_blk_n;
wire    ap_block_pp0_stage0_grp1;
reg    m1_to_m2_data_blk_n;
reg    m1_startOffset_blk_n;
wire    ap_block_pp0_stage0_11001_grp0;
wire    ap_block_pp0_stage0_subdone_grp0;
reg   [30:0] i_10_reg_2985;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln51_reg_2992_pp0_iter1_reg;
reg   [0:0] icmp_ln51_reg_2992_pp0_iter2_reg;
reg   [0:0] icmp_ln51_reg_2992_pp0_iter3_reg;
reg   [0:0] icmp_ln51_reg_2992_pp0_iter4_reg;
reg   [0:0] icmp_ln51_reg_2992_pp0_iter5_reg;
reg   [0:0] icmp_ln51_reg_2992_pp0_iter6_reg;
reg   [0:0] icmp_ln51_reg_2992_pp0_iter7_reg;
reg   [0:0] icmp_ln51_reg_2992_pp0_iter8_reg;
wire   [3:0] trunc_ln51_fu_1016_p1;
reg   [3:0] trunc_ln51_reg_2996;
reg   [3:0] trunc_ln51_reg_2996_pp0_iter1_reg;
reg   [3:0] trunc_ln51_reg_2996_pp0_iter2_reg;
reg   [3:0] trunc_ln51_reg_2996_pp0_iter3_reg;
reg   [3:0] trunc_ln51_reg_2996_pp0_iter4_reg;
reg   [3:0] trunc_ln51_reg_2996_pp0_iter5_reg;
reg   [3:0] trunc_ln51_reg_2996_pp0_iter6_reg;
wire  signed [15:0] rxD_re_fu_1025_p1;
reg  signed [15:0] rxD_re_reg_3005;
reg    ap_block_pp0_stage0_11001_grp1;
reg  signed [15:0] rxD_im_reg_3026;
reg  signed [15:0] rxD_im_reg_3026_pp0_iter2_reg;
wire   [0:0] icmp_ln65_fu_1048_p2;
reg   [0:0] icmp_ln65_reg_3048_pp0_iter2_reg;
reg   [0:0] icmp_ln65_reg_3048_pp0_iter3_reg;
reg   [0:0] icmp_ln65_reg_3048_pp0_iter4_reg;
reg   [0:0] icmp_ln65_reg_3048_pp0_iter5_reg;
reg   [0:0] icmp_ln65_reg_3048_pp0_iter6_reg;
reg   [0:0] icmp_ln65_reg_3048_pp0_iter7_reg;
reg   [0:0] icmp_ln65_reg_3048_pp0_iter8_reg;
wire  signed [28:0] sext_ln78_fu_1059_p1;
wire   [0:0] icmp_ln87_fu_1063_p2;
reg   [0:0] icmp_ln87_reg_3058_pp0_iter2_reg;
reg   [0:0] icmp_ln87_reg_3058_pp0_iter3_reg;
reg   [0:0] icmp_ln87_reg_3058_pp0_iter4_reg;
reg   [0:0] icmp_ln87_reg_3058_pp0_iter5_reg;
reg   [0:0] icmp_ln87_reg_3058_pp0_iter6_reg;
reg   [0:0] icmp_ln87_reg_3058_pp0_iter7_reg;
reg   [0:0] icmp_ln87_reg_3058_pp0_iter8_reg;
wire   [15:0] trunc_ln93_fu_1069_p1;
reg   [15:0] trunc_ln93_reg_3062;
reg   [15:0] trunc_ln93_reg_3062_pp0_iter2_reg;
reg   [15:0] trunc_ln93_reg_3062_pp0_iter3_reg;
reg   [15:0] trunc_ln93_reg_3062_pp0_iter4_reg;
reg   [15:0] trunc_ln93_reg_3062_pp0_iter5_reg;
reg   [15:0] trunc_ln93_reg_3062_pp0_iter6_reg;
reg   [15:0] trunc_ln93_reg_3062_pp0_iter7_reg;
reg   [15:0] trunc_ln93_reg_3062_pp0_iter8_reg;
wire  signed [15:0] rx_re_fu_1120_p35;
reg  signed [15:0] rx_re_reg_3067;
wire  signed [27:0] sext_ln75_fu_1438_p1;
wire  signed [27:0] sext_ln75_1_fu_1442_p1;
wire  signed [27:0] sext_ln75_3_fu_1449_p1;
wire   [27:0] mul_ln75_1_fu_1452_p2;
reg   [27:0] mul_ln75_1_reg_3088;
reg  signed [27:0] mul_ln75_1_reg_3088_pp0_iter3_reg;
wire   [27:0] mul_ln76_fu_1458_p2;
reg   [27:0] mul_ln76_reg_3093;
reg  signed [27:0] mul_ln76_reg_3093_pp0_iter3_reg;
wire  signed [28:0] sext_ln79_1_fu_1464_p1;
wire  signed [28:0] mul_ln78_1_fu_1471_p2;
wire  signed [28:0] sext_ln79_fu_1477_p1;
wire   [28:0] grp_fu_2330_p3;
reg   [15:0] cp_re_reg_3120;
reg   [15:0] cp_im_reg_3141;
wire   [28:0] grp_fu_2354_p3;
reg   [15:0] ps_reg_3167;
wire  signed [31:0] corrSum_re_1_fu_1524_p2;
reg  signed [31:0] corrSum_re_1_reg_3188;
wire  signed [31:0] corrSum_im_1_fu_1541_p2;
reg  signed [31:0] corrSum_im_1_reg_3193;
wire  signed [31:0] powSumAcc_3_fu_1983_p2;
reg  signed [31:0] powSumAcc_3_reg_3198;
wire   [53:0] mul_ln89_fu_550_p2;
reg   [53:0] mul_ln89_reg_3203;
wire   [53:0] mul_ln89_1_fu_554_p2;
reg   [53:0] mul_ln89_1_reg_3208;
reg   [31:0] tmp_s_reg_3213;
wire   [53:0] mul_ln91_fu_558_p2;
reg   [53:0] mul_ln91_reg_3218;
wire   [0:0] detected_load_1_load_fu_2232_p1;
wire   [0:0] icmp_ln95_fu_2263_p2;
wire   [0:0] icmp_ln97_fu_2280_p2;
wire   [15:0] startOffset_6_fu_2306_p2;
reg   [15:0] startOffset_6_reg_3235;
reg    ap_condition_exit_pp0_iter9_stage0;
reg   [0:0] ap_phi_mux_detected_1_phi_fu_536_p8;
wire   [0:0] ap_phi_reg_pp0_iter9_detected_1_reg_533;
reg   [30:0] i_fu_144;
wire   [30:0] i_11_fu_1010_p2;
wire    ap_loop_init;
reg   [30:0] ap_sig_allocacmp_i_10;
wire    ap_block_pp0_stage0;
reg   [15:0] cp_re_buf_fu_148;
reg   [15:0] cp_re_buf_1_fu_152;
reg   [15:0] cp_re_buf_2_fu_156;
reg   [15:0] cp_re_buf_3_fu_160;
reg   [15:0] cp_re_buf_4_fu_164;
reg   [15:0] cp_re_buf_5_fu_168;
reg   [15:0] cp_re_buf_6_fu_172;
reg   [15:0] cp_re_buf_7_fu_176;
reg   [15:0] cp_re_buf_8_fu_180;
reg   [15:0] cp_re_buf_9_fu_184;
reg   [15:0] cp_re_buf_10_fu_188;
reg   [15:0] cp_re_buf_11_fu_192;
reg   [15:0] cp_re_buf_12_fu_196;
reg   [15:0] cp_re_buf_13_fu_200;
reg   [15:0] cp_re_buf_14_fu_204;
reg   [15:0] cp_re_buf_15_fu_208;
reg   [15:0] cp_im_buf_fu_212;
reg   [15:0] cp_im_buf_1_fu_216;
reg   [15:0] cp_im_buf_2_fu_220;
reg   [15:0] cp_im_buf_3_fu_224;
reg   [15:0] cp_im_buf_4_fu_228;
reg   [15:0] cp_im_buf_5_fu_232;
reg   [15:0] cp_im_buf_6_fu_236;
reg   [15:0] cp_im_buf_7_fu_240;
reg   [15:0] cp_im_buf_8_fu_244;
reg   [15:0] cp_im_buf_9_fu_248;
reg   [15:0] cp_im_buf_10_fu_252;
reg   [15:0] cp_im_buf_11_fu_256;
reg   [15:0] cp_im_buf_12_fu_260;
reg   [15:0] cp_im_buf_13_fu_264;
reg   [15:0] cp_im_buf_14_fu_268;
reg   [15:0] cp_im_buf_15_fu_272;
reg   [15:0] ps_buf_fu_276;
reg   [15:0] ps_buf_1_fu_280;
reg   [15:0] ps_buf_2_fu_284;
reg   [15:0] ps_buf_3_fu_288;
reg   [15:0] ps_buf_4_fu_292;
reg   [15:0] ps_buf_5_fu_296;
reg   [15:0] ps_buf_6_fu_300;
reg   [15:0] ps_buf_7_fu_304;
reg   [15:0] ps_buf_8_fu_308;
reg   [15:0] ps_buf_9_fu_312;
reg   [15:0] ps_buf_10_fu_316;
reg   [15:0] ps_buf_11_fu_320;
reg   [15:0] ps_buf_12_fu_324;
reg   [15:0] ps_buf_13_fu_328;
reg   [15:0] ps_buf_14_fu_332;
reg   [15:0] ps_buf_15_fu_336;
reg   [15:0] startOffset_fu_340;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg   [31:0] sustainedCount_fu_344;
wire   [31:0] sustainedCount_3_fu_2274_p2;
reg   [0:0] detected_fu_348;
reg   [31:0] powSumAcc_fu_352;
wire   [31:0] powSumAcc_2_fu_2135_p2;
reg   [31:0] corrSum_im_fu_356;
wire   [31:0] corrSum_im_2_fu_1825_p2;
reg   [31:0] corrSum_re_fu_360;
wire   [31:0] corrSum_re_2_fu_1736_p2;
reg   [15:0] delay_line_im_15_fu_364;
reg    ap_predicate_pred1327_state3;
reg   [15:0] delay_line_im_14_fu_368;
reg    ap_predicate_pred1337_state3;
reg   [15:0] delay_line_im_13_fu_372;
reg    ap_predicate_pred1346_state3;
reg   [15:0] delay_line_im_12_fu_376;
reg    ap_predicate_pred1355_state3;
reg   [15:0] delay_line_im_11_fu_380;
reg    ap_predicate_pred1364_state3;
reg   [15:0] delay_line_im_10_fu_384;
reg    ap_predicate_pred1373_state3;
reg   [15:0] delay_line_im_9_fu_388;
reg    ap_predicate_pred1382_state3;
reg   [15:0] delay_line_im_8_fu_392;
reg    ap_predicate_pred1391_state3;
reg   [15:0] delay_line_im_7_fu_396;
reg    ap_predicate_pred1400_state3;
reg   [15:0] delay_line_im_6_fu_400;
reg    ap_predicate_pred1409_state3;
reg   [15:0] delay_line_im_5_fu_404;
reg    ap_predicate_pred1418_state3;
reg   [15:0] delay_line_im_4_fu_408;
reg    ap_predicate_pred1427_state3;
reg   [15:0] delay_line_im_3_fu_412;
reg    ap_predicate_pred1436_state3;
reg   [15:0] delay_line_im_2_fu_416;
reg    ap_predicate_pred1445_state3;
reg   [15:0] delay_line_im_1_fu_420;
reg    ap_predicate_pred1454_state3;
reg   [15:0] delay_line_im_fu_424;
reg    ap_predicate_pred1463_state3;
reg   [15:0] delay_line_re_15_fu_428;
reg   [15:0] delay_line_re_14_fu_432;
reg   [15:0] delay_line_re_13_fu_436;
reg   [15:0] delay_line_re_12_fu_440;
reg   [15:0] delay_line_re_11_fu_444;
reg   [15:0] delay_line_re_10_fu_448;
reg   [15:0] delay_line_re_9_fu_452;
reg   [15:0] delay_line_re_8_fu_456;
reg   [15:0] delay_line_re_7_fu_460;
reg   [15:0] delay_line_re_6_fu_464;
reg   [15:0] delay_line_re_5_fu_468;
reg   [15:0] delay_line_re_4_fu_472;
reg   [15:0] delay_line_re_3_fu_476;
reg   [15:0] delay_line_re_2_fu_480;
reg   [15:0] delay_line_re_1_fu_484;
reg   [15:0] delay_line_re_fu_488;
reg    ap_block_pp0_stage0_01001_grp1;
wire  signed [31:0] mul_ln89_fu_550_p0;
wire  signed [53:0] sext_ln89_fu_1994_p1;
wire  signed [31:0] mul_ln89_fu_550_p1;
wire  signed [31:0] mul_ln89_1_fu_554_p0;
wire  signed [53:0] sext_ln89_1_fu_1999_p1;
wire  signed [31:0] mul_ln89_1_fu_554_p1;
wire  signed [31:0] mul_ln91_fu_558_p0;
wire  signed [53:0] sext_ln91_fu_2224_p1;
wire  signed [31:0] mul_ln91_fu_558_p1;
wire   [31:0] zext_ln51_fu_1000_p1;
wire   [26:0] tmp_fu_1039_p4;
wire   [30:0] n_fu_1054_p2;
wire   [15:0] rx_re_fu_1120_p33;
wire   [15:0] rx_im_fu_1239_p33;
wire  signed [15:0] rx_im_fu_1239_p35;
wire  signed [15:0] mul_ln75_1_fu_1452_p0;
wire  signed [27:0] sext_ln75_2_fu_1445_p1;
wire  signed [15:0] mul_ln75_1_fu_1452_p1;
wire  signed [15:0] mul_ln76_fu_1458_p0;
wire  signed [15:0] mul_ln76_fu_1458_p1;
wire  signed [15:0] mul_ln78_1_fu_1471_p0;
wire  signed [28:0] sext_ln78_1_fu_1468_p1;
wire  signed [15:0] mul_ln78_1_fu_1471_p1;
wire  signed [27:0] grp_fu_2338_p3;
wire  signed [27:0] grp_fu_2346_p3;
wire  signed [28:0] ps_fu_1504_p1;
wire   [28:0] grp_fu_2362_p3;
wire   [25:0] shl_ln_fu_1513_p3;
wire  signed [31:0] sext_ln82_fu_1520_p1;
wire   [25:0] shl_ln7_fu_1530_p3;
wire  signed [31:0] sext_ln83_fu_1537_p1;
wire   [15:0] tmp_22_i_fu_1653_p33;
wire   [15:0] tmp_22_i_fu_1653_p35;
wire   [25:0] shl_ln9_fu_1724_p3;
wire  signed [31:0] sext_ln110_fu_1732_p1;
wire   [15:0] tmp_23_i_fu_1742_p33;
wire   [15:0] tmp_23_i_fu_1742_p35;
wire   [25:0] shl_ln1_fu_1813_p3;
wire  signed [31:0] sext_ln111_fu_1821_p1;
wire   [25:0] shl_ln8_fu_1972_p3;
wire  signed [31:0] sext_ln84_fu_1979_p1;
wire   [15:0] tmp_24_i_fu_2052_p33;
wire   [15:0] tmp_24_i_fu_2052_p35;
wire   [25:0] shl_ln2_fu_2123_p3;
wire  signed [31:0] sext_ln112_fu_2131_p1;
wire   [53:0] add_ln89_fu_2210_p2;
wire   [31:0] tmp_1_fu_2242_p4;
wire   [52:0] and_ln95_1_fu_2251_p3;
wire  signed [53:0] sext_ln95_fu_2259_p1;
wire   [53:0] and_ln_fu_2235_p3;
wire   [15:0] empty_fu_2291_p1;
wire   [15:0] xor_ln98_fu_2295_p2;
wire   [15:0] add_ln98_fu_2301_p2;
wire  signed [15:0] grp_fu_2330_p0;
wire  signed [15:0] grp_fu_2330_p1;
wire  signed [15:0] grp_fu_2338_p0;
wire  signed [15:0] grp_fu_2338_p1;
wire  signed [15:0] grp_fu_2346_p0;
wire  signed [15:0] grp_fu_2346_p1;
wire  signed [15:0] grp_fu_2354_p0;
wire  signed [15:0] grp_fu_2354_p1;
wire  signed [15:0] grp_fu_2362_p0;
wire  signed [15:0] grp_fu_2362_p1;
reg    grp_fu_2330_ce;
reg    grp_fu_2338_ce;
reg    grp_fu_2346_ce;
reg    grp_fu_2354_ce;
reg    grp_fu_2362_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_2086;
reg    ap_condition_2090;
reg    ap_condition_2094;
reg    ap_condition_2098;
reg    ap_condition_2102;
reg    ap_condition_2106;
reg    ap_condition_2110;
reg    ap_condition_2114;
reg    ap_condition_2118;
reg    ap_condition_2122;
reg    ap_condition_2126;
reg    ap_condition_2130;
reg    ap_condition_2134;
reg    ap_condition_2138;
reg    ap_condition_2142;
reg    ap_condition_2146;
reg    ap_condition_2150;
reg    ap_condition_2154;
reg    ap_condition_2174;
reg    ap_condition_2179;
reg    ap_condition_2183;
reg    ap_condition_2187;
reg    ap_condition_2191;
reg    ap_condition_2195;
reg    ap_condition_2199;
reg    ap_condition_2203;
reg    ap_condition_2207;
reg    ap_condition_2211;
reg    ap_condition_2215;
reg    ap_condition_2219;
reg    ap_condition_2223;
reg    ap_condition_2227;
reg    ap_condition_2231;
reg    ap_condition_2235;
reg    ap_condition_2239;
reg    ap_condition_2243;
reg    ap_condition_2247;
reg    ap_condition_2254;
wire   [3:0] rx_re_fu_1120_p1;
wire   [3:0] rx_re_fu_1120_p3;
wire   [3:0] rx_re_fu_1120_p5;
wire   [3:0] rx_re_fu_1120_p7;
wire   [3:0] rx_re_fu_1120_p9;
wire   [3:0] rx_re_fu_1120_p11;
wire   [3:0] rx_re_fu_1120_p13;
wire   [3:0] rx_re_fu_1120_p15;
wire  signed [3:0] rx_re_fu_1120_p17;
wire  signed [3:0] rx_re_fu_1120_p19;
wire  signed [3:0] rx_re_fu_1120_p21;
wire  signed [3:0] rx_re_fu_1120_p23;
wire  signed [3:0] rx_re_fu_1120_p25;
wire  signed [3:0] rx_re_fu_1120_p27;
wire  signed [3:0] rx_re_fu_1120_p29;
wire  signed [3:0] rx_re_fu_1120_p31;
wire   [3:0] rx_im_fu_1239_p1;
wire   [3:0] rx_im_fu_1239_p3;
wire   [3:0] rx_im_fu_1239_p5;
wire   [3:0] rx_im_fu_1239_p7;
wire   [3:0] rx_im_fu_1239_p9;
wire   [3:0] rx_im_fu_1239_p11;
wire   [3:0] rx_im_fu_1239_p13;
wire   [3:0] rx_im_fu_1239_p15;
wire  signed [3:0] rx_im_fu_1239_p17;
wire  signed [3:0] rx_im_fu_1239_p19;
wire  signed [3:0] rx_im_fu_1239_p21;
wire  signed [3:0] rx_im_fu_1239_p23;
wire  signed [3:0] rx_im_fu_1239_p25;
wire  signed [3:0] rx_im_fu_1239_p27;
wire  signed [3:0] rx_im_fu_1239_p29;
wire  signed [3:0] rx_im_fu_1239_p31;
wire  signed [3:0] tmp_22_i_fu_1653_p1;
wire   [3:0] tmp_22_i_fu_1653_p3;
wire   [3:0] tmp_22_i_fu_1653_p5;
wire   [3:0] tmp_22_i_fu_1653_p7;
wire   [3:0] tmp_22_i_fu_1653_p9;
wire   [3:0] tmp_22_i_fu_1653_p11;
wire   [3:0] tmp_22_i_fu_1653_p13;
wire   [3:0] tmp_22_i_fu_1653_p15;
wire   [3:0] tmp_22_i_fu_1653_p17;
wire  signed [3:0] tmp_22_i_fu_1653_p19;
wire  signed [3:0] tmp_22_i_fu_1653_p21;
wire  signed [3:0] tmp_22_i_fu_1653_p23;
wire  signed [3:0] tmp_22_i_fu_1653_p25;
wire  signed [3:0] tmp_22_i_fu_1653_p27;
wire  signed [3:0] tmp_22_i_fu_1653_p29;
wire  signed [3:0] tmp_22_i_fu_1653_p31;
wire  signed [3:0] tmp_23_i_fu_1742_p1;
wire   [3:0] tmp_23_i_fu_1742_p3;
wire   [3:0] tmp_23_i_fu_1742_p5;
wire   [3:0] tmp_23_i_fu_1742_p7;
wire   [3:0] tmp_23_i_fu_1742_p9;
wire   [3:0] tmp_23_i_fu_1742_p11;
wire   [3:0] tmp_23_i_fu_1742_p13;
wire   [3:0] tmp_23_i_fu_1742_p15;
wire   [3:0] tmp_23_i_fu_1742_p17;
wire  signed [3:0] tmp_23_i_fu_1742_p19;
wire  signed [3:0] tmp_23_i_fu_1742_p21;
wire  signed [3:0] tmp_23_i_fu_1742_p23;
wire  signed [3:0] tmp_23_i_fu_1742_p25;
wire  signed [3:0] tmp_23_i_fu_1742_p27;
wire  signed [3:0] tmp_23_i_fu_1742_p29;
wire  signed [3:0] tmp_23_i_fu_1742_p31;
wire  signed [3:0] tmp_24_i_fu_2052_p1;
wire   [3:0] tmp_24_i_fu_2052_p3;
wire   [3:0] tmp_24_i_fu_2052_p5;
wire   [3:0] tmp_24_i_fu_2052_p7;
wire   [3:0] tmp_24_i_fu_2052_p9;
wire   [3:0] tmp_24_i_fu_2052_p11;
wire   [3:0] tmp_24_i_fu_2052_p13;
wire   [3:0] tmp_24_i_fu_2052_p15;
wire   [3:0] tmp_24_i_fu_2052_p17;
wire  signed [3:0] tmp_24_i_fu_2052_p19;
wire  signed [3:0] tmp_24_i_fu_2052_p21;
wire  signed [3:0] tmp_24_i_fu_2052_p23;
wire  signed [3:0] tmp_24_i_fu_2052_p25;
wire  signed [3:0] tmp_24_i_fu_2052_p27;
wire  signed [3:0] tmp_24_i_fu_2052_p29;
wire  signed [3:0] tmp_24_i_fu_2052_p31;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 i_fu_144 = 31'd0;
#0 cp_re_buf_fu_148 = 16'd0;
#0 cp_re_buf_1_fu_152 = 16'd0;
#0 cp_re_buf_2_fu_156 = 16'd0;
#0 cp_re_buf_3_fu_160 = 16'd0;
#0 cp_re_buf_4_fu_164 = 16'd0;
#0 cp_re_buf_5_fu_168 = 16'd0;
#0 cp_re_buf_6_fu_172 = 16'd0;
#0 cp_re_buf_7_fu_176 = 16'd0;
#0 cp_re_buf_8_fu_180 = 16'd0;
#0 cp_re_buf_9_fu_184 = 16'd0;
#0 cp_re_buf_10_fu_188 = 16'd0;
#0 cp_re_buf_11_fu_192 = 16'd0;
#0 cp_re_buf_12_fu_196 = 16'd0;
#0 cp_re_buf_13_fu_200 = 16'd0;
#0 cp_re_buf_14_fu_204 = 16'd0;
#0 cp_re_buf_15_fu_208 = 16'd0;
#0 cp_im_buf_fu_212 = 16'd0;
#0 cp_im_buf_1_fu_216 = 16'd0;
#0 cp_im_buf_2_fu_220 = 16'd0;
#0 cp_im_buf_3_fu_224 = 16'd0;
#0 cp_im_buf_4_fu_228 = 16'd0;
#0 cp_im_buf_5_fu_232 = 16'd0;
#0 cp_im_buf_6_fu_236 = 16'd0;
#0 cp_im_buf_7_fu_240 = 16'd0;
#0 cp_im_buf_8_fu_244 = 16'd0;
#0 cp_im_buf_9_fu_248 = 16'd0;
#0 cp_im_buf_10_fu_252 = 16'd0;
#0 cp_im_buf_11_fu_256 = 16'd0;
#0 cp_im_buf_12_fu_260 = 16'd0;
#0 cp_im_buf_13_fu_264 = 16'd0;
#0 cp_im_buf_14_fu_268 = 16'd0;
#0 cp_im_buf_15_fu_272 = 16'd0;
#0 ps_buf_fu_276 = 16'd0;
#0 ps_buf_1_fu_280 = 16'd0;
#0 ps_buf_2_fu_284 = 16'd0;
#0 ps_buf_3_fu_288 = 16'd0;
#0 ps_buf_4_fu_292 = 16'd0;
#0 ps_buf_5_fu_296 = 16'd0;
#0 ps_buf_6_fu_300 = 16'd0;
#0 ps_buf_7_fu_304 = 16'd0;
#0 ps_buf_8_fu_308 = 16'd0;
#0 ps_buf_9_fu_312 = 16'd0;
#0 ps_buf_10_fu_316 = 16'd0;
#0 ps_buf_11_fu_320 = 16'd0;
#0 ps_buf_12_fu_324 = 16'd0;
#0 ps_buf_13_fu_328 = 16'd0;
#0 ps_buf_14_fu_332 = 16'd0;
#0 ps_buf_15_fu_336 = 16'd0;
#0 startOffset_fu_340 = 16'd0;
#0 sustainedCount_fu_344 = 32'd0;
#0 detected_fu_348 = 1'd0;
#0 powSumAcc_fu_352 = 32'd0;
#0 corrSum_im_fu_356 = 32'd0;
#0 corrSum_re_fu_360 = 32'd0;
#0 delay_line_im_15_fu_364 = 16'd0;
#0 delay_line_im_14_fu_368 = 16'd0;
#0 delay_line_im_13_fu_372 = 16'd0;
#0 delay_line_im_12_fu_376 = 16'd0;
#0 delay_line_im_11_fu_380 = 16'd0;
#0 delay_line_im_10_fu_384 = 16'd0;
#0 delay_line_im_9_fu_388 = 16'd0;
#0 delay_line_im_8_fu_392 = 16'd0;
#0 delay_line_im_7_fu_396 = 16'd0;
#0 delay_line_im_6_fu_400 = 16'd0;
#0 delay_line_im_5_fu_404 = 16'd0;
#0 delay_line_im_4_fu_408 = 16'd0;
#0 delay_line_im_3_fu_412 = 16'd0;
#0 delay_line_im_2_fu_416 = 16'd0;
#0 delay_line_im_1_fu_420 = 16'd0;
#0 delay_line_im_fu_424 = 16'd0;
#0 delay_line_re_15_fu_428 = 16'd0;
#0 delay_line_re_14_fu_432 = 16'd0;
#0 delay_line_re_13_fu_436 = 16'd0;
#0 delay_line_re_12_fu_440 = 16'd0;
#0 delay_line_re_11_fu_444 = 16'd0;
#0 delay_line_re_10_fu_448 = 16'd0;
#0 delay_line_re_9_fu_452 = 16'd0;
#0 delay_line_re_8_fu_456 = 16'd0;
#0 delay_line_re_7_fu_460 = 16'd0;
#0 delay_line_re_6_fu_464 = 16'd0;
#0 delay_line_re_5_fu_468 = 16'd0;
#0 delay_line_re_4_fu_472 = 16'd0;
#0 delay_line_re_3_fu_476 = 16'd0;
#0 delay_line_re_2_fu_480 = 16'd0;
#0 delay_line_re_1_fu_484 = 16'd0;
#0 delay_line_re_fu_488 = 16'd0;
#0 ap_done_reg = 1'b0;
end

system_top_mul_32s_32s_54_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 54 ))
mul_32s_32s_54_1_1_U67(
    .din0(mul_ln89_fu_550_p0),
    .din1(mul_ln89_fu_550_p1),
    .dout(mul_ln89_fu_550_p2)
);

system_top_mul_32s_32s_54_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 54 ))
mul_32s_32s_54_1_1_U68(
    .din0(mul_ln89_1_fu_554_p0),
    .din1(mul_ln89_1_fu_554_p1),
    .dout(mul_ln89_1_fu_554_p2)
);

system_top_mul_32s_32s_54_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 54 ))
mul_32s_32s_54_1_1_U69(
    .din0(mul_ln91_fu_558_p0),
    .din1(mul_ln91_fu_558_p1),
    .dout(mul_ln91_fu_558_p2)
);

(* dissolve_hierarchy = "yes" *) system_top_sparsemux_33_4_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 4'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 4'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 4'h3 ),
    .din3_WIDTH( 16 ),
    .CASE4( 4'h4 ),
    .din4_WIDTH( 16 ),
    .CASE5( 4'h5 ),
    .din5_WIDTH( 16 ),
    .CASE6( 4'h6 ),
    .din6_WIDTH( 16 ),
    .CASE7( 4'h7 ),
    .din7_WIDTH( 16 ),
    .CASE8( 4'h8 ),
    .din8_WIDTH( 16 ),
    .CASE9( 4'h9 ),
    .din9_WIDTH( 16 ),
    .CASE10( 4'hA ),
    .din10_WIDTH( 16 ),
    .CASE11( 4'hB ),
    .din11_WIDTH( 16 ),
    .CASE12( 4'hC ),
    .din12_WIDTH( 16 ),
    .CASE13( 4'hD ),
    .din13_WIDTH( 16 ),
    .CASE14( 4'hE ),
    .din14_WIDTH( 16 ),
    .CASE15( 4'hF ),
    .din15_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 16 ))
sparsemux_33_4_16_1_1_U70(
    .din0(delay_line_re_fu_488),
    .din1(delay_line_re_1_fu_484),
    .din2(delay_line_re_2_fu_480),
    .din3(delay_line_re_3_fu_476),
    .din4(delay_line_re_4_fu_472),
    .din5(delay_line_re_5_fu_468),
    .din6(delay_line_re_6_fu_464),
    .din7(delay_line_re_7_fu_460),
    .din8(delay_line_re_8_fu_456),
    .din9(delay_line_re_9_fu_452),
    .din10(delay_line_re_10_fu_448),
    .din11(delay_line_re_11_fu_444),
    .din12(delay_line_re_12_fu_440),
    .din13(delay_line_re_13_fu_436),
    .din14(delay_line_re_14_fu_432),
    .din15(delay_line_re_15_fu_428),
    .def(rx_re_fu_1120_p33),
    .sel(trunc_ln51_reg_2996_pp0_iter1_reg),
    .dout(rx_re_fu_1120_p35)
);

(* dissolve_hierarchy = "yes" *) system_top_sparsemux_33_4_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 4'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 4'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 4'h3 ),
    .din3_WIDTH( 16 ),
    .CASE4( 4'h4 ),
    .din4_WIDTH( 16 ),
    .CASE5( 4'h5 ),
    .din5_WIDTH( 16 ),
    .CASE6( 4'h6 ),
    .din6_WIDTH( 16 ),
    .CASE7( 4'h7 ),
    .din7_WIDTH( 16 ),
    .CASE8( 4'h8 ),
    .din8_WIDTH( 16 ),
    .CASE9( 4'h9 ),
    .din9_WIDTH( 16 ),
    .CASE10( 4'hA ),
    .din10_WIDTH( 16 ),
    .CASE11( 4'hB ),
    .din11_WIDTH( 16 ),
    .CASE12( 4'hC ),
    .din12_WIDTH( 16 ),
    .CASE13( 4'hD ),
    .din13_WIDTH( 16 ),
    .CASE14( 4'hE ),
    .din14_WIDTH( 16 ),
    .CASE15( 4'hF ),
    .din15_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 16 ))
sparsemux_33_4_16_1_1_U71(
    .din0(delay_line_im_fu_424),
    .din1(delay_line_im_1_fu_420),
    .din2(delay_line_im_2_fu_416),
    .din3(delay_line_im_3_fu_412),
    .din4(delay_line_im_4_fu_408),
    .din5(delay_line_im_5_fu_404),
    .din6(delay_line_im_6_fu_400),
    .din7(delay_line_im_7_fu_396),
    .din8(delay_line_im_8_fu_392),
    .din9(delay_line_im_9_fu_388),
    .din10(delay_line_im_10_fu_384),
    .din11(delay_line_im_11_fu_380),
    .din12(delay_line_im_12_fu_376),
    .din13(delay_line_im_13_fu_372),
    .din14(delay_line_im_14_fu_368),
    .din15(delay_line_im_15_fu_364),
    .def(rx_im_fu_1239_p33),
    .sel(trunc_ln51_reg_2996_pp0_iter1_reg),
    .dout(rx_im_fu_1239_p35)
);

system_top_mul_16s_16s_28_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 28 ))
mul_16s_16s_28_1_1_U72(
    .din0(mul_ln75_1_fu_1452_p0),
    .din1(mul_ln75_1_fu_1452_p1),
    .dout(mul_ln75_1_fu_1452_p2)
);

system_top_mul_16s_16s_28_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 28 ))
mul_16s_16s_28_1_1_U73(
    .din0(mul_ln76_fu_1458_p0),
    .din1(mul_ln76_fu_1458_p1),
    .dout(mul_ln76_fu_1458_p2)
);

system_top_mul_16s_16s_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 29 ))
mul_16s_16s_29_1_1_U74(
    .din0(mul_ln78_1_fu_1471_p0),
    .din1(mul_ln78_1_fu_1471_p1),
    .dout(mul_ln78_1_fu_1471_p2)
);

(* dissolve_hierarchy = "yes" *) system_top_sparsemux_33_4_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'hF ),
    .din0_WIDTH( 16 ),
    .CASE1( 4'h0 ),
    .din1_WIDTH( 16 ),
    .CASE2( 4'h1 ),
    .din2_WIDTH( 16 ),
    .CASE3( 4'h2 ),
    .din3_WIDTH( 16 ),
    .CASE4( 4'h3 ),
    .din4_WIDTH( 16 ),
    .CASE5( 4'h4 ),
    .din5_WIDTH( 16 ),
    .CASE6( 4'h5 ),
    .din6_WIDTH( 16 ),
    .CASE7( 4'h6 ),
    .din7_WIDTH( 16 ),
    .CASE8( 4'h7 ),
    .din8_WIDTH( 16 ),
    .CASE9( 4'h8 ),
    .din9_WIDTH( 16 ),
    .CASE10( 4'h9 ),
    .din10_WIDTH( 16 ),
    .CASE11( 4'hA ),
    .din11_WIDTH( 16 ),
    .CASE12( 4'hB ),
    .din12_WIDTH( 16 ),
    .CASE13( 4'hC ),
    .din13_WIDTH( 16 ),
    .CASE14( 4'hD ),
    .din14_WIDTH( 16 ),
    .CASE15( 4'hE ),
    .din15_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 16 ))
sparsemux_33_4_16_1_1_U75(
    .din0(cp_re_buf_fu_148),
    .din1(cp_re_buf_1_fu_152),
    .din2(cp_re_buf_2_fu_156),
    .din3(cp_re_buf_3_fu_160),
    .din4(cp_re_buf_4_fu_164),
    .din5(cp_re_buf_5_fu_168),
    .din6(cp_re_buf_6_fu_172),
    .din7(cp_re_buf_7_fu_176),
    .din8(cp_re_buf_8_fu_180),
    .din9(cp_re_buf_9_fu_184),
    .din10(cp_re_buf_10_fu_188),
    .din11(cp_re_buf_11_fu_192),
    .din12(cp_re_buf_12_fu_196),
    .din13(cp_re_buf_13_fu_200),
    .din14(cp_re_buf_14_fu_204),
    .din15(cp_re_buf_15_fu_208),
    .def(tmp_22_i_fu_1653_p33),
    .sel(trunc_ln51_reg_2996_pp0_iter5_reg),
    .dout(tmp_22_i_fu_1653_p35)
);

(* dissolve_hierarchy = "yes" *) system_top_sparsemux_33_4_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'hF ),
    .din0_WIDTH( 16 ),
    .CASE1( 4'h0 ),
    .din1_WIDTH( 16 ),
    .CASE2( 4'h1 ),
    .din2_WIDTH( 16 ),
    .CASE3( 4'h2 ),
    .din3_WIDTH( 16 ),
    .CASE4( 4'h3 ),
    .din4_WIDTH( 16 ),
    .CASE5( 4'h4 ),
    .din5_WIDTH( 16 ),
    .CASE6( 4'h5 ),
    .din6_WIDTH( 16 ),
    .CASE7( 4'h6 ),
    .din7_WIDTH( 16 ),
    .CASE8( 4'h7 ),
    .din8_WIDTH( 16 ),
    .CASE9( 4'h8 ),
    .din9_WIDTH( 16 ),
    .CASE10( 4'h9 ),
    .din10_WIDTH( 16 ),
    .CASE11( 4'hA ),
    .din11_WIDTH( 16 ),
    .CASE12( 4'hB ),
    .din12_WIDTH( 16 ),
    .CASE13( 4'hC ),
    .din13_WIDTH( 16 ),
    .CASE14( 4'hD ),
    .din14_WIDTH( 16 ),
    .CASE15( 4'hE ),
    .din15_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 16 ))
sparsemux_33_4_16_1_1_U76(
    .din0(cp_im_buf_fu_212),
    .din1(cp_im_buf_1_fu_216),
    .din2(cp_im_buf_2_fu_220),
    .din3(cp_im_buf_3_fu_224),
    .din4(cp_im_buf_4_fu_228),
    .din5(cp_im_buf_5_fu_232),
    .din6(cp_im_buf_6_fu_236),
    .din7(cp_im_buf_7_fu_240),
    .din8(cp_im_buf_8_fu_244),
    .din9(cp_im_buf_9_fu_248),
    .din10(cp_im_buf_10_fu_252),
    .din11(cp_im_buf_11_fu_256),
    .din12(cp_im_buf_12_fu_260),
    .din13(cp_im_buf_13_fu_264),
    .din14(cp_im_buf_14_fu_268),
    .din15(cp_im_buf_15_fu_272),
    .def(tmp_23_i_fu_1742_p33),
    .sel(trunc_ln51_reg_2996_pp0_iter5_reg),
    .dout(tmp_23_i_fu_1742_p35)
);

(* dissolve_hierarchy = "yes" *) system_top_sparsemux_33_4_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'hF ),
    .din0_WIDTH( 16 ),
    .CASE1( 4'h0 ),
    .din1_WIDTH( 16 ),
    .CASE2( 4'h1 ),
    .din2_WIDTH( 16 ),
    .CASE3( 4'h2 ),
    .din3_WIDTH( 16 ),
    .CASE4( 4'h3 ),
    .din4_WIDTH( 16 ),
    .CASE5( 4'h4 ),
    .din5_WIDTH( 16 ),
    .CASE6( 4'h5 ),
    .din6_WIDTH( 16 ),
    .CASE7( 4'h6 ),
    .din7_WIDTH( 16 ),
    .CASE8( 4'h7 ),
    .din8_WIDTH( 16 ),
    .CASE9( 4'h8 ),
    .din9_WIDTH( 16 ),
    .CASE10( 4'h9 ),
    .din10_WIDTH( 16 ),
    .CASE11( 4'hA ),
    .din11_WIDTH( 16 ),
    .CASE12( 4'hB ),
    .din12_WIDTH( 16 ),
    .CASE13( 4'hC ),
    .din13_WIDTH( 16 ),
    .CASE14( 4'hD ),
    .din14_WIDTH( 16 ),
    .CASE15( 4'hE ),
    .din15_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 16 ))
sparsemux_33_4_16_1_1_U77(
    .din0(ps_buf_fu_276),
    .din1(ps_buf_1_fu_280),
    .din2(ps_buf_2_fu_284),
    .din3(ps_buf_3_fu_288),
    .din4(ps_buf_4_fu_292),
    .din5(ps_buf_5_fu_296),
    .din6(ps_buf_6_fu_300),
    .din7(ps_buf_7_fu_304),
    .din8(ps_buf_8_fu_308),
    .din9(ps_buf_9_fu_312),
    .din10(ps_buf_10_fu_316),
    .din11(ps_buf_11_fu_320),
    .din12(ps_buf_12_fu_324),
    .din13(ps_buf_13_fu_328),
    .din14(ps_buf_14_fu_332),
    .din15(ps_buf_15_fu_336),
    .def(tmp_24_i_fu_2052_p33),
    .sel(trunc_ln51_reg_2996_pp0_iter6_reg),
    .dout(tmp_24_i_fu_2052_p35)
);

system_top_mac_muladd_16s_16s_29s_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
mac_muladd_16s_16s_29s_29_4_1_U78(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_2330_p0),
    .din1(grp_fu_2330_p1),
    .din2(mul_ln78_1_fu_1471_p2),
    .ce(grp_fu_2330_ce),
    .dout(grp_fu_2330_p3)
);

system_top_mac_muladd_16s_16s_28s_28_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 28 ),
    .dout_WIDTH( 28 ))
mac_muladd_16s_16s_28s_28_4_1_U79(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_2338_p0),
    .din1(grp_fu_2338_p1),
    .din2(mul_ln75_1_reg_3088_pp0_iter3_reg),
    .ce(grp_fu_2338_ce),
    .dout(grp_fu_2338_p3)
);

system_top_mac_mulsub_16s_16s_28s_28_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 28 ),
    .dout_WIDTH( 28 ))
mac_mulsub_16s_16s_28s_28_4_1_U80(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_2346_p0),
    .din1(grp_fu_2346_p1),
    .din2(mul_ln76_reg_3093_pp0_iter3_reg),
    .ce(grp_fu_2346_ce),
    .dout(grp_fu_2346_p3)
);

system_top_mac_muladd_16s_16s_29ns_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
mac_muladd_16s_16s_29ns_29_4_1_U81(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_2354_p0),
    .din1(grp_fu_2354_p1),
    .din2(grp_fu_2330_p3),
    .ce(grp_fu_2354_ce),
    .dout(grp_fu_2354_p3)
);

system_top_mac_muladd_16s_16s_29ns_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
mac_muladd_16s_16s_29ns_29_4_1_U82(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_2362_p0),
    .din1(grp_fu_2362_p1),
    .din2(grp_fu_2354_p3),
    .ce(grp_fu_2362_ce),
    .dout(grp_fu_2362_p3)
);

system_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter9_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter9_stage0)) begin
            ap_enable_reg_pp0_iter10 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            corrSum_im_fu_356 <= 32'd0;
        end else if ((1'b1 == ap_condition_2090)) begin
            corrSum_im_fu_356 <= corrSum_im_2_fu_1825_p2;
        end else if ((1'b1 == ap_condition_2086)) begin
            corrSum_im_fu_356 <= corrSum_im_1_fu_1541_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            corrSum_re_fu_360 <= 32'd0;
        end else if ((1'b1 == ap_condition_2090)) begin
            corrSum_re_fu_360 <= corrSum_re_2_fu_1736_p2;
        end else if ((1'b1 == ap_condition_2086)) begin
            corrSum_re_fu_360 <= corrSum_re_1_fu_1524_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            cp_im_buf_10_fu_252 <= 16'd0;
        end else if ((1'b1 == ap_condition_2094)) begin
            cp_im_buf_10_fu_252 <= cp_im_reg_3141;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            cp_im_buf_11_fu_256 <= 16'd0;
        end else if ((1'b1 == ap_condition_2098)) begin
            cp_im_buf_11_fu_256 <= cp_im_reg_3141;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            cp_im_buf_12_fu_260 <= 16'd0;
        end else if ((1'b1 == ap_condition_2102)) begin
            cp_im_buf_12_fu_260 <= cp_im_reg_3141;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            cp_im_buf_13_fu_264 <= 16'd0;
        end else if ((1'b1 == ap_condition_2106)) begin
            cp_im_buf_13_fu_264 <= cp_im_reg_3141;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            cp_im_buf_14_fu_268 <= 16'd0;
        end else if ((1'b1 == ap_condition_2110)) begin
            cp_im_buf_14_fu_268 <= cp_im_reg_3141;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            cp_im_buf_15_fu_272 <= 16'd0;
        end else if ((1'b1 == ap_condition_2114)) begin
            cp_im_buf_15_fu_272 <= cp_im_reg_3141;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            cp_im_buf_1_fu_216 <= 16'd0;
        end else if ((1'b1 == ap_condition_2118)) begin
            cp_im_buf_1_fu_216 <= cp_im_reg_3141;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            cp_im_buf_2_fu_220 <= 16'd0;
        end else if ((1'b1 == ap_condition_2122)) begin
            cp_im_buf_2_fu_220 <= cp_im_reg_3141;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            cp_im_buf_3_fu_224 <= 16'd0;
        end else if ((1'b1 == ap_condition_2126)) begin
            cp_im_buf_3_fu_224 <= cp_im_reg_3141;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            cp_im_buf_4_fu_228 <= 16'd0;
        end else if ((1'b1 == ap_condition_2130)) begin
            cp_im_buf_4_fu_228 <= cp_im_reg_3141;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            cp_im_buf_5_fu_232 <= 16'd0;
        end else if ((1'b1 == ap_condition_2134)) begin
            cp_im_buf_5_fu_232 <= cp_im_reg_3141;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            cp_im_buf_6_fu_236 <= 16'd0;
        end else if ((1'b1 == ap_condition_2138)) begin
            cp_im_buf_6_fu_236 <= cp_im_reg_3141;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            cp_im_buf_7_fu_240 <= 16'd0;
        end else if ((1'b1 == ap_condition_2142)) begin
            cp_im_buf_7_fu_240 <= cp_im_reg_3141;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            cp_im_buf_8_fu_244 <= 16'd0;
        end else if ((1'b1 == ap_condition_2146)) begin
            cp_im_buf_8_fu_244 <= cp_im_reg_3141;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            cp_im_buf_9_fu_248 <= 16'd0;
        end else if ((1'b1 == ap_condition_2150)) begin
            cp_im_buf_9_fu_248 <= cp_im_reg_3141;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            cp_im_buf_fu_212 <= 16'd0;
        end else if ((1'b1 == ap_condition_2154)) begin
            cp_im_buf_fu_212 <= cp_im_reg_3141;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            cp_re_buf_10_fu_188 <= 16'd0;
        end else if ((1'b1 == ap_condition_2094)) begin
            cp_re_buf_10_fu_188 <= cp_re_reg_3120;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            cp_re_buf_11_fu_192 <= 16'd0;
        end else if ((1'b1 == ap_condition_2098)) begin
            cp_re_buf_11_fu_192 <= cp_re_reg_3120;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            cp_re_buf_12_fu_196 <= 16'd0;
        end else if ((1'b1 == ap_condition_2102)) begin
            cp_re_buf_12_fu_196 <= cp_re_reg_3120;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            cp_re_buf_13_fu_200 <= 16'd0;
        end else if ((1'b1 == ap_condition_2106)) begin
            cp_re_buf_13_fu_200 <= cp_re_reg_3120;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            cp_re_buf_14_fu_204 <= 16'd0;
        end else if ((1'b1 == ap_condition_2110)) begin
            cp_re_buf_14_fu_204 <= cp_re_reg_3120;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            cp_re_buf_15_fu_208 <= 16'd0;
        end else if ((1'b1 == ap_condition_2114)) begin
            cp_re_buf_15_fu_208 <= cp_re_reg_3120;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            cp_re_buf_1_fu_152 <= 16'd0;
        end else if ((1'b1 == ap_condition_2118)) begin
            cp_re_buf_1_fu_152 <= cp_re_reg_3120;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            cp_re_buf_2_fu_156 <= 16'd0;
        end else if ((1'b1 == ap_condition_2122)) begin
            cp_re_buf_2_fu_156 <= cp_re_reg_3120;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            cp_re_buf_3_fu_160 <= 16'd0;
        end else if ((1'b1 == ap_condition_2126)) begin
            cp_re_buf_3_fu_160 <= cp_re_reg_3120;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            cp_re_buf_4_fu_164 <= 16'd0;
        end else if ((1'b1 == ap_condition_2130)) begin
            cp_re_buf_4_fu_164 <= cp_re_reg_3120;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            cp_re_buf_5_fu_168 <= 16'd0;
        end else if ((1'b1 == ap_condition_2134)) begin
            cp_re_buf_5_fu_168 <= cp_re_reg_3120;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            cp_re_buf_6_fu_172 <= 16'd0;
        end else if ((1'b1 == ap_condition_2138)) begin
            cp_re_buf_6_fu_172 <= cp_re_reg_3120;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            cp_re_buf_7_fu_176 <= 16'd0;
        end else if ((1'b1 == ap_condition_2142)) begin
            cp_re_buf_7_fu_176 <= cp_re_reg_3120;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            cp_re_buf_8_fu_180 <= 16'd0;
        end else if ((1'b1 == ap_condition_2146)) begin
            cp_re_buf_8_fu_180 <= cp_re_reg_3120;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            cp_re_buf_9_fu_184 <= 16'd0;
        end else if ((1'b1 == ap_condition_2150)) begin
            cp_re_buf_9_fu_184 <= cp_re_reg_3120;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            cp_re_buf_fu_148 <= 16'd0;
        end else if ((1'b1 == ap_condition_2154)) begin
            cp_re_buf_fu_148 <= cp_re_reg_3120;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            delay_line_im_10_fu_384 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_pred1373_state3 == 1'b1))) begin
            delay_line_im_10_fu_384 <= rxD_im_reg_3026;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            delay_line_im_11_fu_380 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_pred1364_state3 == 1'b1))) begin
            delay_line_im_11_fu_380 <= rxD_im_reg_3026;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            delay_line_im_12_fu_376 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_pred1355_state3 == 1'b1))) begin
            delay_line_im_12_fu_376 <= rxD_im_reg_3026;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            delay_line_im_13_fu_372 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_pred1346_state3 == 1'b1))) begin
            delay_line_im_13_fu_372 <= rxD_im_reg_3026;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            delay_line_im_14_fu_368 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_pred1337_state3 == 1'b1))) begin
            delay_line_im_14_fu_368 <= rxD_im_reg_3026;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            delay_line_im_15_fu_364 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_pred1327_state3 == 1'b1))) begin
            delay_line_im_15_fu_364 <= rxD_im_reg_3026;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            delay_line_im_1_fu_420 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_pred1454_state3 == 1'b1))) begin
            delay_line_im_1_fu_420 <= rxD_im_reg_3026;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            delay_line_im_2_fu_416 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_pred1445_state3 == 1'b1))) begin
            delay_line_im_2_fu_416 <= rxD_im_reg_3026;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            delay_line_im_3_fu_412 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_pred1436_state3 == 1'b1))) begin
            delay_line_im_3_fu_412 <= rxD_im_reg_3026;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            delay_line_im_4_fu_408 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_pred1427_state3 == 1'b1))) begin
            delay_line_im_4_fu_408 <= rxD_im_reg_3026;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            delay_line_im_5_fu_404 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_pred1418_state3 == 1'b1))) begin
            delay_line_im_5_fu_404 <= rxD_im_reg_3026;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            delay_line_im_6_fu_400 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_pred1409_state3 == 1'b1))) begin
            delay_line_im_6_fu_400 <= rxD_im_reg_3026;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            delay_line_im_7_fu_396 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_pred1400_state3 == 1'b1))) begin
            delay_line_im_7_fu_396 <= rxD_im_reg_3026;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            delay_line_im_8_fu_392 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_pred1391_state3 == 1'b1))) begin
            delay_line_im_8_fu_392 <= rxD_im_reg_3026;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            delay_line_im_9_fu_388 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_pred1382_state3 == 1'b1))) begin
            delay_line_im_9_fu_388 <= rxD_im_reg_3026;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            delay_line_im_fu_424 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_pred1463_state3 == 1'b1))) begin
            delay_line_im_fu_424 <= rxD_im_reg_3026;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            delay_line_re_10_fu_448 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_pred1373_state3 == 1'b1))) begin
            delay_line_re_10_fu_448 <= rxD_re_reg_3005;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            delay_line_re_11_fu_444 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_pred1364_state3 == 1'b1))) begin
            delay_line_re_11_fu_444 <= rxD_re_reg_3005;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            delay_line_re_12_fu_440 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_pred1355_state3 == 1'b1))) begin
            delay_line_re_12_fu_440 <= rxD_re_reg_3005;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            delay_line_re_13_fu_436 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_pred1346_state3 == 1'b1))) begin
            delay_line_re_13_fu_436 <= rxD_re_reg_3005;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            delay_line_re_14_fu_432 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_pred1337_state3 == 1'b1))) begin
            delay_line_re_14_fu_432 <= rxD_re_reg_3005;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            delay_line_re_15_fu_428 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_pred1327_state3 == 1'b1))) begin
            delay_line_re_15_fu_428 <= rxD_re_reg_3005;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            delay_line_re_1_fu_484 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_pred1454_state3 == 1'b1))) begin
            delay_line_re_1_fu_484 <= rxD_re_reg_3005;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            delay_line_re_2_fu_480 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_pred1445_state3 == 1'b1))) begin
            delay_line_re_2_fu_480 <= rxD_re_reg_3005;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            delay_line_re_3_fu_476 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_pred1436_state3 == 1'b1))) begin
            delay_line_re_3_fu_476 <= rxD_re_reg_3005;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            delay_line_re_4_fu_472 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_pred1427_state3 == 1'b1))) begin
            delay_line_re_4_fu_472 <= rxD_re_reg_3005;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            delay_line_re_5_fu_468 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_pred1418_state3 == 1'b1))) begin
            delay_line_re_5_fu_468 <= rxD_re_reg_3005;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            delay_line_re_6_fu_464 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_pred1409_state3 == 1'b1))) begin
            delay_line_re_6_fu_464 <= rxD_re_reg_3005;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            delay_line_re_7_fu_460 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_pred1400_state3 == 1'b1))) begin
            delay_line_re_7_fu_460 <= rxD_re_reg_3005;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            delay_line_re_8_fu_456 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_pred1391_state3 == 1'b1))) begin
            delay_line_re_8_fu_456 <= rxD_re_reg_3005;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            delay_line_re_9_fu_452 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_pred1382_state3 == 1'b1))) begin
            delay_line_re_9_fu_452 <= rxD_re_reg_3005;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            delay_line_re_fu_488 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_pred1463_state3 == 1'b1))) begin
            delay_line_re_fu_488 <= rxD_re_reg_3005;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            detected_fu_348 <= 1'd0;
        end else if ((1'b1 == ap_condition_2174)) begin
            detected_fu_348 <= ap_phi_mux_detected_1_phi_fu_536_p8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln51_fu_1004_p2 == 1'd1))) begin
            i_fu_144 <= i_11_fu_1010_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_144 <= 31'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            powSumAcc_fu_352 <= 32'd0;
        end else if ((1'b1 == ap_condition_2183)) begin
            powSumAcc_fu_352 <= powSumAcc_2_fu_2135_p2;
        end else if ((1'b1 == ap_condition_2179)) begin
            powSumAcc_fu_352 <= powSumAcc_3_fu_1983_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ps_buf_10_fu_316 <= 16'd0;
        end else if ((1'b1 == ap_condition_2187)) begin
            ps_buf_10_fu_316 <= ps_reg_3167;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ps_buf_11_fu_320 <= 16'd0;
        end else if ((1'b1 == ap_condition_2191)) begin
            ps_buf_11_fu_320 <= ps_reg_3167;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ps_buf_12_fu_324 <= 16'd0;
        end else if ((1'b1 == ap_condition_2195)) begin
            ps_buf_12_fu_324 <= ps_reg_3167;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ps_buf_13_fu_328 <= 16'd0;
        end else if ((1'b1 == ap_condition_2199)) begin
            ps_buf_13_fu_328 <= ps_reg_3167;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ps_buf_14_fu_332 <= 16'd0;
        end else if ((1'b1 == ap_condition_2203)) begin
            ps_buf_14_fu_332 <= ps_reg_3167;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ps_buf_15_fu_336 <= 16'd0;
        end else if ((1'b1 == ap_condition_2207)) begin
            ps_buf_15_fu_336 <= ps_reg_3167;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ps_buf_1_fu_280 <= 16'd0;
        end else if ((1'b1 == ap_condition_2211)) begin
            ps_buf_1_fu_280 <= ps_reg_3167;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ps_buf_2_fu_284 <= 16'd0;
        end else if ((1'b1 == ap_condition_2215)) begin
            ps_buf_2_fu_284 <= ps_reg_3167;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ps_buf_3_fu_288 <= 16'd0;
        end else if ((1'b1 == ap_condition_2219)) begin
            ps_buf_3_fu_288 <= ps_reg_3167;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ps_buf_4_fu_292 <= 16'd0;
        end else if ((1'b1 == ap_condition_2223)) begin
            ps_buf_4_fu_292 <= ps_reg_3167;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ps_buf_5_fu_296 <= 16'd0;
        end else if ((1'b1 == ap_condition_2227)) begin
            ps_buf_5_fu_296 <= ps_reg_3167;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ps_buf_6_fu_300 <= 16'd0;
        end else if ((1'b1 == ap_condition_2231)) begin
            ps_buf_6_fu_300 <= ps_reg_3167;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ps_buf_7_fu_304 <= 16'd0;
        end else if ((1'b1 == ap_condition_2235)) begin
            ps_buf_7_fu_304 <= ps_reg_3167;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ps_buf_8_fu_308 <= 16'd0;
        end else if ((1'b1 == ap_condition_2239)) begin
            ps_buf_8_fu_308 <= ps_reg_3167;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ps_buf_9_fu_312 <= 16'd0;
        end else if ((1'b1 == ap_condition_2243)) begin
            ps_buf_9_fu_312 <= ps_reg_3167;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ps_buf_fu_276 <= 16'd0;
        end else if ((1'b1 == ap_condition_2247)) begin
            ps_buf_fu_276 <= ps_reg_3167;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            startOffset_fu_340 <= 16'd0;
        end else if ((1'b1 == ap_condition_2254)) begin
            startOffset_fu_340 <= startOffset_6_fu_2306_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln95_fu_2263_p2 == 1'd1) & (detected_load_1_load_fu_2232_p1 == 1'd0) & (icmp_ln87_reg_3058_pp0_iter8_reg == 1'd1) & (icmp_ln65_reg_3048_pp0_iter8_reg == 1'd0) & (icmp_ln51_reg_2992_pp0_iter8_reg == 1'd1) & (ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        sustainedCount_fu_344 <= sustainedCount_3_fu_2274_p2;
    end else if ((((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1)) | ((icmp_ln95_fu_2263_p2 == 1'd0) & (detected_load_1_load_fu_2232_p1 == 1'd0) & (icmp_ln87_reg_3058_pp0_iter8_reg == 1'd1) & (icmp_ln65_reg_3048_pp0_iter8_reg == 1'd0) & (icmp_ln51_reg_2992_pp0_iter8_reg == 1'd1) & (ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1)))) begin
        sustainedCount_fu_344 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        ap_predicate_pred1327_state3 <= ((icmp_ln51_reg_2992 == 1'd1) & (trunc_ln51_reg_2996 == 4'd15));
        ap_predicate_pred1337_state3 <= ((icmp_ln51_reg_2992 == 1'd1) & (trunc_ln51_reg_2996 == 4'd14));
        ap_predicate_pred1346_state3 <= ((icmp_ln51_reg_2992 == 1'd1) & (trunc_ln51_reg_2996 == 4'd13));
        ap_predicate_pred1355_state3 <= ((icmp_ln51_reg_2992 == 1'd1) & (trunc_ln51_reg_2996 == 4'd12));
        ap_predicate_pred1364_state3 <= ((icmp_ln51_reg_2992 == 1'd1) & (trunc_ln51_reg_2996 == 4'd11));
        ap_predicate_pred1373_state3 <= ((icmp_ln51_reg_2992 == 1'd1) & (trunc_ln51_reg_2996 == 4'd10));
        ap_predicate_pred1382_state3 <= ((icmp_ln51_reg_2992 == 1'd1) & (trunc_ln51_reg_2996 == 4'd9));
        ap_predicate_pred1391_state3 <= ((icmp_ln51_reg_2992 == 1'd1) & (trunc_ln51_reg_2996 == 4'd8));
        ap_predicate_pred1400_state3 <= ((icmp_ln51_reg_2992 == 1'd1) & (trunc_ln51_reg_2996 == 4'd7));
        ap_predicate_pred1409_state3 <= ((icmp_ln51_reg_2992 == 1'd1) & (trunc_ln51_reg_2996 == 4'd6));
        ap_predicate_pred1418_state3 <= ((icmp_ln51_reg_2992 == 1'd1) & (trunc_ln51_reg_2996 == 4'd5));
        ap_predicate_pred1427_state3 <= ((icmp_ln51_reg_2992 == 1'd1) & (trunc_ln51_reg_2996 == 4'd4));
        ap_predicate_pred1436_state3 <= ((icmp_ln51_reg_2992 == 1'd1) & (trunc_ln51_reg_2996 == 4'd3));
        ap_predicate_pred1445_state3 <= ((icmp_ln51_reg_2992 == 1'd1) & (trunc_ln51_reg_2996 == 4'd2));
        ap_predicate_pred1454_state3 <= ((icmp_ln51_reg_2992 == 1'd1) & (trunc_ln51_reg_2996 == 4'd1));
        ap_predicate_pred1463_state3 <= ((icmp_ln51_reg_2992 == 1'd1) & (trunc_ln51_reg_2996 == 4'd0));
        i_10_reg_2985 <= ap_sig_allocacmp_i_10;
        icmp_ln51_reg_2992 <= icmp_ln51_fu_1004_p2;
        icmp_ln51_reg_2992_pp0_iter1_reg <= icmp_ln51_reg_2992;
        trunc_ln51_reg_2996 <= trunc_ln51_fu_1016_p1;
        trunc_ln51_reg_2996_pp0_iter1_reg <= trunc_ln51_reg_2996;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        icmp_ln51_reg_2992_pp0_iter2_reg <= icmp_ln51_reg_2992_pp0_iter1_reg;
        icmp_ln51_reg_2992_pp0_iter3_reg <= icmp_ln51_reg_2992_pp0_iter2_reg;
        icmp_ln51_reg_2992_pp0_iter4_reg <= icmp_ln51_reg_2992_pp0_iter3_reg;
        icmp_ln51_reg_2992_pp0_iter5_reg <= icmp_ln51_reg_2992_pp0_iter4_reg;
        icmp_ln51_reg_2992_pp0_iter6_reg <= icmp_ln51_reg_2992_pp0_iter5_reg;
        icmp_ln51_reg_2992_pp0_iter7_reg <= icmp_ln51_reg_2992_pp0_iter6_reg;
        icmp_ln51_reg_2992_pp0_iter8_reg <= icmp_ln51_reg_2992_pp0_iter7_reg;
        icmp_ln51_reg_2992_pp0_iter9_reg <= icmp_ln51_reg_2992_pp0_iter8_reg;
        trunc_ln51_reg_2996_pp0_iter2_reg <= trunc_ln51_reg_2996_pp0_iter1_reg;
        trunc_ln51_reg_2996_pp0_iter3_reg <= trunc_ln51_reg_2996_pp0_iter2_reg;
        trunc_ln51_reg_2996_pp0_iter4_reg <= trunc_ln51_reg_2996_pp0_iter3_reg;
        trunc_ln51_reg_2996_pp0_iter5_reg <= trunc_ln51_reg_2996_pp0_iter4_reg;
        trunc_ln51_reg_2996_pp0_iter6_reg <= trunc_ln51_reg_2996_pp0_iter5_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        corrSum_im_1_reg_3193 <= corrSum_im_1_fu_1541_p2;
        corrSum_re_1_reg_3188 <= corrSum_re_1_fu_1524_p2;
        cp_im_reg_3141 <= {{grp_fu_2346_p3[27:12]}};
        cp_re_reg_3120 <= {{grp_fu_2338_p3[27:12]}};
        detected_load_1_reg_3223 <= detected_fu_348;
        icmp_ln65_reg_3048_pp0_iter2_reg <= icmp_ln65_reg_3048;
        icmp_ln65_reg_3048_pp0_iter3_reg <= icmp_ln65_reg_3048_pp0_iter2_reg;
        icmp_ln65_reg_3048_pp0_iter4_reg <= icmp_ln65_reg_3048_pp0_iter3_reg;
        icmp_ln65_reg_3048_pp0_iter5_reg <= icmp_ln65_reg_3048_pp0_iter4_reg;
        icmp_ln65_reg_3048_pp0_iter6_reg <= icmp_ln65_reg_3048_pp0_iter5_reg;
        icmp_ln65_reg_3048_pp0_iter7_reg <= icmp_ln65_reg_3048_pp0_iter6_reg;
        icmp_ln65_reg_3048_pp0_iter8_reg <= icmp_ln65_reg_3048_pp0_iter7_reg;
        icmp_ln65_reg_3048_pp0_iter9_reg <= icmp_ln65_reg_3048_pp0_iter8_reg;
        icmp_ln87_reg_3058_pp0_iter2_reg <= icmp_ln87_reg_3058;
        icmp_ln87_reg_3058_pp0_iter3_reg <= icmp_ln87_reg_3058_pp0_iter2_reg;
        icmp_ln87_reg_3058_pp0_iter4_reg <= icmp_ln87_reg_3058_pp0_iter3_reg;
        icmp_ln87_reg_3058_pp0_iter5_reg <= icmp_ln87_reg_3058_pp0_iter4_reg;
        icmp_ln87_reg_3058_pp0_iter6_reg <= icmp_ln87_reg_3058_pp0_iter5_reg;
        icmp_ln87_reg_3058_pp0_iter7_reg <= icmp_ln87_reg_3058_pp0_iter6_reg;
        icmp_ln87_reg_3058_pp0_iter8_reg <= icmp_ln87_reg_3058_pp0_iter7_reg;
        icmp_ln87_reg_3058_pp0_iter9_reg <= icmp_ln87_reg_3058_pp0_iter8_reg;
        icmp_ln95_reg_3227 <= icmp_ln95_fu_2263_p2;
        icmp_ln97_reg_3231 <= icmp_ln97_fu_2280_p2;
        mul_ln75_1_reg_3088 <= mul_ln75_1_fu_1452_p2;
        mul_ln75_1_reg_3088_pp0_iter3_reg <= mul_ln75_1_reg_3088;
        mul_ln76_reg_3093 <= mul_ln76_fu_1458_p2;
        mul_ln76_reg_3093_pp0_iter3_reg <= mul_ln76_reg_3093;
        mul_ln89_1_reg_3208 <= mul_ln89_1_fu_554_p2;
        mul_ln89_reg_3203 <= mul_ln89_fu_550_p2;
        mul_ln91_reg_3218 <= mul_ln91_fu_558_p2;
        powSumAcc_3_reg_3198 <= powSumAcc_3_fu_1983_p2;
        ps_reg_3167 <= {{ps_fu_1504_p1[28:13]}};
        rxD_im_reg_3026_pp0_iter2_reg <= rxD_im_reg_3026;
        rx_re_reg_3067 <= rx_re_fu_1120_p35;
        startOffset_6_reg_3235 <= startOffset_6_fu_2306_p2;
        tmp_s_reg_3213 <= {{add_ln89_fu_2210_p2[53:22]}};
        trunc_ln93_reg_3062_pp0_iter2_reg <= trunc_ln93_reg_3062;
        trunc_ln93_reg_3062_pp0_iter3_reg <= trunc_ln93_reg_3062_pp0_iter2_reg;
        trunc_ln93_reg_3062_pp0_iter4_reg <= trunc_ln93_reg_3062_pp0_iter3_reg;
        trunc_ln93_reg_3062_pp0_iter5_reg <= trunc_ln93_reg_3062_pp0_iter4_reg;
        trunc_ln93_reg_3062_pp0_iter6_reg <= trunc_ln93_reg_3062_pp0_iter5_reg;
        trunc_ln93_reg_3062_pp0_iter7_reg <= trunc_ln93_reg_3062_pp0_iter6_reg;
        trunc_ln93_reg_3062_pp0_iter8_reg <= trunc_ln93_reg_3062_pp0_iter7_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        icmp_ln65_reg_3048 <= icmp_ln65_fu_1048_p2;
        icmp_ln87_reg_3058 <= icmp_ln87_fu_1063_p2;
        rxD_im_reg_3026 <= {{m0_to_m1_data_dout[31:16]}};
        rxD_re_reg_3005 <= rxD_re_fu_1025_p1;
        trunc_ln93_reg_3062 <= trunc_ln93_fu_1069_p1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln51_fu_1004_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln51_reg_2992_pp0_iter8_reg == 1'd0) & (ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter9_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter9_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter9_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln97_fu_2280_p2 == 1'd0) & (icmp_ln95_fu_2263_p2 == 1'd1) & (detected_load_1_load_fu_2232_p1 == 1'd0) & (icmp_ln87_reg_3058_pp0_iter8_reg == 1'd1) & (icmp_ln65_reg_3048_pp0_iter8_reg == 1'd0) & (icmp_ln51_reg_2992_pp0_iter8_reg == 1'd1)) | ((icmp_ln95_fu_2263_p2 == 1'd0) & (detected_load_1_load_fu_2232_p1 == 1'd0) & (icmp_ln87_reg_3058_pp0_iter8_reg == 1'd1) & (icmp_ln65_reg_3048_pp0_iter8_reg == 1'd0) & (icmp_ln51_reg_2992_pp0_iter8_reg == 1'd1)))) begin
        ap_phi_mux_detected_1_phi_fu_536_p8 = 1'd0;
    end else if ((((detected_load_1_load_fu_2232_p1 == 1'd1) & (icmp_ln87_reg_3058_pp0_iter8_reg == 1'd1) & (icmp_ln65_reg_3048_pp0_iter8_reg == 1'd0) & (icmp_ln51_reg_2992_pp0_iter8_reg == 1'd1)) | ((icmp_ln97_fu_2280_p2 == 1'd1) & (icmp_ln95_fu_2263_p2 == 1'd1) & (detected_load_1_load_fu_2232_p1 == 1'd0) & (icmp_ln87_reg_3058_pp0_iter8_reg == 1'd1) & (icmp_ln65_reg_3048_pp0_iter8_reg == 1'd0) & (icmp_ln51_reg_2992_pp0_iter8_reg == 1'd1)))) begin
        ap_phi_mux_detected_1_phi_fu_536_p8 = 1'd1;
    end else begin
        ap_phi_mux_detected_1_phi_fu_536_p8 = ap_phi_reg_pp0_iter9_detected_1_reg_533;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_i_10 = 31'd0;
    end else begin
        ap_sig_allocacmp_i_10 = i_fu_144;
    end
end

always @ (*) begin
    if (((icmp_ln51_reg_2992_pp0_iter8_reg == 1'd0) & (ap_loop_exit_ready_pp0_iter9_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        detected_out_ap_vld = 1'b1;
    end else begin
        detected_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        grp_fu_2330_ce = 1'b1;
    end else begin
        grp_fu_2330_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        grp_fu_2338_ce = 1'b1;
    end else begin
        grp_fu_2338_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        grp_fu_2346_ce = 1'b1;
    end else begin
        grp_fu_2346_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        grp_fu_2354_ce = 1'b1;
    end else begin
        grp_fu_2354_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        grp_fu_2362_ce = 1'b1;
    end else begin
        grp_fu_2362_ce = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln51_reg_2992 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_grp1))) begin
        m0_to_m1_data_blk_n = m0_to_m1_data_empty_n;
    end else begin
        m0_to_m1_data_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln51_reg_2992 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        m0_to_m1_data_read = 1'b1;
    end else begin
        m0_to_m1_data_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1) & (ap_predicate_op512_write_state11 == 1'b1))) begin
        m1_startOffset_blk_n = m1_startOffset_full_n;
    end else begin
        m1_startOffset_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_predicate_op512_write_state11 == 1'b1))) begin
        m1_startOffset_write = 1'b1;
    end else begin
        m1_startOffset_write = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln51_reg_2992 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_grp1))) begin
        m1_to_m2_data_blk_n = m1_to_m2_data_full_n;
    end else begin
        m1_to_m2_data_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln51_reg_2992 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        m1_to_m2_data_write = 1'b1;
    end else begin
        m1_to_m2_data_write = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln51_reg_2992_pp0_iter8_reg == 1'd0) & (ap_loop_exit_ready_pp0_iter9_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        startOffset_out_ap_vld = 1'b1;
    end else begin
        startOffset_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln89_fu_2210_p2 = (mul_ln89_reg_3203 + mul_ln89_1_reg_3208);

assign add_ln98_fu_2301_p2 = (trunc_ln93_reg_3062_pp0_iter8_reg + xor_ln98_fu_2295_p2);

assign and_ln95_1_fu_2251_p3 = {{tmp_1_fu_2242_p4}, {21'd0}};

assign and_ln_fu_2235_p3 = {{tmp_s_reg_3213}, {22'd0}};

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp1)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_block_state11_pp0_stage0_iter10_grp1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp1)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_block_state11_pp0_stage0_iter10_grp1)));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp1)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_block_state11_pp0_stage0_iter10_grp1)));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp1)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_block_state11_pp0_stage0_iter10_grp1)));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state11_pp0_stage0_iter10_grp1 = ((m1_startOffset_full_n == 1'b0) & (ap_predicate_op512_write_state11 == 1'b1));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1_grp1 = (((icmp_ln51_reg_2992 == 1'd1) & (m1_to_m2_data_full_n == 1'b0)) | ((icmp_ln51_reg_2992 == 1'd1) & (m0_to_m1_data_empty_n == 1'b0)));
end

always @ (*) begin
    ap_condition_2086 = ((icmp_ln87_reg_3058_pp0_iter5_reg == 1'd0) & (icmp_ln65_reg_3048_pp0_iter5_reg == 1'd0) & (icmp_ln51_reg_2992_pp0_iter5_reg == 1'd1) & (ap_enable_reg_pp0_iter6 == 1'b1));
end

always @ (*) begin
    ap_condition_2090 = ((icmp_ln87_reg_3058_pp0_iter5_reg == 1'd1) & (icmp_ln65_reg_3048_pp0_iter5_reg == 1'd0) & (icmp_ln51_reg_2992_pp0_iter5_reg == 1'd1) & (ap_enable_reg_pp0_iter6 == 1'b1));
end

always @ (*) begin
    ap_condition_2094 = ((icmp_ln65_reg_3048_pp0_iter5_reg == 1'd0) & (trunc_ln51_reg_2996_pp0_iter5_reg == 4'd10) & (icmp_ln51_reg_2992_pp0_iter5_reg == 1'd1) & (ap_enable_reg_pp0_iter6 == 1'b1));
end

always @ (*) begin
    ap_condition_2098 = ((icmp_ln65_reg_3048_pp0_iter5_reg == 1'd0) & (trunc_ln51_reg_2996_pp0_iter5_reg == 4'd11) & (icmp_ln51_reg_2992_pp0_iter5_reg == 1'd1) & (ap_enable_reg_pp0_iter6 == 1'b1));
end

always @ (*) begin
    ap_condition_2102 = ((icmp_ln65_reg_3048_pp0_iter5_reg == 1'd0) & (trunc_ln51_reg_2996_pp0_iter5_reg == 4'd12) & (icmp_ln51_reg_2992_pp0_iter5_reg == 1'd1) & (ap_enable_reg_pp0_iter6 == 1'b1));
end

always @ (*) begin
    ap_condition_2106 = ((icmp_ln65_reg_3048_pp0_iter5_reg == 1'd0) & (trunc_ln51_reg_2996_pp0_iter5_reg == 4'd13) & (icmp_ln51_reg_2992_pp0_iter5_reg == 1'd1) & (ap_enable_reg_pp0_iter6 == 1'b1));
end

always @ (*) begin
    ap_condition_2110 = ((icmp_ln65_reg_3048_pp0_iter5_reg == 1'd0) & (trunc_ln51_reg_2996_pp0_iter5_reg == 4'd14) & (icmp_ln51_reg_2992_pp0_iter5_reg == 1'd1) & (ap_enable_reg_pp0_iter6 == 1'b1));
end

always @ (*) begin
    ap_condition_2114 = ((icmp_ln65_reg_3048_pp0_iter5_reg == 1'd0) & (trunc_ln51_reg_2996_pp0_iter5_reg == 4'd15) & (icmp_ln51_reg_2992_pp0_iter5_reg == 1'd1) & (ap_enable_reg_pp0_iter6 == 1'b1));
end

always @ (*) begin
    ap_condition_2118 = ((icmp_ln65_reg_3048_pp0_iter5_reg == 1'd0) & (trunc_ln51_reg_2996_pp0_iter5_reg == 4'd1) & (icmp_ln51_reg_2992_pp0_iter5_reg == 1'd1) & (ap_enable_reg_pp0_iter6 == 1'b1));
end

always @ (*) begin
    ap_condition_2122 = ((icmp_ln65_reg_3048_pp0_iter5_reg == 1'd0) & (trunc_ln51_reg_2996_pp0_iter5_reg == 4'd2) & (icmp_ln51_reg_2992_pp0_iter5_reg == 1'd1) & (ap_enable_reg_pp0_iter6 == 1'b1));
end

always @ (*) begin
    ap_condition_2126 = ((icmp_ln65_reg_3048_pp0_iter5_reg == 1'd0) & (trunc_ln51_reg_2996_pp0_iter5_reg == 4'd3) & (icmp_ln51_reg_2992_pp0_iter5_reg == 1'd1) & (ap_enable_reg_pp0_iter6 == 1'b1));
end

always @ (*) begin
    ap_condition_2130 = ((icmp_ln65_reg_3048_pp0_iter5_reg == 1'd0) & (trunc_ln51_reg_2996_pp0_iter5_reg == 4'd4) & (icmp_ln51_reg_2992_pp0_iter5_reg == 1'd1) & (ap_enable_reg_pp0_iter6 == 1'b1));
end

always @ (*) begin
    ap_condition_2134 = ((icmp_ln65_reg_3048_pp0_iter5_reg == 1'd0) & (trunc_ln51_reg_2996_pp0_iter5_reg == 4'd5) & (icmp_ln51_reg_2992_pp0_iter5_reg == 1'd1) & (ap_enable_reg_pp0_iter6 == 1'b1));
end

always @ (*) begin
    ap_condition_2138 = ((icmp_ln65_reg_3048_pp0_iter5_reg == 1'd0) & (trunc_ln51_reg_2996_pp0_iter5_reg == 4'd6) & (icmp_ln51_reg_2992_pp0_iter5_reg == 1'd1) & (ap_enable_reg_pp0_iter6 == 1'b1));
end

always @ (*) begin
    ap_condition_2142 = ((icmp_ln65_reg_3048_pp0_iter5_reg == 1'd0) & (trunc_ln51_reg_2996_pp0_iter5_reg == 4'd7) & (icmp_ln51_reg_2992_pp0_iter5_reg == 1'd1) & (ap_enable_reg_pp0_iter6 == 1'b1));
end

always @ (*) begin
    ap_condition_2146 = ((icmp_ln65_reg_3048_pp0_iter5_reg == 1'd0) & (trunc_ln51_reg_2996_pp0_iter5_reg == 4'd8) & (icmp_ln51_reg_2992_pp0_iter5_reg == 1'd1) & (ap_enable_reg_pp0_iter6 == 1'b1));
end

always @ (*) begin
    ap_condition_2150 = ((icmp_ln65_reg_3048_pp0_iter5_reg == 1'd0) & (trunc_ln51_reg_2996_pp0_iter5_reg == 4'd9) & (icmp_ln51_reg_2992_pp0_iter5_reg == 1'd1) & (ap_enable_reg_pp0_iter6 == 1'b1));
end

always @ (*) begin
    ap_condition_2154 = ((icmp_ln65_reg_3048_pp0_iter5_reg == 1'd0) & (trunc_ln51_reg_2996_pp0_iter5_reg == 4'd0) & (icmp_ln51_reg_2992_pp0_iter5_reg == 1'd1) & (ap_enable_reg_pp0_iter6 == 1'b1));
end

always @ (*) begin
    ap_condition_2174 = ((icmp_ln87_reg_3058_pp0_iter8_reg == 1'd1) & (icmp_ln65_reg_3048_pp0_iter8_reg == 1'd0) & (icmp_ln51_reg_2992_pp0_iter8_reg == 1'd1) & (ap_enable_reg_pp0_iter9 == 1'b1));
end

always @ (*) begin
    ap_condition_2179 = ((icmp_ln87_reg_3058_pp0_iter6_reg == 1'd0) & (icmp_ln65_reg_3048_pp0_iter6_reg == 1'd0) & (icmp_ln51_reg_2992_pp0_iter6_reg == 1'd1) & (ap_enable_reg_pp0_iter7 == 1'b1));
end

always @ (*) begin
    ap_condition_2183 = ((icmp_ln87_reg_3058_pp0_iter6_reg == 1'd1) & (icmp_ln65_reg_3048_pp0_iter6_reg == 1'd0) & (icmp_ln51_reg_2992_pp0_iter6_reg == 1'd1) & (ap_enable_reg_pp0_iter7 == 1'b1));
end

always @ (*) begin
    ap_condition_2187 = ((icmp_ln65_reg_3048_pp0_iter6_reg == 1'd0) & (trunc_ln51_reg_2996_pp0_iter6_reg == 4'd10) & (icmp_ln51_reg_2992_pp0_iter6_reg == 1'd1) & (ap_enable_reg_pp0_iter7 == 1'b1));
end

always @ (*) begin
    ap_condition_2191 = ((icmp_ln65_reg_3048_pp0_iter6_reg == 1'd0) & (trunc_ln51_reg_2996_pp0_iter6_reg == 4'd11) & (icmp_ln51_reg_2992_pp0_iter6_reg == 1'd1) & (ap_enable_reg_pp0_iter7 == 1'b1));
end

always @ (*) begin
    ap_condition_2195 = ((icmp_ln65_reg_3048_pp0_iter6_reg == 1'd0) & (trunc_ln51_reg_2996_pp0_iter6_reg == 4'd12) & (icmp_ln51_reg_2992_pp0_iter6_reg == 1'd1) & (ap_enable_reg_pp0_iter7 == 1'b1));
end

always @ (*) begin
    ap_condition_2199 = ((icmp_ln65_reg_3048_pp0_iter6_reg == 1'd0) & (trunc_ln51_reg_2996_pp0_iter6_reg == 4'd13) & (icmp_ln51_reg_2992_pp0_iter6_reg == 1'd1) & (ap_enable_reg_pp0_iter7 == 1'b1));
end

always @ (*) begin
    ap_condition_2203 = ((icmp_ln65_reg_3048_pp0_iter6_reg == 1'd0) & (trunc_ln51_reg_2996_pp0_iter6_reg == 4'd14) & (icmp_ln51_reg_2992_pp0_iter6_reg == 1'd1) & (ap_enable_reg_pp0_iter7 == 1'b1));
end

always @ (*) begin
    ap_condition_2207 = ((icmp_ln65_reg_3048_pp0_iter6_reg == 1'd0) & (trunc_ln51_reg_2996_pp0_iter6_reg == 4'd15) & (icmp_ln51_reg_2992_pp0_iter6_reg == 1'd1) & (ap_enable_reg_pp0_iter7 == 1'b1));
end

always @ (*) begin
    ap_condition_2211 = ((icmp_ln65_reg_3048_pp0_iter6_reg == 1'd0) & (trunc_ln51_reg_2996_pp0_iter6_reg == 4'd1) & (icmp_ln51_reg_2992_pp0_iter6_reg == 1'd1) & (ap_enable_reg_pp0_iter7 == 1'b1));
end

always @ (*) begin
    ap_condition_2215 = ((icmp_ln65_reg_3048_pp0_iter6_reg == 1'd0) & (trunc_ln51_reg_2996_pp0_iter6_reg == 4'd2) & (icmp_ln51_reg_2992_pp0_iter6_reg == 1'd1) & (ap_enable_reg_pp0_iter7 == 1'b1));
end

always @ (*) begin
    ap_condition_2219 = ((icmp_ln65_reg_3048_pp0_iter6_reg == 1'd0) & (trunc_ln51_reg_2996_pp0_iter6_reg == 4'd3) & (icmp_ln51_reg_2992_pp0_iter6_reg == 1'd1) & (ap_enable_reg_pp0_iter7 == 1'b1));
end

always @ (*) begin
    ap_condition_2223 = ((icmp_ln65_reg_3048_pp0_iter6_reg == 1'd0) & (trunc_ln51_reg_2996_pp0_iter6_reg == 4'd4) & (icmp_ln51_reg_2992_pp0_iter6_reg == 1'd1) & (ap_enable_reg_pp0_iter7 == 1'b1));
end

always @ (*) begin
    ap_condition_2227 = ((icmp_ln65_reg_3048_pp0_iter6_reg == 1'd0) & (trunc_ln51_reg_2996_pp0_iter6_reg == 4'd5) & (icmp_ln51_reg_2992_pp0_iter6_reg == 1'd1) & (ap_enable_reg_pp0_iter7 == 1'b1));
end

always @ (*) begin
    ap_condition_2231 = ((icmp_ln65_reg_3048_pp0_iter6_reg == 1'd0) & (trunc_ln51_reg_2996_pp0_iter6_reg == 4'd6) & (icmp_ln51_reg_2992_pp0_iter6_reg == 1'd1) & (ap_enable_reg_pp0_iter7 == 1'b1));
end

always @ (*) begin
    ap_condition_2235 = ((icmp_ln65_reg_3048_pp0_iter6_reg == 1'd0) & (trunc_ln51_reg_2996_pp0_iter6_reg == 4'd7) & (icmp_ln51_reg_2992_pp0_iter6_reg == 1'd1) & (ap_enable_reg_pp0_iter7 == 1'b1));
end

always @ (*) begin
    ap_condition_2239 = ((icmp_ln65_reg_3048_pp0_iter6_reg == 1'd0) & (trunc_ln51_reg_2996_pp0_iter6_reg == 4'd8) & (icmp_ln51_reg_2992_pp0_iter6_reg == 1'd1) & (ap_enable_reg_pp0_iter7 == 1'b1));
end

always @ (*) begin
    ap_condition_2243 = ((icmp_ln65_reg_3048_pp0_iter6_reg == 1'd0) & (trunc_ln51_reg_2996_pp0_iter6_reg == 4'd9) & (icmp_ln51_reg_2992_pp0_iter6_reg == 1'd1) & (ap_enable_reg_pp0_iter7 == 1'b1));
end

always @ (*) begin
    ap_condition_2247 = ((icmp_ln65_reg_3048_pp0_iter6_reg == 1'd0) & (trunc_ln51_reg_2996_pp0_iter6_reg == 4'd0) & (icmp_ln51_reg_2992_pp0_iter6_reg == 1'd1) & (ap_enable_reg_pp0_iter7 == 1'b1));
end

always @ (*) begin
    ap_condition_2254 = ((icmp_ln97_fu_2280_p2 == 1'd1) & (icmp_ln95_fu_2263_p2 == 1'd1) & (detected_load_1_load_fu_2232_p1 == 1'd0) & (icmp_ln87_reg_3058_pp0_iter8_reg == 1'd1) & (icmp_ln65_reg_3048_pp0_iter8_reg == 1'd0) & (icmp_ln51_reg_2992_pp0_iter8_reg == 1'd1) & (ap_enable_reg_pp0_iter9 == 1'b1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter9_detected_1_reg_533 = 'bx;

always @ (*) begin
    ap_predicate_op512_write_state11 = ((detected_load_1_reg_3223 == 1'd0) & (icmp_ln87_reg_3058_pp0_iter9_reg == 1'd1) & (icmp_ln65_reg_3048_pp0_iter9_reg == 1'd0) & (icmp_ln51_reg_2992_pp0_iter9_reg == 1'd1) & (icmp_ln97_reg_3231 == 1'd1) & (icmp_ln95_reg_3227 == 1'd1));
end

assign ap_ready = ap_ready_sig;

assign corrSum_im_1_fu_1541_p2 = ($signed(corrSum_im_fu_356) + $signed(sext_ln83_fu_1537_p1));

assign corrSum_im_2_fu_1825_p2 = ($signed(corrSum_im_1_fu_1541_p2) - $signed(sext_ln111_fu_1821_p1));

assign corrSum_re_1_fu_1524_p2 = ($signed(corrSum_re_fu_360) + $signed(sext_ln82_fu_1520_p1));

assign corrSum_re_2_fu_1736_p2 = ($signed(corrSum_re_1_fu_1524_p2) - $signed(sext_ln110_fu_1732_p1));

assign detected_load_1_load_fu_2232_p1 = detected_fu_348;

assign detected_out = detected_fu_348;

assign empty_fu_2291_p1 = sustainedCount_fu_344[15:0];

assign grp_fu_2330_p0 = sext_ln78_fu_1059_p1;

assign grp_fu_2330_p1 = sext_ln78_fu_1059_p1;

assign grp_fu_2338_p0 = sext_ln75_fu_1438_p1;

assign grp_fu_2338_p1 = sext_ln75_1_fu_1442_p1;

assign grp_fu_2346_p0 = sext_ln75_fu_1438_p1;

assign grp_fu_2346_p1 = sext_ln75_3_fu_1449_p1;

assign grp_fu_2354_p0 = sext_ln79_1_fu_1464_p1;

assign grp_fu_2354_p1 = sext_ln79_1_fu_1464_p1;

assign grp_fu_2362_p0 = sext_ln79_fu_1477_p1;

assign grp_fu_2362_p1 = sext_ln79_fu_1477_p1;

assign i_11_fu_1010_p2 = (ap_sig_allocacmp_i_10 + 31'd1);

assign icmp_ln51_fu_1004_p2 = (($signed(zext_ln51_fu_1000_p1) < $signed(p_read)) ? 1'b1 : 1'b0);

assign icmp_ln65_fu_1048_p2 = ((tmp_fu_1039_p4 == 27'd0) ? 1'b1 : 1'b0);

assign icmp_ln87_fu_1063_p2 = ((n_fu_1054_p2 > 31'd14) ? 1'b1 : 1'b0);

assign icmp_ln95_fu_2263_p2 = (($signed(sext_ln95_fu_2259_p1) < $signed(and_ln_fu_2235_p3)) ? 1'b1 : 1'b0);

assign icmp_ln97_fu_2280_p2 = (($signed(sustainedCount_3_fu_2274_p2) > $signed(32'd23)) ? 1'b1 : 1'b0);

assign m1_startOffset_din = startOffset_6_reg_3235;

assign m1_to_m2_data_din = m0_to_m1_data_dout;

assign mul_ln75_1_fu_1452_p0 = sext_ln75_2_fu_1445_p1;

assign mul_ln75_1_fu_1452_p1 = sext_ln75_3_fu_1449_p1;

assign mul_ln76_fu_1458_p0 = sext_ln75_2_fu_1445_p1;

assign mul_ln76_fu_1458_p1 = sext_ln75_1_fu_1442_p1;

assign mul_ln78_1_fu_1471_p0 = sext_ln78_1_fu_1468_p1;

assign mul_ln78_1_fu_1471_p1 = sext_ln78_1_fu_1468_p1;

assign mul_ln89_1_fu_554_p0 = sext_ln89_1_fu_1999_p1;

assign mul_ln89_1_fu_554_p1 = sext_ln89_1_fu_1999_p1;

assign mul_ln89_fu_550_p0 = sext_ln89_fu_1994_p1;

assign mul_ln89_fu_550_p1 = sext_ln89_fu_1994_p1;

assign mul_ln91_fu_558_p0 = sext_ln91_fu_2224_p1;

assign mul_ln91_fu_558_p1 = sext_ln91_fu_2224_p1;

assign n_fu_1054_p2 = ($signed(i_10_reg_2985) + $signed(31'd2147483632));

assign powSumAcc_2_fu_2135_p2 = ($signed(powSumAcc_3_fu_1983_p2) - $signed(sext_ln112_fu_2131_p1));

assign powSumAcc_3_fu_1983_p2 = ($signed(powSumAcc_fu_352) + $signed(sext_ln84_fu_1979_p1));

assign ps_fu_1504_p1 = grp_fu_2362_p3;

assign rxD_re_fu_1025_p1 = m0_to_m1_data_dout[15:0];

assign rx_im_fu_1239_p33 = 'bx;

assign rx_re_fu_1120_p33 = 'bx;

assign sext_ln110_fu_1732_p1 = $signed(shl_ln9_fu_1724_p3);

assign sext_ln111_fu_1821_p1 = $signed(shl_ln1_fu_1813_p3);

assign sext_ln112_fu_2131_p1 = $signed(shl_ln2_fu_2123_p3);

assign sext_ln75_1_fu_1442_p1 = rxD_re_reg_3005;

assign sext_ln75_2_fu_1445_p1 = rx_im_fu_1239_p35;

assign sext_ln75_3_fu_1449_p1 = rxD_im_reg_3026;

assign sext_ln75_fu_1438_p1 = rx_re_fu_1120_p35;

assign sext_ln78_1_fu_1468_p1 = rxD_im_reg_3026_pp0_iter2_reg;

assign sext_ln78_fu_1059_p1 = rxD_re_fu_1025_p1;

assign sext_ln79_1_fu_1464_p1 = rx_im_fu_1239_p35;

assign sext_ln79_fu_1477_p1 = rx_re_reg_3067;

assign sext_ln82_fu_1520_p1 = $signed(shl_ln_fu_1513_p3);

assign sext_ln83_fu_1537_p1 = $signed(shl_ln7_fu_1530_p3);

assign sext_ln84_fu_1979_p1 = $signed(shl_ln8_fu_1972_p3);

assign sext_ln89_1_fu_1999_p1 = corrSum_im_1_reg_3193;

assign sext_ln89_fu_1994_p1 = corrSum_re_1_reg_3188;

assign sext_ln91_fu_2224_p1 = powSumAcc_3_reg_3198;

assign sext_ln95_fu_2259_p1 = $signed(and_ln95_1_fu_2251_p3);

assign shl_ln1_fu_1813_p3 = {{tmp_23_i_fu_1742_p35}, {10'd0}};

assign shl_ln2_fu_2123_p3 = {{tmp_24_i_fu_2052_p35}, {10'd0}};

assign shl_ln7_fu_1530_p3 = {{cp_im_reg_3141}, {10'd0}};

assign shl_ln8_fu_1972_p3 = {{ps_reg_3167}, {10'd0}};

assign shl_ln9_fu_1724_p3 = {{tmp_22_i_fu_1653_p35}, {10'd0}};

assign shl_ln_fu_1513_p3 = {{cp_re_reg_3120}, {10'd0}};

assign startOffset_6_fu_2306_p2 = ($signed(add_ln98_fu_2301_p2) + $signed(16'd65506));

assign startOffset_out = startOffset_fu_340;

assign sustainedCount_3_fu_2274_p2 = (sustainedCount_fu_344 + 32'd1);

assign tmp_1_fu_2242_p4 = {{mul_ln91_reg_3218[53:22]}};

assign tmp_22_i_fu_1653_p33 = 'bx;

assign tmp_23_i_fu_1742_p33 = 'bx;

assign tmp_24_i_fu_2052_p33 = 'bx;

assign tmp_fu_1039_p4 = {{i_10_reg_2985[30:4]}};

assign trunc_ln51_fu_1016_p1 = ap_sig_allocacmp_i_10[3:0];

assign trunc_ln93_fu_1069_p1 = i_10_reg_2985[15:0];

assign xor_ln98_fu_2295_p2 = (empty_fu_2291_p1 ^ 16'd65535);

assign zext_ln51_fu_1000_p1 = ap_sig_allocacmp_i_10;

endmodule //system_top_module1_packet_detect_Pipeline_STREAM_LOOP
